In [1]:
import selenium
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException
from selenium.common.exceptions import ElementNotInteractableException
import pandas as pd
import numpy as np
import time

In [441]:
driver=webdriver.Chrome("chromedriver.exe")
driver.get('https://www.cardekho.com/')

In [432]:
used_car_ele=driver.find_element_by_xpath('//a[@title="Cardekho Used Cars"]')
used_car_url=used_car_ele.get_attribute('href')
driver.get(used_car_url)

In [433]:
for _ in range(500):
            driver.execute_script("window.scrollBy(0,20)")
city_url_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-4 gsc_col-sm-3 gsc_col-md-2"]//a')
city_url=[]
city_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-4 gsc_col-sm-3 gsc_col-md-2"]//a//span[3]')
city=[]
for ele in city_url_ele[:12]:
    city_url.append(ele.get_attribute('href'))
    
for ele in city_ele:
    city.append(ele.text)

In [453]:
model=[]
brand=[]
variant=[]
price=[]
make_year=[]
fuel=[]
km=[]
engine=[]
owner=[]
transmission=[]
mileage=[]
max_power=[]
torque=[]
body_type=[]
location=[]

In [454]:
#city 11
for i in range(1):
    for j in range(6):
        driver.get(city_url[11])
        for _ in range(100):
            driver.execute_script("window.scrollBy(0,20)")
        body_type_ele=driver.find_elements_by_xpath('//ul[@class="checkBoxWrap bodyTypes cd-bodyTicon"]//li')
        b_type=body_type_ele[j].text
        try:
            driver.implicitly_wait(10)
            ActionChains(driver).move_to_element(body_type_ele[j]).click(body_type_ele[j]).perform()
            
        except ElementNotInteractableException:
            continue
        
        except StaleElementReferenceException:
            continue

        for _ in range(10000):
            driver.execute_script("window.scrollBy(0,10)")

        urls=[]
        url_ele=driver.find_elements_by_xpath('//div[@class="gsc_col-xs-7 carsName"]//a')
        for ele in url_ele:
            try:
                urls.append(ele.get_attribute('href'))
            except StaleElementReferenceException:
                continue
    
        for url in urls:
            driver.get(url)
            for _ in range(50):
                driver.execute_script("window.scrollBy(0,20)")
            try:
                price_ele=driver.find_element_by_xpath('//span[@class="amount"]')
                pr=float(price_ele.text[:-6])
                price.append(int(pr*100000))
                    
                model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1[2]')
                model.append(model_ele.text)
                    
                str=model_ele.text
                for k in range(len(str)):
                    if str[k]==' ':
                        x=k
                        break
                brand.append(str[:x])
                
                info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6"]')
                make_year.append(info_ele[0].text)
                km.append(info_ele[2].text[:-4])
                
                owner.append(info_ele[3].text)
                print(info_ele[3].text)
                fuel.append(info_ele[4].text)
                transmission.append(info_ele[5].text)
                mileage.append(info_ele[8].text[8:-5])
                
                if len(info_ele)>8:
                    engine.append(info_ele[9].text[7:-3])
                    
                    if len(info_ele)>=10:
                        max_power.append(info_ele[10].text)
                        torque.append(info_ele[11].text)
                    else:
                        max_power.append(None)
                        torque.append(None)
                    
                else:
                    engine.append(None)
                    max_power.append(None)
                    torque.append(None)
                    
            except NoSuchElementException:
                try:
                    price_ele=driver.find_element_by_xpath('//div[@class="priceSection"]//span[2]')
                    str=price_ele.text
                    price.append(str.replace(',',''))
                
                    model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1')
                    model.append(model_ele.text[5:])
                
                    str=model_ele.text[5:]
                    for k in range(len(str)):
                        if str[k]==' ':
                            x=k
                            break
                    brand.append(str[:x])
                    
                    info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6 gsc_col-md-4"]')
                    make_year.append(info_ele[0].text[10:])
                    fuel.append(info_ele[2].text[5:])
                    km.append(info_ele[3].text[11:-4])
                    engine.append(info_ele[4].text[20:-3])
                    owner.append(info_ele[5].text)
                    print(info_ele[5].text)
                
                    if len(info_ele)>=12:
                        transmission.append(info_ele[7].text[13:])
                        mileage.append(info_ele[9].text[8:-5])
                        max_power.append(info_ele[11].text)
                        torque.append(info_ele[12].text)
                    else:
                        transmission.append(None)
                        mileage.append(None)
                        max_power.append(None)
                        torque.append(None)
                except NoSuchElementException:
                    continue
    
            try:
                var_ele=driver.find_element_by_xpath('//div[@class="variant-name"]')
                variant.append(var_ele.text)
        
            except NoSuchElementException:
                variant.append(None)
   
            body_type.append(b_type)
            location.append(city[i])
            if len(owner)<len(model):
                owner.append(None)
            print(len(urls),len(owner),len(location),city[11],'\n')

No Of Owner(s)
2nd Owner
700 1 1 Pune

No Of Owner(s)
2nd Owner
700 2 2 Pune

No Of Owner(s)
1st Owner
700 3 3 Pune

No Of Owner(s)
1st Owner
700 4 4 Pune

No Of Owner(s)
1st Owner
700 5 5 Pune

No Of Owner(s)
1st Owner
700 6 6 Pune

No Of Owner(s)
1st Owner
700 7 7 Pune

No Of Owner(s)
1st Owner
700 8 8 Pune

No Of Owner(s)
1st Owner
700 9 9 Pune

No Of Owner(s)
1st Owner
700 10 10 Pune

No Of Owner(s)
2nd Owner
700 11 11 Pune

No Of Owner(s)
1st Owner
700 12 12 Pune

No Of Owner(s)
1st Owner
700 13 13 Pune

No Of Owner(s)
1st Owner
700 14 14 Pune

First Owner
700 15 15 Pune

First Owner
700 16 16 Pune

No Of Owner(s)
1st Owner
700 17 17 Pune

First Owner
700 18 18 Pune

No Of Owner(s)
1st Owner
700 19 19 Pune

No Of Owner(s)
1st Owner
700 20 20 Pune

No Of Owner(s)
2nd Owner
700 21 21 Pune

No Of Owner(s)
1st Owner
700 22 22 Pune

No Of Owner(s)
1st Owner
700 23 23 Pune

No Of Owner(s)
1st Owner
700 24 24 Pune

No Of Owner(s)
1st Owner
700 25 25 Pune

No Of Owner(s)
1st Owner
700 26 26 Pune

No Of Owner(s)
1st Owner
700 27 27 Pune

No Of Owner(s)
1st Owner
700 28 28 Pune

No Of Owner(s)
1st Owner
700 29 29 Pune

No Of Owner(s)
2nd Owner
700 30 30 Pune

No Of Owner(s)
1st Owner
700 31 31 Pune

No Of Owner(s)
1st Owner
700 32 32 Pune

No Of Owner(s)
1st Owner
700 33 33 Pune

No Of Owner(s)
1st Owner
700 34 34 Pune

No Of Owner(s)
1st Owner
700 35 35 Pune

No Of Owner(s)
2nd Owner
700 36 36 Pune

No Of Owner(s)
1st Owner
700 37 37 Pune

No Of Owner(s)
1st Owner
700 38 38 Pune

No Of Owner(s)
1st Owner
700 39 39 Pune

No Of Owner(s)
1st Owner
700 40 40 Pune

No Of Owner(s)
1st Owner
700 41 41 Pune

No Of Owner(s)
1st Owner
700 42 42 Pune

No Of Owner(s)
1st Owner
700 43 43 Pune

No Of Owner(s)
1st Owner
700 44 44 Pune

No Of Owner(s)
1st Owner
700 45 45 Pune

No Of Owner(s)
1st Owner
700 46 46 Pune

No Of Owner(s)
1st Owner
700 47 47 Pune

No Of Owner(s)
1st Owner
700 48 48 Pune

No Of Owner(s)
1st Owner
700 49 49 Pune

No Of Owner(s)
1st Owner
700 50 50 Pune

No Of Owner(s)
1st Owner
700 51 51 Pune

No Of Owner(s)
1st Owner
700 52 52 Pune

No Of Owner(s)
1st Owner
700 53 53 Pune

No Of Owner(s)
1st Owner
700 54 54 Pune

No Of Owner(s)
1st Owner
700 55 55 Pune

No Of Owner(s)
1st Owner
700 56 56 Pune

No Of Owner(s)
1st Owner
700 57 57 Pune

No Of Owner(s)
2nd Owner
700 58 58 Pune

No Of Owner(s)
2nd Owner
700 59 59 Pune

No Of Owner(s)
1st Owner
700 60 60 Pune

No Of Owner(s)
1st Owner
700 61 61 Pune

No Of Owner(s)
1st Owner
700 62 62 Pune

No Of Owner(s)
1st Owner
700 63 63 Pune

No Of Owner(s)
1st Owner
700 64 64 Pune

No Of Owner(s)
1st Owner
700 65 65 Pune

No Of Owner(s)
1st Owner
700 66 66 Pune

No Of Owner(s)
1st Owner
700 67 67 Pune

No Of Owner(s)
1st Owner
700 68 68 Pune

No Of Owner(s)
1st Owner
700 69 69 Pune

No Of Owner(s)
1st Owner
700 70 70 Pune

No Of Owner(s)
1st Owner
700 71 71 Pune

No Of Owner(s)
2nd Owner
700 72 72 Pune

No Of Owner(s)
1st Owner
700 73 73 Pune

No Of Owner(s)
1st Owner
700 74 74 Pune

No Of Owner(s)
1st Owner
700 75 75 Pune

No Of Owner(s)
1st Owner
700 76 76 Pune

No Of Owner(s)
1st Owner
700 77 77 Pune

No Of Owner(s)
1st Owner
700 78 78 Pune

No Of Owner(s)
1st Owner
700 79 79 Pune

No Of Owner(s)
1st Owner
700 80 80 Pune

No Of Owner(s)
1st Owner
700 81 81 Pune

No Of Owner(s)
1st Owner
700 82 82 Pune

No Of Owner(s)
2nd Owner
700 83 83 Pune

No Of Owner(s)
1st Owner
700 84 84 Pune

No Of Owner(s)
1st Owner
700 85 85 Pune

No Of Owner(s)
1st Owner
700 86 86 Pune

No Of Owner(s)
1st Owner
700 87 87 Pune

No Of Owner(s)
1st Owner
700 88 88 Pune

No Of Owner(s)
1st Owner
700 89 89 Pune

No Of Owner(s)
1st Owner
700 90 90 Pune

No Of Owner(s)
1st Owner
700 91 91 Pune

No Of Owner(s)
1st Owner
700 92 92 Pune

No Of Owner(s)
1st Owner
700 93 93 Pune

No Of Owner(s)
1st Owner
700 94 94 Pune

No Of Owner(s)
2nd Owner
700 95 95 Pune

No Of Owner(s)
1st Owner
700 96 96 Pune

No Of Owner(s)
1st Owner
700 97 97 Pune

No Of Owner(s)
1st Owner
700 98 98 Pune

No Of Owner(s)
1st Owner
700 99 99 Pune

No Of Owner(s)
1st Owner
700 100 100 Pune

No Of Owner(s)
1st Owner
700 101 101 Pune

No Of Owner(s)
1st Owner
700 102 102 Pune

No Of Owner(s)
1st Owner
700 103 103 Pune

No Of Owner(s)
1st Owner
700 104 104 Pune

No Of Owner(s)
1st Owner
700 105 105 Pune

No Of Owner(s)
1st Owner
700 106 106 Pune

No Of Owner(s)
1st Owner
700 107 107 Pune

No Of Owner(s)
1st Owner
700 108 108 Pune

No Of Owner(s)
2nd Owner
700 109 109 Pune

No Of Owner(s)
2nd Owner
700 110 110 Pune

No Of Owner(s)
1st Owner
700 111 111 Pune

No Of Owner(s)
2nd Owner
700 112 112 Pune

No Of Owner(s)
1st Owner
700 113 113 Pune

No Of Owner(s)
1st Owner
700 114 114 Pune

No Of Owner(s)
1st Owner
700 115 115 Pune

No Of Owner(s)
1st Owner
700 116 116 Pune

No Of Owner(s)
1st Owner
700 117 117 Pune

No Of Owner(s)
1st Owner
700 118 118 Pune

No Of Owner(s)
2nd Owner
700 119 119 Pune

No Of Owner(s)
1st Owner
700 120 120 Pune

No Of Owner(s)
1st Owner
700 121 121 Pune

No Of Owner(s)
1st Owner
700 122 122 Pune

No Of Owner(s)
1st Owner
700 123 123 Pune

No Of Owner(s)
1st Owner
700 124 124 Pune

First Owner
700 125 125 Pune

First Owner
700 126 126 Pune

First Owner
700 127 127 Pune

First Owner
700 128 128 Pune

First Owner
700 129 129 Pune

Second Owner
700 130 130 Pune

Second Owner
700 131 131 Pune

Second Owner
700 132 132 Pune

First Owner
700 133 133 Pune

First Owner
700 134 134 Pune

First Owner
700 135 135 Pune

Second Owner
700 136 136 Pune

First Owner
700 137 137 Pune

Third Owner
700 138 138 Pune

First Owner
700 139 139 Pune

Second Owner
700 140 140 Pune

First Owner
700 141 141 Pune

First Owner
700 142 142 Pune

First Owner
700 143 143 Pune

First Owner
700 144 144 Pune

Second Owner
700 145 145 Pune

First Owner
700 146 146 Pune

First Owner
700 147 147 Pune

First Owner
700 148 148 Pune

First Owner
700 149 149 Pune

Second Owner
700 150 150 Pune

First Owner
700 151 151 Pune

First Owner
700 152 152 Pune

Second Owner
700 153 153 Pune

First Owner
700 154 154 Pune

First Owner
700 155 155 Pune

First Owner
700 156 156 Pune

First Owner
700 157 157 Pune

Second Owner
700 158 158 Pune

First Owner
700 159 159 Pune

First Owner
700 160 160 Pune

First Owner
700 161 161 Pune

First Owner
700 162 162 Pune

First Owner
700 163 163 Pune

First Owner
700 164 164 Pune

First Owner
700 165 165 Pune

First Owner
700 166 166 Pune

First Owner
700 167 167 Pune

Second Owner
700 168 168 Pune

First Owner
700 169 169 Pune

First Owner
700 170 170 Pune

First Owner

IndexError: list index out of range

In [496]:
 for url in urls[365:]:
            driver.get(url)
            for _ in range(50):
                driver.execute_script("window.scrollBy(0,20)")
            try:
                price_ele=driver.find_element_by_xpath('//span[@class="amount"]')
                pr=float(price_ele.text[:-6])
                price.append(int(pr*100000))
                    
                model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1[2]')
                model.append(model_ele.text)
                    
                str=model_ele.text
                for k in range(len(str)):
                    if str[k]==' ':
                        x=k
                        break
                brand.append(str[:x])
                
                info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6"]')
                make_year.append(info_ele[0].text)
                km.append(info_ele[2].text[:-4])
                
                owner.append(info_ele[3].text)
                print(info_ele[3].text)
                fuel.append(info_ele[4].text)
                transmission.append(info_ele[5].text)
                mileage.append(info_ele[8].text[8:-5])
                
                if len(info_ele)>8:
                    engine.append(info_ele[9].text[7:-3])
                    
                    if len(info_ele)>=10:
                        max_power.append(info_ele[10].text)
                        torque.append(info_ele[11].text)
                    else:
                        max_power.append(None)
                        torque.append(None)
                    
                else:
                    engine.append(None)
                    max_power.append(None)
                    torque.append(None)
                    
            except NoSuchElementException:
                try:
                    price_ele=driver.find_element_by_xpath('//div[@class="priceSection"]//span[2]')
                    str=price_ele.text
                    price.append(str.replace(',',''))
                
                    model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1')
                    model.append(model_ele.text[5:])
                
                    str=model_ele.text[5:]
                    for k in range(len(str)):
                        if str[k]==' ':
                            x=k
                            break
                    brand.append(str[:x])
                    
                    info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6 gsc_col-md-4"]')
                    make_year.append(info_ele[0].text[10:])
                    fuel.append(info_ele[2].text[5:])
                    km.append(info_ele[3].text[11:-4])
                    engine.append(info_ele[4].text[20:-3])
                    owner.append(info_ele[5].text)
                    print(info_ele[5].text)
                
                    if len(info_ele)>=12:
                        transmission.append(info_ele[7].text[13:])
                        mileage.append(info_ele[9].text[8:-5])
                        max_power.append(info_ele[11].text)
                        torque.append(info_ele[12].text)
                    else:
                        transmission.append(None)
                        mileage.append(None)
                        max_power.append(None)
                        torque.append(None)
                except NoSuchElementException:
                    continue
    
            try:
                var_ele=driver.find_element_by_xpath('//div[@class="variant-name"]')
                variant.append(var_ele.text)
        
            except NoSuchElementException:
                variant.append(None)
   
            body_type.append(b_type)
            location.append(city[i])
            if len(owner)<len(model):
                owner.append(None)
            print(len(urls),len(owner),len(location),city[11],'\n')

First Owner
700 359 359 Pune

First Owner
700 360 360 Pune

First Owner
700 361 361 Pune

First Owner
700 362 362 Pune

Second Owner
700 363 363 Pune

First Owner
700 364 364 Pune

First Owner
700 365 365 Pune

Second Owner
700 366 366 Pune

Second Owner
700 367 367 Pune

First Owner
700 368 368 Pune

First Owner
700 369 369 Pune

First Owner
700 370 370 Pune

First Owner
700 371 371 Pune

First Owner
700 372 372 Pune

First Owner
700 373 373 Pune

First Owner
700 374 374 Pune

First Owner
700 375 375 Pune

Test Drive Car
700 376 376 Pune

Third Owner
700 377 377 Pune

First Owner
700 378 378 Pune

First Owner
700 379 379 Pune

First Owner
700 380 380 Pune

First Owner
700 381 381 Pune

First Owner
700 382 382 Pune

First Owner
700 383 383 Pune

First Owner
700 384 384 Pune

First Owner
700 385 385 Pune

First Owner
700 386 386 Pune

First Owner
700 387 387 Pune

First Owner
700 388 388 Pune

First Owner
700 389 389 Pune

First Owner
700 390 390 Pune

First Owner
700 391 391 Pune

First Owner

IndexError: list index out of range

In [498]:
owner=owner[:391]
brand=brand[:391]
model=model[:391]
variant=variant[:391]
make_year=make_year[:391]
fuel=fuel[:391]
km=km[:391]
engine=engine[:391]
transmission=transmission[:391]
mileage=mileage[:391]
max_power=max_power[:391]
torque=torque[:391]
body_type=body_type[:391]
price=price[:391]
location=location[:391]
print(len(urls),len(torque),len(location),city[11],'\n')

700 391 391 Pune

In [499]:
cardekho_11=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                  'Engine':(engine),
                  'Number_of_Owners':(owner),
                  'Transmission':(transmission),
                  'Milaege':(mileage),
                  'Max_Power':(max_power),
                  'Torque':(torque),
                   'Body_Type':(body_type),
                   'Location':(city[11]),
                  'Price':(price)})
cardekho_11

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Engine,Number_of_Owners,Transmission,Milaege,Max_Power,Torque,Body_Type,Location,Price
0,Hyundai,Hyundai i20,1.2 Magna,2011,Petrol,"68,398",1197,No Of Owner(s)\n2nd Owner,Manual,18.5,Max Power\n80 PS at 5200 rpm,"Torque\n11.4 kgm at 4,000 rpm",Hatchback,Pune,308000
1,Hyundai,Hyundai Grand i10,Asta Option,2014,Petrol,"82,087",1197,No Of Owner(s)\n2nd Owner,Manual,18.9,Max Power\n82bhp,Torque\n114Nm,Hatchback,Pune,375000
2,Maruti,Maruti Swift,ZDi,2012,Diesel,"110,912",1248,No Of Owner(s)\n1st Owner,Manual,22.9,Max Power\n74bhp,Torque\n190Nm,Hatchback,Pune,438500
3,Hyundai,Hyundai i20,1.4 CRDi Anniversary Edition,2015,Diesel,"119,350",1396,No Of Owner(s)\n1st Owner,Manual,22.54,Max Power\n88.73bhp,Torque\n219.7Nm,Hatchback,Pune,561000
4,Hyundai,Hyundai Grand i10,CRDi Asta Option,2015,Diesel,"50,429",1120,No Of Owner(s)\n1st Owner,Manual,24,Max Power\n70bhp,Torque\n160Nm,Hatchback,Pune,502000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386,Fiat,Fiat Punto EVO 1.2 Dynamic,None,2018,Petrol,"19,836",1172,First Owner,Manual,15.8,Max Power\n67.1 bhp,Torque\n96Nm@ 2500rpm,Hatchback,Pune,375000
387,Hyundai,Hyundai i10 Magna,None,2010,Petrol,"96,418",1197,First Owner,Manual,20.36,Max Power\n78.9 bhp,Torque\n111.7Nm@ 4000rpm,Hatchback,Pune,295000
388,Maruti,Maruti Ritz VXI,None,2010,Petrol,"45,000",1197,First Owner,Manual,21.1,Max Power\n85.80 bhp,Torque\n114Nm@ 4000rpm,Hatchback,Pune,270000
389,Hyundai,Hyundai i10 Magna 1.2,None,2010,Petrol,"47,000",1197,First Owner,Manual,20.36,Max Power\n78.9 bhp,Torque\n111.7Nm@ 4000rpm,Hatchback,Pune,235000
390,Maruti,Maruti S-Cross 2017-2020 Zeta DDiS 200 SH,None,2018,Diesel,"72,000",1248,First Owner,Manual,25.1,Max Power\n88.5 bhp,Torque\n200Nm@ 1750rpm,Hatchback,Pune,894999

In [500]:
cardekho_11['Source']='CarDekho'

In [501]:
cardekho_11.to_csv('cardekho_11.csv')

In [504]:
model=[]
brand=[]
variant=[]
price=[]
make_year=[]
reg_year=[]
fuel=[]
km=[]
engine=[]
owner=[]
transmission=[]
mileage=[]
max_power=[]
torque=[]
body_type=[]
location=[]

In [505]:
#city 10
for i in range(1):
    for j in range(0,6):
        driver.get(city_url[10])
        for _ in range(100):
            driver.execute_script("window.scrollBy(0,20)")
        body_type_ele=driver.find_elements_by_xpath('//ul[@class="checkBoxWrap bodyTypes cd-bodyTicon"]//li')
        b_type=body_type_ele[j].text
        try:
            driver.implicitly_wait(10)
            ActionChains(driver).move_to_element(body_type_ele[j]).click(body_type_ele[j]).perform()
            
        except ElementNotInteractableException:
            continue
        
        except StaleElementReferenceException:
            continue

        for _ in range(2000):
            driver.execute_script("window.scrollBy(0,20)")

        urls=[]
        url_ele=driver.find_elements_by_xpath('//div[@class="gsc_col-xs-7 carsName"]//a')
        for ele in url_ele:
            try:
                urls.append(ele.get_attribute('href'))
            except StaleElementReferenceException:
                continue
    
        for url in urls:
            driver.get(url)
            for _ in range(50):
                driver.execute_script("window.scrollBy(0,20)")
            try:
                price_ele=driver.find_element_by_xpath('//span[@class="amount"]')
                pr=float(price_ele.text[:-6])
                price.append(int(pr*100000))
                    
                model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1[2]')
                model.append(model_ele.text)
                    
                str=model_ele.text
                for k in range(len(str)):
                    if str[k]==' ':
                        x=k
                        break
                brand.append(str[:x])
                
                info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6"]')
                make_year.append(info_ele[0].text)
                km.append(info_ele[2].text[:-4])
                
                owner.append(info_ele[3].text)
                print(info_ele[3].text)
                fuel.append(info_ele[4].text)
                transmission.append(info_ele[5].text)
                mileage.append(info_ele[8].text[8:-5])
                
                if len(info_ele)>8:
                    engine.append(info_ele[9].text[7:-3])
                    
                    if len(info_ele)>=10:
                        max_power.append(info_ele[10].text)
                        torque.append(info_ele[11].text)
                    else:
                        max_power.append(None)
                        torque.append(None)
                    
                else:
                    engine.append(None)
                    max_power.append(None)
                    torque.append(None)
                    
            except NoSuchElementException:
                try:
                    price_ele=driver.find_element_by_xpath('//div[@class="priceSection"]//span[2]')
                    str=price_ele.text
                    price.append(str.replace(',',''))
                
                    model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1')
                    model.append(model_ele.text[5:])
                
                    str=model_ele.text[5:]
                    for k in range(len(str)):
                        if str[k]==' ':
                            x=k
                            break
                    brand.append(str[:x])
                    
                    info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6 gsc_col-md-4"]')
                    make_year.append(info_ele[0].text[10:])
                    fuel.append(info_ele[2].text[5:])
                    km.append(info_ele[3].text[11:-4])
                    engine.append(info_ele[4].text[20:-3])
                    owner.append(info_ele[5].text)
                    print(info_ele[5].text)
                
                    if len(info_ele)>=12:
                        transmission.append(info_ele[7].text[13:])
                        mileage.append(info_ele[9].text[8:-5])
                        max_power.append(info_ele[11].text)
                        torque.append(info_ele[12].text)
                    else:
                        transmission.append(None)
                        mileage.append(None)
                        max_power.append(None)
                        torque.append(None)
                except NoSuchElementException:
                    continue
    
            try:
                var_ele=driver.find_element_by_xpath('//div[@class="variant-name"]')
                variant.append(var_ele.text)
        
            except NoSuchElementException:
                variant.append(None)
   
            body_type.append(b_type)
            location.append(city[10])
            if len(owner)<len(model):
                owner.append(None)
            print(len(model),len(owner),len(location),city[10],'\n')

No Of Owner(s)
1st Owner
1 1 1 Noida

No Of Owner(s)
1st Owner
2 2 2 Noida

No Of Owner(s)
1st Owner
3 3 3 Noida

No Of Owner(s)
2nd Owner
4 4 4 Noida

No Of Owner(s)
1st Owner
5 5 5 Noida

No Of Owner(s)
1st Owner
6 6 6 Noida

No Of Owner(s)
1st Owner
7 7 7 Noida

No Of Owner(s)
1st Owner
8 8 8 Noida

No Of Owner(s)
1st Owner
9 9 9 Noida

No Of Owner(s)
1st Owner
10 10 10 Noida

No Of Owner(s)
1st Owner
11 11 11 Noida

No Of Owner(s)
1st Owner
12 12 12 Noida

No Of Owner(s)
1st Owner
13 13 13 Noida

No Of Owner(s)
1st Owner
14 14 14 Noida

No Of Owner(s)
2nd Owner
15 15 15 Noida

No Of Owner(s)
1st Owner
16 16 16 Noida

No Of Owner(s)
1st Owner
17 17 17 Noida

No Of Owner(s)
1st Owner
18 18 18 Noida

No Of Owner(s)
3rd Owner
19 19 19 Noida

No Of Owner(s)
2nd Owner
20 20 20 Noida

No Of Owner(s)
1st Owner
21 21 21 Noida

No Of Owner(s)
1st Owner
22 22 22 Noida

No Of Owner(s)
1st Owner
23 23 23 Noida

No Of Owner(s)
1st Owner
24 24 24 Noida

No Of Owner(s)
1st Owner
25 25 25 Noida

No Of Owner(s)
1st Owner
26 26 26 Noida

No Of Owner(s)
1st Owner
27 27 27 Noida

No Of Owner(s)
1st Owner
28 28 28 Noida

No Of Owner(s)
1st Owner
29 29 29 Noida

No Of Owner(s)
2nd Owner
30 30 30 Noida

No Of Owner(s)
1st Owner
31 31 31 Noida

No Of Owner(s)
1st Owner
32 32 32 Noida

No Of Owner(s)
1st Owner
33 33 33 Noida

No Of Owner(s)
1st Owner
34 34 34 Noida

No Of Owner(s)
1st Owner
35 35 35 Noida

No Of Owner(s)
1st Owner
36 36 36 Noida

No Of Owner(s)
1st Owner
37 37 37 Noida

No Of Owner(s)
1st Owner
38 38 38 Noida

No Of Owner(s)
1st Owner
39 39 39 Noida

No Of Owner(s)
1st Owner
40 40 40 Noida

No Of Owner(s)
1st Owner
41 41 41 Noida

No Of Owner(s)
1st Owner
42 42 42 Noida

No Of Owner(s)
1st Owner
43 43 43 Noida

No Of Owner(s)
1st Owner
44 44 44 Noida

No Of Owner(s)
1st Owner
45 45 45 Noida

No Of Owner(s)
1st Owner
46 46 46 Noida

No Of Owner(s)
1st Owner
47 47 47 Noida

No Of Owner(s)
1st Owner
48 48 48 Noida

No Of Owner(s)
1st Owner
49 49 49 Noida

No Of Owner(s)
1st Owner
50 50 50 Noida

No Of Owner(s)
1st Owner
51 51 51 Noida

No Of Owner(s)
1st Owner
52 52 52 Noida

No Of Owner(s)
1st Owner
53 53 53 Noida

No Of Owner(s)
1st Owner
54 54 54 Noida

No Of Owner(s)
1st Owner
55 55 55 Noida

No Of Owner(s)
1st Owner
56 56 56 Noida

No Of Owner(s)
1st Owner
57 57 57 Noida

No Of Owner(s)
1st Owner
58 58 58 Noida

No Of Owner(s)
1st Owner
59 59 59 Noida

No Of Owner(s)
1st Owner
60 60 60 Noida

No Of Owner(s)
1st Owner
61 61 61 Noida

No Of Owner(s)
1st Owner
62 62 62 Noida

No Of Owner(s)
1st Owner
63 63 63 Noida

No Of Owner(s)
1st Owner
64 64 64 Noida

No Of Owner(s)
1st Owner
65 65 65 Noida

No Of Owner(s)
2nd Owner
66 66 66 Noida

No Of Owner(s)
1st Owner
67 67 67 Noida

No Of Owner(s)
1st Owner
68 68 68 Noida

No Of Owner(s)
1st Owner
69 69 69 Noida

No Of Owner(s)
1st Owner
70 70 70 Noida

No Of Owner(s)
1st Owner
71 71 71 Noida

No Of Owner(s)
1st Owner
72 72 72 Noida

No Of Owner(s)
1st Owner
73 73 73 Noida

No Of Owner(s)
1st Owner
74 74 74 Noida

No Of Owner(s)
2nd Owner
75 75 75 Noida

No Of Owner(s)
1st Owner
76 76 76 Noida

No Of Owner(s)
1st Owner
77 77 77 Noida

No Of Owner(s)
1st Owner
78 78 78 Noida

No Of Owner(s)
1st Owner
79 79 79 Noida

No Of Owner(s)
1st Owner
80 80 80 Noida

No Of Owner(s)
2nd Owner
81 81 81 Noida

No Of Owner(s)
1st Owner
82 82 82 Noida

No Of Owner(s)
1st Owner
83 83 83 Noida

No Of Owner(s)
1st Owner
84 84 84 Noida

No Of Owner(s)
1st Owner
85 85 85 Noida

No Of Owner(s)
1st Owner
86 86 86 Noida

No Of Owner(s)
1st Owner
87 87 87 Noida

No Of Owner(s)
1st Owner
88 88 88 Noida

No Of Owner(s)
1st Owner
89 89 89 Noida

No Of Owner(s)
1st Owner
90 90 90 Noida

No Of Owner(s)
1st Owner
91 91 91 Noida

No Of Owner(s)
1st Owner
92 92 92 Noida

No Of Owner(s)
1st Owner
93 93 93 Noida

No Of Owner(s)
1st Owner
94 94 94 Noida

No Of Owner(s)
1st Owner
95 95 95 Noida

No Of Owner(s)
1st Owner
96 96 96 Noida

No Of Owner(s)
1st Owner
97 97 97 Noida

No Of Owner(s)
1st Owner
98 98 98 Noida

No Of Owner(s)
1st Owner
99 99 99 Noida

No Of Owner(s)
1st Owner
100 100 100 Noida

No Of Owner(s)
2nd Owner
101 101 101 Noida

No Of Owner(s)
1st Owner
102 102 102 Noida

No Of Owner(s)
1st Owner
103 103 103 Noida

No Of Owner(s)
1st Owner
104 104 104 Noida

No Of Owner(s)
1st Owner
105 105 105 Noida

No Of Owner(s)
1st Owner
106 106 106 Noida

No Of Owner(s)
2nd Owner
107 107 107 Noida

No Of Owner(s)
1st Owner
108 108 108 Noida

No Of Owner(s)
1st Owner
109 109 109 Noida

No Of Owner(s)
1st Owner
110 110 110 Noida

No Of Owner(s)
1st Owner
111 111 111 Noida

No Of Owner(s)
1st Owner
112 112 112 Noida

No Of Owner(s)
1st Owner
113 113 113 Noida

No Of Owner(s)
1st Owner
114 114 114 Noida

No Of Owner(s)
1st Owner
115 115 115 Noida

No Of Owner(s)
1st Owner
116 116 116 Noida

No Of Owner(s)
1st Owner
117 117 117 Noida

No Of Owner(s)
1st Owner
118 118 118 Noida

No Of Owner(s)
1st Owner
119 119 119 Noida

No Of Owner(s)
2nd Owner
120 120 120 Noida

No Of Owner(s)
1st Owner
121 121 121 Noida

No Of Owner(s)
1st Owner
122 122 122 Noida

No Of Owner(s)
1st Owner
123 123 123 Noida

No Of Owner(s)
1st Owner
124 124 124 Noida

No Of Owner(s)
1st Owner
125 125 125 Noida

No Of Owner(s)
1st Owner
126 126 126 Noida

No Of Owner(s)
1st Owner
127 127 127 Noida

No Of Owner(s)
1st Owner
128 128 128 Noida

No Of Owner(s)
1st Owner
129 129 129 Noida

No Of Owner(s)
1st Owner
130 130 130 Noida

No Of Owner(s)
1st Owner
131 131 131 Noida

No Of Owner(s)
1st Owner
132 132 132 Noida

No Of Owner(s)
1st Owner
133 133 133 Noida

No Of Owner(s)
1st Owner
134 134 134 Noida

No Of Owner(s)
1st Owner
135 135 135 Noida

No Of Owner(s)
2nd Owner
136 136 136 Noida

No Of Owner(s)
1st Owner
137 137 137 Noida

No Of Owner(s)
1st Owner
138 138 138 Noida

No Of Owner(s)
1st Owner
139 139 139 Noida

No Of Owner(s)
1st Owner
140 140 140 Noida

No Of Owner(s)
1st Owner
141 141 141 Noida

No Of Owner(s)
1st Owner
142 142 142 Noida

No Of Owner(s)
2nd Owner
143 143 143 Noida

No Of Owner(s)
1st Owner
144 144 144 Noida

No Of Owner(s)
1st Owner
145 145 145 Noida

No Of Owner(s)
4th Owner
146 146 146 Noida

No Of Owner(s)
1st Owner
147 147 147 Noida

No Of Owner(s)
1st Owner
148 148 148 Noida

No Of Owner(s)
1st Owner
149 149 149 Noida

No Of Owner(s)
1st Owner
150 150 150 Noida

No Of Owner(s)
1st Owner
151 151 151 Noida

No Of Owner(s)
1st Owner
152 152 152 Noida

No Of Owner(s)
1st Owner
153 153 153 Noida

No Of Owner(s)
1st Owner
154 154 154 Noida

No Of Owner(s)
1st Owner
155 155 155 Noida

No Of Owner(s)
1st Owner
156 156 156 Noida

No Of Owner(s)
1st Owner
157 157 157 Noida

No Of Owner(s)
2nd Owner
158 158 158 Noida

No Of Owner(s)
1st Owner
159 159 159 Noida

No Of Owner(s)
1st Owner
160 160 160 Noida

No Of Owner(s)
1st Owner
161 161 161 Noida

No Of Owner(s)
1st Owner
162 162 162 Noida

No Of Owner(s)
1st Owner
163 163 163 Noida

No Of Owner(s)
1st Owner
164 164 164 Noida

No Of Owner(s)
1st Owner
165 165 165 Noida

No Of Owner(s)
1st Owner
166 166 166 Noida

No Of Owner(s)
1st Owner
167 167 167 Noida

No Of Owner(s)
1st Owner
168 168 168 Noida

No Of Owner(s)
1st Owner
169 169 169 Noida

No Of Owner(s)
1st Owner
170 170 170 Noida

No Of Owner(s)
1st Owner
171 171 171 Noida

No Of Owner(s)
1st Owner
172 172 172 Noida

No Of Owner(s)
1st Owner
173 173 173 Noida

No Of Owner(s)
1st Owner
174 174 174 Noida

No Of Owner(s)
1st Owner
175 175 175 Noida

No Of Owner(s)
1st Owner
176 176 176 Noida

No Of Owner(s)
1st Owner
177 177 177 Noida

No Of Owner(s)
1st Owner
178 178 178 Noida

No Of Owner(s)
1st Owner
179 179 179 Noida

No Of Owner(s)
1st Owner
180 180 180 Noida

No Of Owner(s)
1st Owner
181 181 181 Noida

No Of Owner(s)
1st Owner
182 182 182 Noida

No Of Owner(s)
1st Owner
183 183 183 Noida

No Of Owner(s)
1st Owner
184 184 184 Noida

No Of Owner(s)
1st Owner
185 185 185 Noida

No Of Owner(s)
1st Owner
186 186 186 Noida

No Of Owner(s)
1st Owner
187 187 187 Noida

No Of Owner(s)
1st Owner
188 188 188 Noida

No Of Owner(s)
1st Owner
189 189 189 Noida

No Of Owner(s)
1st Owner
190 190 190 Noida

No Of Owner(s)
1st Owner
191 191 191 Noida

No Of Owner(s)
1st Owner
192 192 192 Noida

No Of Owner(s)
1st Owner
193 193 193 Noida

No Of Owner(s)
1st Owner
194 194 194 Noida

No Of Owner(s)
2nd Owner
195 195 195 Noida

No Of Owner(s)
1st Owner
196 196 196 Noida

No Of Owner(s)
1st Owner
197 197 197 Noida

No Of Owner(s)
1st Owner
198 198 198 Noida

No Of Owner(s)
1st Owner
199 199 199 Noida

No Of Owner(s)
1st Owner
200 200 200 Noida

No Of Owner(s)
1st Owner
201 201 201 Noida

No Of Owner(s)
1st Owner
202 202 202 Noida

No Of Owner(s)
1st Owner
203 203 203 Noida

No Of Owner(s)
1st Owner
204 204 204 Noida

No Of Owner(s)
1st Owner
205 205 205 Noida

No Of Owner(s)
2nd Owner
206 206 206 Noida

No Of Owner(s)
1st Owner
207 207 207 Noida

No Of Owner(s)
2nd Owner
208 208 208 Noida

No Of Owner(s)
1st Owner
209 209 209 Noida

No Of Owner(s)
1st Owner
210 210 210 Noida

No Of Owner(s)
1st Owner
211 211 211 Noida

No Of Owner(s)
1st Owner
212 212 212 Noida

No Of Owner(s)
1st Owner
213 213 213 Noida

No Of Owner(s)
1st Owner
214 214 214 Noida

No Of Owner(s)
1st Owner
215 215 215 Noida

No Of Owner(s)
1st Owner
216 216 216 Noida

No Of Owner(s)
1st Owner
217 217 217 Noida

No Of Owner(s)
1st Owner
218 218 218 Noida

No Of Owner(s)
1st Owner
219 219 219 Noida

No Of Owner(s)
1st Owner
220 220 220 Noida

No Of Owner(s)
2nd Owner
221 221 221 Noida

No Of Owner(s)
1st Owner
222 222 222 Noida

No Of Owner(s)
1st Owner
223 223 223 Noida

No Of Owner(s)
1st Owner
224 224 224 Noida

No Of Owner(s)
1st Owner
225 225 225 Noida

No Of Owner(s)
1st Owner
226 226 226 Noida

No Of Owner(s)
1st Owner
227 227 227 Noida

No Of Owner(s)
2nd Owner
228 228 228 Noida

No Of Owner(s)
1st Owner
229 229 229 Noida

No Of Owner(s)
1st Owner
230 230 230 Noida

No Of Owner(s)
1st Owner
231 231 231 Noida

No Of Owner(s)
1st Owner
232 232 232 Noida

No Of Owner(s)
1st Owner
233 233 233 Noida

No Of Owner(s)
1st Owner
234 234 234 Noida

No Of Owner(s)
1st Owner
235 235 235 Noida

No Of Owner(s)
2nd Owner
236 236 236 Noida

No Of Owner(s)
1st Owner
237 237 237 Noida

No Of Owner(s)
2nd Owner
238 238 238 Noida

No Of Owner(s)
1st Owner
239 239 239 Noida

No Of Owner(s)
1st Owner
240 240 240 Noida

No Of Owner(s)
1st Owner
241 241 241 Noida

No Of Owner(s)
1st Owner
242 242 242 Noida

No Of Owner(s)
1st Owner
243 243 243 Noida

No Of Owner(s)
1st Owner
244 244 244 Noida

No Of Owner(s)
1st Owner
245 245 245 Noida

No Of Owner(s)
1st Owner
246 246 246 Noida

No Of Owner(s)
1st Owner
247 247 247 Noida

No Of Owner(s)
1st Owner
248 248 248 Noida

No Of Owner(s)
1st Owner
249 249 249 Noida

No Of Owner(s)
1st Owner
250 250 250 Noida

No Of Owner(s)
2nd Owner
251 251 251 Noida

No Of Owner(s)
1st Owner
252 252 252 Noida

No Of Owner(s)
1st Owner
253 253 253 Noida

No Of Owner(s)
1st Owner
254 254 254 Noida

No Of Owner(s)
1st Owner
255 255 255 Noida

No Of Owner(s)
1st Owner
256 256 256 Noida

No Of Owner(s)
1st Owner
257 257 257 Noida

No Of Owner(s)
1st Owner
258 258 258 Noida

No Of Owner(s)
1st Owner
259 259 259 Noida

No Of Owner(s)
1st Owner
260 260 260 Noida

No Of Owner(s)
2nd Owner
261 261 261 Noida

No Of Owner(s)
1st Owner
262 262 262 Noida

No Of Owner(s)
1st Owner
263 263 263 Noida

No Of Owner(s)
1st Owner
264 264 264 Noida

No Of Owner(s)
1st Owner
265 265 265 Noida

No Of Owner(s)
1st Owner
266 266 266 Noida

No Of Owner(s)
1st Owner
267 267 267 Noida

No Of Owner(s)
1st Owner
268 268 268 Noida

No Of Owner(s)
1st Owner
269 269 269 Noida

No Of Owner(s)
2nd Owner
270 270 270 Noida

No Of Owner(s)
1st Owner
271 271 271 Noida

No Of Owner(s)
1st Owner
272 272 272 Noida

No Of Owner(s)
1st Owner
273 273 273 Noida

No Of Owner(s)
1st Owner
274 274 274 Noida

No Of Owner(s)
1st Owner
275 275 275 Noida

No Of Owner(s)
1st Owner
276 276 276 Noida

No Of Owner(s)
1st Owner
277 277 277 Noida

No Of Owner(s)
1st Owner
278 278 278 Noida

No Of Owner(s)
1st Owner
279 279 279 Noida

No Of Owner(s)
1st Owner
280 280 280 Noida

No Of Owner(s)
1st Owner
281 281 281 Noida

No Of Owner(s)
1st Owner
282 282 282 Noida

No Of Owner(s)
1st Owner
283 283 283 Noida

No Of Owner(s)
2nd Owner
284 284 284 Noida

No Of Owner(s)
2nd Owner
285 285 285 Noida

No Of Owner(s)
2nd Owner
286 286 286 Noida

No Of Owner(s)
1st Owner
287 287 287 Noida

No Of Owner(s)
1st Owner
288 288 288 Noida

No Of Owner(s)
1st Owner
289 289 289 Noida

No Of Owner(s)
1st Owner
290 290 290 Noida

No Of Owner(s)
1st Owner
291 291 291 Noida

No Of Owner(s)
1st Owner
292 292 292 Noida

No Of Owner(s)
1st Owner
293 293 293 Noida

No Of Owner(s)
1st Owner
294 294 294 Noida

No Of Owner(s)
1st Owner
295 295 295 Noida

No Of Owner(s)
1st Owner
296 296 296 Noida

No Of Owner(s)
1st Owner
297 297 297 Noida

No Of Owner(s)
1st Owner
298 298 298 Noida

No Of Owner(s)
1st Owner
299 299 299 Noida

No Of Owner(s)
1st Owner
300 300 300 Noida

No Of Owner(s)
1st Owner
301 301 301 Noida

No Of Owner(s)
1st Owner
302 302 302 Noida

No Of Owner(s)
1st Owner
303 303 303 Noida

No Of Owner(s)
2nd Owner
304 304 304 Noida

No Of Owner(s)
1st Owner
305 305 305 Noida

No Of Owner(s)
1st Owner
306 306 306 Noida

No Of Owner(s)
1st Owner
307 307 307 Noida

No Of Owner(s)
1st Owner
308 308 308 Noida

No Of Owner(s)
1st Owner
309 309 309 Noida

No Of Owner(s)
2nd Owner
310 310 310 Noida

No Of Owner(s)
2nd Owner
311 311 311 Noida

No Of Owner(s)
2nd Owner
312 312 312 Noida

No Of Owner(s)
1st Owner
313 313 313 Noida

No Of Owner(s)
1st Owner
314 314 314 Noida

No Of Owner(s)
2nd Owner
315 315 315 Noida

No Of Owner(s)
1st Owner
316 316 316 Noida

No Of Owner(s)
2nd Owner
317 317 317 Noida

No Of Owner(s)
2nd Owner
318 318 318 Noida

No Of Owner(s)
1st Owner
319 319 319 Noida

No Of Owner(s)
1st Owner
320 320 320 Noida

No Of Owner(s)
2nd Owner
321 321 321 Noida

No Of Owner(s)
1st Owner
322 322 322 Noida

No Of Owner(s)
1st Owner
323 323 323 Noida

No Of Owner(s)
1st Owner
324 324 324 Noida

No Of Owner(s)
1st Owner
325 325 325 Noida

No Of Owner(s)
1st Owner
326 326 326 Noida

No Of Owner(s)
1st Owner
327 327 327 Noida

No Of Owner(s)
1st Owner
328 328 328 Noida

No Of Owner(s)
1st Owner
329 329 329 Noida

No Of Owner(s)
1st Owner
330 330 330 Noida

No Of Owner(s)
2nd Owner
331 331 331 Noida

No Of Owner(s)
1st Owner
332 332 332 Noida

No Of Owner(s)
1st Owner
333 333 333 Noida

No Of Owner(s)
2nd Owner
334 334 334 Noida

No Of Owner(s)
1st Owner
335 335 335 Noida

No Of Owner(s)
2nd Owner
336 336 336 Noida

No Of Owner(s)
2nd Owner
337 337 337 Noida

No Of Owner(s)
2nd Owner
338 338 338 Noida

No Of Owner(s)
1st Owner
339 339 339 Noida

No Of Owner(s)
2nd Owner
340 340 340 Noida

No Of Owner(s)
1st Owner
341 341 341 Noida

No Of Owner(s)
1st Owner
342 342 342 Noida

No Of Owner(s)
1st Owner
343 343 343 Noida

No Of Owner(s)
1st Owner
344 344 344 Noida

No Of Owner(s)
1st Owner
345 345 345 Noida

No Of Owner(s)
1st Owner
346 346 346 Noida

No Of Owner(s)
1st Owner
347 347 347 Noida

No Of Owner(s)
1st Owner
348 348 348 Noida

No Of Owner(s)
1st Owner
349 349 349 Noida

No Of Owner(s)
1st Owner
350 350 350 Noida

No Of Owner(s)
2nd Owner
351 351 351 Noida

No Of Owner(s)
2nd Owner
352 352 352 Noida

No Of Owner(s)
1st Owner
353 353 353 Noida

No Of Owner(s)
1st Owner
354 354 354 Noida

No Of Owner(s)
1st Owner
355 355 355 Noida

No Of Owner(s)
1st Owner
356 356 356 Noida

No Of Owner(s)
1st Owner
357 357 357 Noida

No Of Owner(s)
2nd Owner
358 358 358 Noida

No Of Owner(s)
1st Owner
359 359 359 Noida

No Of Owner(s)
1st Owner
360 360 360 Noida

No Of Owner(s)
1st Owner
361 361 361 Noida

No Of Owner(s)
1st Owner
362 362 362 Noida

No Of Owner(s)
2nd Owner
363 363 363 Noida

No Of Owner(s)
1st Owner
364 364 364 Noida

No Of Owner(s)
1st Owner
365 365 365 Noida

No Of Owner(s)
1st Owner
366 366 366 Noida

No Of Owner(s)
1st Owner
367 367 367 Noida

No Of Owner(s)
1st Owner
368 368 368 Noida

No Of Owner(s)
1st Owner
369 369 369 Noida

No Of Owner(s)
1st Owner
370 370 370 Noida

No Of Owner(s)
1st Owner
371 371 371 Noida

No Of Owner(s)
2nd Owner
372 372 372 Noida

No Of Owner(s)
1st Owner
373 373 373 Noida

No Of Owner(s)
2nd Owner
374 374 374 Noida

No Of Owner(s)
1st Owner
375 375 375 Noida

No Of Owner(s)
1st Owner
376 376 376 Noida

No Of Owner(s)
1st Owner
377 377 377 Noida

No Of Owner(s)
1st Owner
378 378 378 Noida

No Of Owner(s)
1st Owner
379 379 379 Noida

No Of Owner(s)
1st Owner
380 380 380 Noida

No Of Owner(s)
1st Owner
381 381 381 Noida

No Of Owner(s)
2nd Owner
382 382 382 Noida

No Of Owner(s)
1st Owner
383 383 383 Noida

No Of Owner(s)
1st Owner
384 384 384 Noida

No Of Owner(s)
1st Owner
385 385 385 Noida

No Of Owner(s)
1st Owner
386 386 386 Noida

No Of Owner(s)
1st Owner
387 387 387 Noida

No Of Owner(s)
1st Owner
388 388 388 Noida

No Of Owner(s)
1st Owner
389 389 389 Noida

No Of Owner(s)
1st Owner
390 390 390 Noida

No Of Owner(s)
1st Owner
391 391 391 Noida

No Of Owner(s)
1st Owner
392 392 392 Noida

No Of Owner(s)
1st Owner
393 393 393 Noida

No Of Owner(s)
1st Owner
394 394 394 Noida

No Of Owner(s)
1st Owner
395 395 395 Noida

No Of Owner(s)
1st Owner
396 396 396 Noida

No Of Owner(s)
1st Owner
397 397 397 Noida

No Of Owner(s)
2nd Owner
398 398 398 Noida

No Of Owner(s)
1st Owner
399 399 399 Noida

No Of Owner(s)
1st Owner
400 400 400 Noida

No Of Owner(s)
1st Owner
401 401 401 Noida

No Of Owner(s)
1st Owner
402 402 402 Noida

No Of Owner(s)
1st Owner
403 403 403 Noida

No Of Owner(s)
2nd Owner
404 404 404 Noida

No Of Owner(s)
1st Owner
405 405 405 Noida

No Of Owner(s)
1st Owner
406 406 406 Noida

No Of Owner(s)
1st Owner
407 407 407 Noida

No Of Owner(s)
1st Owner
408 408 408 Noida

No Of Owner(s)
1st Owner
409 409 409 Noida

No Of Owner(s)
1st Owner
410 410 410 Noida

No Of Owner(s)
2nd Owner
411 411 411 Noida

No Of Owner(s)
1st Owner
412 412 412 Noida

No Of Owner(s)
1st Owner
413 413 413 Noida

No Of Owner(s)
1st Owner
414 414 414 Noida

No Of Owner(s)
1st Owner
415 415 415 Noida

No Of Owner(s)
1st Owner
416 416 416 Noida

No Of Owner(s)
1st Owner
417 417 417 Noida

No Of Owner(s)
1st Owner
418 418 418 Noida

No Of Owner(s)
1st Owner
419 419 419 Noida

No Of Owner(s)
2nd Owner
420 420 420 Noida

No Of Owner(s)
1st Owner
421 421 421 Noida

No Of Owner(s)
1st Owner
422 422 422 Noida

No Of Owner(s)
1st Owner
423 423 423 Noida

No Of Owner(s)
1st Owner
424 424 424 Noida

No Of Owner(s)
2nd Owner
425 425 425 Noida

No Of Owner(s)
1st Owner
426 426 426 Noida

No Of Owner(s)
2nd Owner
427 427 427 Noida

No Of Owner(s)
1st Owner
428 428 428 Noida

No Of Owner(s)
1st Owner
429 429 429 Noida

No Of Owner(s)
1st Owner
430 430 430 Noida

No Of Owner(s)
1st Owner
431 431 431 Noida

No Of Owner(s)
1st Owner
432 432 432 Noida

No Of Owner(s)
1st Owner
433 433 433 Noida

No Of Owner(s)
1st Owner
434 434 434 Noida

No Of Owner(s)
1st Owner
435 435 435 Noida

No Of Owner(s)
2nd Owner
436 436 436 Noida

No Of Owner(s)
1st Owner
437 437 437 Noida

No Of Owner(s)
1st Owner
438 438 438 Noida

No Of Owner(s)
2nd Owner
439 439 439 Noida

No Of Owner(s)
1st Owner
440 440 440 Noida

No Of Owner(s)
1st Owner
441 441 441 Noida

No Of Owner(s)
1st Owner
442 442 442 Noida

No Of Owner(s)
1st Owner
443 443 443 Noida

No Of Owner(s)
1st Owner
444 444 444 Noida

No Of Owner(s)
1st Owner
445 445 445 Noida

No Of Owner(s)
1st Owner
446 446 446 Noida

No Of Owner(s)
1st Owner
447 447 447 Noida

No Of Owner(s)
1st Owner
448 448 448 Noida

No Of Owner(s)
1st Owner
449 449 449 Noida

No Of Owner(s)
1st Owner
450 450 450 Noida

No Of Owner(s)
1st Owner
451 451 451 Noida

No Of Owner(s)
1st Owner
452 452 452 Noida

No Of Owner(s)
1st Owner
453 453 453 Noida

No Of Owner(s)
2nd Owner
454 454 454 Noida

No Of Owner(s)
1st Owner
455 455 455 Noida

No Of Owner(s)
1st Owner
456 456 456 Noida

No Of Owner(s)
1st Owner
457 457 457 Noida

No Of Owner(s)
2nd Owner
458 458 458 Noida

No Of Owner(s)
1st Owner
459 459 459 Noida

No Of Owner(s)
2nd Owner
460 460 460 Noida

No Of Owner(s)
1st Owner
461 461 461 Noida

No Of Owner(s)
1st Owner
462 462 462 Noida

No Of Owner(s)
1st Owner
463 463 463 Noida

No Of Owner(s)
1st Owner
464 464 464 Noida

No Of Owner(s)
1st Owner
465 465 465 Noida

No Of Owner(s)
1st Owner
466 466 466 Noida

No Of Owner(s)
1st Owner
467 467 467 Noida

No Of Owner(s)
1st Owner
468 468 468 Noida

No Of Owner(s)
1st Owner
469 469 469 Noida

No Of Owner(s)
1st Owner
470 470 470 Noida

No Of Owner(s)
1st Owner
471 471 471 Noida

No Of Owner(s)
2nd Owner
472 472 472 Noida

No Of Owner(s)
1st Owner
473 473 473 Noida

No Of Owner(s)
1st Owner
474 474 474 Noida

No Of Owner(s)
1st Owner
475 475 475 Noida

No Of Owner(s)
1st Owner
476 476 476 Noida

No Of Owner(s)
1st Owner
477 477 477 Noida

No Of Owner(s)
1st Owner
478 478 478 Noida

No Of Owner(s)
1st Owner
479 479 479 Noida

No Of Owner(s)
1st Owner
480 480 480 Noida

No Of Owner(s)
1st Owner
481 481 481 Noida

No Of Owner(s)
1st Owner
482 482 482 Noida

No Of Owner(s)
1st Owner
483 483 483 Noida

No Of Owner(s)
1st Owner
484 484 484 Noida

No Of Owner(s)
1st Owner
485 485 485 Noida

No Of Owner(s)
2nd Owner
486 486 486 Noida

No Of Owner(s)
2nd Owner
487 487 487 Noida

No Of Owner(s)
1st Owner
488 488 488 Noida

No Of Owner(s)
1st Owner
489 489 489 Noida

No Of Owner(s)
2nd Owner
490 490 490 Noida

No Of Owner(s)
2nd Owner
491 491 491 Noida

No Of Owner(s)
2nd Owner
492 492 492 Noida

No Of Owner(s)
2nd Owner
493 493 493 Noida

First Owner
494 494 494 Noida

First Owner
495 495 495 Noida

First Owner
496 496 496 Noida

First Owner
497 497 497 Noida

First Owner
498 498 498 Noida

First Owner
499 499 499 Noida

First Owner
500 500 500 Noida

First Owner
501 501 501 Noida

First Owner
502 502 502 Noida

First Owner
503 503 503 Noida

First Owner
504 504 504 Noida

First Owner
505 505 505 Noida

Second Owner
506 506 506 Noida

Second Owner
507 507 507 Noida

First Owner
508 508 508 Noida

Second Owner
509 509 509 Noida

Second Owner
510 510 510 Noida

First Owner
511 511 511 Noida

Third Owner
512 512 512 Noida

First Owner
513 513 513 Noida

First Owner
514 514 514 Noida

First Owner
515 515 515 Noida

First Owner
516 516 516 Noida

First Owner
517 517 517 Noida

First Owner
518 518 518 Noida

First Owner
519 519 519 Noida

First Owner
520 520 520 Noida

Second Owner
521 521 521 Noida

Second Owner
522 522 522 Noida

First Owner
523 523 523 Noida

First Owner
524 524 524 Noida

First Owner
525 525 525 Noida

First Owner
526 526 526 Noida

First Owner
527 527 527 Noida

First Owner
528 528 528 Noida

First Owner
529 529 529 Noida

First Owner
530 530 530 Noida

First Owner
531 531 531 Noida

First Owner
532 532 532 Noida

First Owner
533 533 533 Noida

Third Owner
534 534 534 Noida

First Owner
535 535 535 Noida

First Owner
536 536 536 Noida

First Owner
537 537 537 Noida

First Owner
538 538 538 Noida

First Owner
539 539 539 Noida

First Owner
540 540 540 Noida

First Owner
541 541 541 Noida

Fourth & Above Owner
542 542 542 Noida

Second Owner
543 543 543 Noida

First Owner
544 544 544 Noida

First Owner
545 545 545 Noida

First Owner
546 546 546 Noida

Second Owner
547 547 547 Noida

Second Owner
548 548 548 Noida

First Owner
549 549 549 Noida

First Owner
550 550 550 Noida

First Owner
551 551 551 Noida

First Owner
552 552 552 Noida

No Of Owner(s)
1st Owner
553 553 553 Noida

No Of Owner(s)
1st Owner
554 554 554 Noida

No Of Owner(s)
1st Owner
555 555 555 Noida

No Of Owner(s)
1st Owner
556 556 556 Noida

No Of Owner(s)
1st Owner
557 557 557 Noida

No Of Owner(s)
1st Owner
558 558 558 Noida

No Of Owner(s)
1st Owner
559 559 559 Noida

No Of Owner(s)
1st Owner
560 560 560 Noida

No Of Owner(s)
1st Owner
561 561 561 Noida

No Of Owner(s)
1st Owner
562 562 562 Noida

No Of Owner(s)
1st Owner
563 563 563 Noida

No Of Owner(s)
2nd Owner
564 564 564 Noida

No Of Owner(s)
1st Owner
565 565 565 Noida

No Of Owner(s)
1st Owner
566 566 566 Noida

No Of Owner(s)
1st Owner
567 567 567 Noida

No Of Owner(s)
1st Owner
568 568 568 Noida

No Of Owner(s)
1st Owner
569 569 569 Noida

No Of Owner(s)
1st Owner
570 570 570 Noida

No Of Owner(s)
1st Owner
571 571 571 Noida

No Of Owner(s)
1st Owner
572 572 572 Noida

No Of Owner(s)
1st Owner
573 573 573 Noida

No Of Owner(s)
2nd Owner
574 574 574 Noida

No Of Owner(s)
2nd Owner
575 575 575 Noida

No Of Owner(s)
1st Owner
576 576 576 Noida

No Of Owner(s)
1st Owner
577 577 577 Noida

No Of Owner(s)
1st Owner
578 578 578 Noida

No Of Owner(s)
1st Owner
579 579 579 Noida

No Of Owner(s)
1st Owner
580 580 580 Noida

No Of Owner(s)
1st Owner
581 581 581 Noida

No Of Owner(s)
1st Owner
582 582 582 Noida

No Of Owner(s)
1st Owner
583 583 583 Noida

No Of Owner(s)
1st Owner
584 584 584 Noida

No Of Owner(s)
1st Owner
585 585 585 Noida

No Of Owner(s)
2nd Owner
586 586 586 Noida

No Of Owner(s)
1st Owner
587 587 587 Noida

No Of Owner(s)
1st Owner
588 588 588 Noida

No Of Owner(s)
1st Owner
589 589 589 Noida

No Of Owner(s)
1st Owner
590 590 590 Noida

No Of Owner(s)
1st Owner
591 591 591 Noida

No Of Owner(s)
1st Owner
592 592 592 Noida

No Of Owner(s)
2nd Owner
593 593 593 Noida

No Of Owner(s)
1st Owner
594 594 594 Noida

No Of Owner(s)
1st Owner
595 595 595 Noida

No Of Owner(s)
1st Owner
596 596 596 Noida

No Of Owner(s)
1st Owner
597 597 597 Noida

No Of Owner(s)
1st Owner
598 598 598 Noida

No Of Owner(s)
1st Owner
599 599 599 Noida

No Of Owner(s)
1st Owner
600 600 600 Noida

No Of Owner(s)
1st Owner
601 601 601 Noida

No Of Owner(s)
1st Owner
602 602 602 Noida

No Of Owner(s)
1st Owner
603 603 603 Noida

No Of Owner(s)
2nd Owner
604 604 604 Noida

No Of Owner(s)
2nd Owner
605 605 605 Noida

No Of Owner(s)
2nd Owner
606 606 606 Noida

No Of Owner(s)
1st Owner
607 607 607 Noida

No Of Owner(s)
2nd Owner
608 608 608 Noida

No Of Owner(s)
1st Owner
609 609 609 Noida

No Of Owner(s)
1st Owner
610 610 610 Noida

No Of Owner(s)
1st Owner
611 611 611 Noida

No Of Owner(s)
1st Owner
612 612 612 Noida

No Of Owner(s)
2nd Owner
613 613 613 Noida

No Of Owner(s)
1st Owner
614 614 614 Noida

No Of Owner(s)
1st Owner
615 615 615 Noida

No Of Owner(s)
1st Owner
616 616 616 Noida

No Of Owner(s)
1st Owner
617 617 617 Noida

No Of Owner(s)
2nd Owner
618 618 618 Noida

No Of Owner(s)
1st Owner
619 619 619 Noida

No Of Owner(s)
2nd Owner
620 620 620 Noida

No Of Owner(s)
1st Owner
621 621 621 Noida

No Of Owner(s)
1st Owner
622 622 622 Noida

No Of Owner(s)
1st Owner
623 623 623 Noida

No Of Owner(s)
1st Owner
624 624 624 Noida

No Of Owner(s)
1st Owner
625 625 625 Noida

No Of Owner(s)
1st Owner
626 626 626 Noida

No Of Owner(s)
1st Owner
627 627 627 Noida

No Of Owner(s)
1st Owner
628 628 628 Noida

No Of Owner(s)
1st Owner
629 629 629 Noida

No Of Owner(s)
1st Owner
630 630 630 Noida

No Of Owner(s)
1st Owner
631 631 631 Noida

No Of Owner(s)
1st Owner
632 632 632 Noida

No Of Owner(s)
1st Owner
633 633 633 Noida

No Of Owner(s)
1st Owner
634 634 634 Noida

No Of Owner(s)
1st Owner
635 635 635 Noida

No Of Owner(s)
1st Owner
636 636 636 Noida

No Of Owner(s)
2nd Owner
637 637 637 Noida

No Of Owner(s)
1st Owner
638 638 638 Noida

No Of Owner(s)
1st Owner
639 639 639 Noida

No Of Owner(s)
1st Owner
640 640 640 Noida

No Of Owner(s)
1st Owner
641 641 641 Noida

No Of Owner(s)
1st Owner
642 642 642 Noida

No Of Owner(s)
1st Owner
643 643 643 Noida

No Of Owner(s)
1st Owner
644 644 644 Noida

No Of Owner(s)
1st Owner
645 645 645 Noida

First Owner
646 646 646 Noida

First Owner
647 647 647 Noida

First Owner
648 648 648 Noida

Third Owner
649 649 649 Noida

First Owner
650 650 650 Noida

First Owner
651 651 651 Noida

Second Owner
652 652 652 Noida

Second Owner
653 653 653 Noida

First Owner
654 654 654 Noida

First Owner
655 655 655 Noida

First Owner
656 656 656 Noida

First Owner
657 657 657 Noida

First Owner
658 658 658 Noida

First Owner
659 659 659 Noida

Second Owner
660 660 660 Noida

Second Owner
661 661 661 Noida

First Owner
662 662 662 Noida

First Owner
663 663 663 Noida

First Owner
664 664 664 Noida

First Owner
665 665 665 Noida

First Owner
666 666 666 Noida

First Owner
667 667 667 Noida

First Owner
668 668 668 Noida

First Owner
669 669 669 Noida

First Owner
670 670 670 Noida

First Owner
671 671 671 Noida

Second Owner
672 672 672 Noida

Second Owner
673 673 673 Noida

First Owner
674 674 674 Noida

First Owner
675 675 675 Noida

First Owner
676 676 676 Noida

First Owner
677 677 677 Noida

First Owner
678 678 678 Noida

First Owner
679 679 679 Noida

Second Owner
680 680 680 Noida

Second Owner
681 681 681 Noida

First Owner
682 682 682 Noida

First Owner
683 683 683 Noida

First Owner
684 684 684 Noida

First Owner
685 685 685 Noida

First Owner
686 686 686 Noida

First Owner
687 687 687 Noida

First Owner
688 688 688 Noida

First Owner
689 689 689 Noida

First Owner
690 690 690 Noida

First Owner
691 691 691 Noida

First Owner
692 692 692 Noida

First Owner
693 693 693 Noida

First Owner
694 694 694 Noida

First Owner
695 695 695 Noida

Second Owner
696 696 696 Noida

First Owner
697 697 697 Noida

First Owner
698 698 698 Noida

First Owner
699 699 699 Noida

First Owner
700 700 700 Noida

First Owner
701 701 701 Noida

Second Owner
702 702 702 Noida

No Of Owner(s)
1st Owner
703 703 703 Noida

No Of Owner(s)
1st Owner
704 704 704 Noida

No Of Owner(s)
1st Owner
705 705 705 Noida

No Of Owner(s)
1st Owner
706 706 706 Noida

No Of Owner(s)
1st Owner
707 707 707 Noida

No Of Owner(s)
1st Owner
708 708 708 Noida

No Of Owner(s)
1st Owner
709 709 709 Noida

No Of Owner(s)
2nd Owner
710 710 710 Noida

No Of Owner(s)
1st Owner
711 711 711 Noida

No Of Owner(s)
1st Owner
712 712 712 Noida

No Of Owner(s)
2nd Owner
713 713 713 Noida

No Of Owner(s)
1st Owner
714 714 714 Noida

No Of Owner(s)
1st Owner
715 715 715 Noida

No Of Owner(s)
1st Owner
716 716 716 Noida

No Of Owner(s)
1st Owner
717 717 717 Noida

First Owner
718 718 718 Noida

First Owner
719 719 719 Noida

First Owner
720 720 720 Noida

First Owner
721 721 721 Noida

First Owner
722 722 722 Noida

First Owner
723 723 723 Noida

First Owner
724 724 724 Noida

First Owner
725 725 725 Noida

First Owner
726 726 726 Noida

First Owner
727 727 727 Noida

First Owner
728 728 728 Noida

No Of Owner(s)
1st Owner
729 729 729 Noida

No Of Owner(s)
1st Owner
730 730 730 Noida

No Of Owner(s)
1st Owner
731 731 731 Noida

No Of Owner(s)
1st Owner
732 732 732 Noida

No Of Owner(s)
1st Owner
733 733 733 Noida

No Of Owner(s)
1st Owner
734 734 734 Noida

No Of Owner(s)
1st Owner
735 735 735 Noida

No Of Owner(s)
1st Owner
736 736 736 Noida

No Of Owner(s)
1st Owner
737 737 737 Noida

No Of Owner(s)
1st Owner
738 738 738 Noida

No Of Owner(s)
1st Owner
739 739 739 Noida

No Of Owner(s)
1st Owner
740 740 740 Noida

No Of Owner(s)
1st Owner
741 741 741 Noida

First Owner
742 742 742 Noida

Second Owner
743 743 743 Noida

Third Owner
744 744 744 Noida

Second Owner
745 745 745 Noida

First Owner
746 746 746 Noida

Second Owner
747 747 747 Noida

In [506]:
cardekho_10=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                  'Engine':(engine),
                  'Number_of_Owners':(owner),
                  'Transmission':(transmission),
                  'Milaege':(mileage),
                  'Max_Power':(max_power),
                  'Torque':(torque),
                   'Body_Type':(body_type),
                   'Location':(city[10]),
                  'Price':(price)})
cardekho_10

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Engine,Number_of_Owners,Transmission,Milaege,Max_Power,Torque,Body_Type,Location,Price
0,Renault,Renault KWID,1.0 RXT Optional,2017,Petrol,"72,081",999,No Of Owner(s)\n1st Owner,Manual,23.01,Max Power\n67bhp,Torque\n91Nm,Hatchback,Noida,266500
1,Honda,Honda Brio,S MT,2012,Petrol,"99,235",1198,No Of Owner(s)\n1st Owner,Manual,19.4,Max Power\n86.8bhp,Torque\n109Nm,Hatchback,Noida,246500
2,Maruti,Maruti Baleno,1.3 Delta,2016,Diesel,"36,993",1248,No Of Owner(s)\n1st Owner,Manual,27.39,Max Power\n74bhp,Torque\n190Nm,Hatchback,Noida,489000
3,Honda,Honda Brio,S MT,2013,Petrol,"36,163",1198,No Of Owner(s)\n2nd Owner,Manual,19.4,Max Power\n86.8bhp,Torque\n109Nm,Hatchback,Noida,258000
4,Maruti,Maruti Swift,VDI,2014,Diesel,"90,169",1248,No Of Owner(s)\n1st Owner,Manual,28.4,Max Power\n74bhp,Torque\n190Nm,Hatchback,Noida,400500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,Maruti,Maruti Eeco 5 STR With AC Plus HTR CNG,None,2015,CNG,"55,000",1196,Second Owner,Manual,15.1,Max Power\n73 bhp,Torque\n101Nm@ 3000rpm,Minivan,Noida,310000
743,Mercedes-Benz,Mercedes-Benz E-Class E250 CDI Avantgarde,None,2013,Diesel,"64,000",2143,Third Owner,Automatic,14.21,Max Power\n203 bhp,Torque\n500Nm@ 1600-1800rpm,Luxury,Noida,1475000
744,Audi,Audi Q3 2.0 TDI Quattro Premium Plus,None,2012,Diesel,"64,000",1968,Second Owner,Automatic,15.73,Max Power\n174.33 bhp,Torque\n380Nm@ 1750-2500rpm,Luxury,Noida,1275000
745,Mercedes-Benz,Mercedes-Benz CLA 200 CDI Sport,None,2017,Diesel,"35,000",2143,First Owner,Automatic,17.9,Max Power\n136 bhp,Torque\n300Nm@ 1600-3000rpm,Luxury,Noida,2200000
746,Audi,Audi Q7 2006-2020 3.0 TDI Quattro Premium Plus,None,2014,Diesel,"88,000",2967,Second Owner,Automatic,12.07,Max Power\n241.4 bhp,Torque\n550Nm@ 1750-2750rpm,Luxury,Noida,2450000

In [507]:
cardekho_10['Source']='CarDekho'
cardekho_10.to_csv('cardekho10.csv')

In [ ]:
cardekho_10['Body_Type'].value_counts()

In [108]:
model=[]
brand=[]
variant=[]
price=[]
make_year=[]
reg_year=[]
fuel=[]
km=[]
engine=[]
owner=[]
transmission=[]
mileage=[]
max_power=[]
torque=[]
body_type=[]
location=[]

In [109]:
#city 9
for i in range(1):
    for j in range(0,6):
        driver.get(city_url[9])
        for _ in range(100):
            driver.execute_script("window.scrollBy(0,20)")
        body_type_ele=driver.find_elements_by_xpath('//ul[@class="checkBoxWrap bodyTypes cd-bodyTicon"]//li')
        b_type=body_type_ele[j].text
        try:
            driver.implicitly_wait(10)
            ActionChains(driver).move_to_element(body_type_ele[j]).click(body_type_ele[j]).perform()
            
        except ElementNotInteractableException:
            continue
        
        except StaleElementReferenceException:
            continue

        for _ in range(2000):
            driver.execute_script("window.scrollBy(0,20)")

        urls=[]
        url_ele=driver.find_elements_by_xpath('//div[@class="gsc_col-xs-7 carsName"]//a')
        for ele in url_ele:
            try:
                urls.append(ele.get_attribute('href'))
            except StaleElementReferenceException:
                continue
    
        for url in urls:
            driver.get(url)
            for _ in range(50):
                driver.execute_script("window.scrollBy(0,20)")
            try:
                price_ele=driver.find_element_by_xpath('//span[@class="amount"]')
                pr=float(price_ele.text[:-6])
                price.append(int(pr*100000))
                    
                model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1[2]')
                model.append(model_ele.text)
                    
                str=model_ele.text
                for k in range(len(str)):
                    if str[k]==' ':
                        x=k
                        break
                brand.append(str[:x])
                
                info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6"]')
                make_year.append(info_ele[0].text)
                km.append(info_ele[2].text[:-4])
                
                owner.append(info_ele[3].text)
                fuel.append(info_ele[4].text)
                transmission.append(info_ele[5].text)
                mileage.append(info_ele[8].text[8:-5])
                
                if len(info_ele)>8:
                    engine.append(info_ele[9].text[7:-3])
                    
                    if len(info_ele)>10:
                        max_power.append(info_ele[10].text)
                        torque.append(info_ele[11].text)
                    else:
                        max_power.append(None)
                        torque.append(None)
                    
                else:
                    engine.append(None)
                    max_power.append(None)
                    torque.append(None)
                    
            except NoSuchElementException:
                try:
                    price_ele=driver.find_element_by_xpath('//div[@class="priceSection"]//span[2]')
                    str=price_ele.text
                    price.append(str.replace(',',''))
                
                    model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1')
                    model.append(model_ele.text[5:])
                
                    str=model_ele.text[5:]
                    for k in range(len(str)):
                        if str[k]==' ':
                            x=k
                            break
                    brand.append(str[:x])
                    
                    info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6 gsc_col-md-4"]')
                    make_year.append(info_ele[0].text[10:])
                    fuel.append(info_ele[2].text[5:])
                    km.append(info_ele[3].text[11:-4])
                    engine.append(info_ele[4].text[20:-3])
                    owner.append(info_ele[5].text)
                
                    if len(info_ele)>=12:
                        transmission.append(info_ele[7].text[13:])
                        mileage.append(info_ele[9].text[8:-5])
                        max_power.append(info_ele[11].text)
                        torque.append(info_ele[12].text)
                    else:
                        transmission.append(None)
                        mileage.append(None)
                        max_power.append(None)
                        torque.append(None)
                except NoSuchElementException:
                    continue
    
            try:
                var_ele=driver.find_element_by_xpath('//div[@class="variant-name"]')
                variant.append(var_ele.text)
        
            except NoSuchElementException:
                variant.append(None)
   
            body_type.append(b_type)
            location.append(city[9])
            if len(owner)<len(model):
                owner.append(None)
            print(len(model),len(owner),len(location),b_type,city[9],'\n')

1 1 1 Hatchback New Delhi

2 2 2 Hatchback New Delhi

3 3 3 Hatchback New Delhi

4 4 4 Hatchback New Delhi

5 5 5 Hatchback New Delhi

6 6 6 Hatchback New Delhi

7 7 7 Hatchback New Delhi

8 8 8 Hatchback New Delhi

9 9 9 Hatchback New Delhi

10 10 10 Hatchback New Delhi

11 11 11 Hatchback New Delhi

12 12 12 Hatchback New Delhi

13 13 13 Hatchback New Delhi

14 14 14 Hatchback New Delhi

15 15 15 Hatchback New Delhi

16 16 16 Hatchback New Delhi

17 17 17 Hatchback New Delhi

18 18 18 Hatchback New Delhi

19 19 19 Hatchback New Delhi

20 20 20 Hatchback New Delhi

21 21 21 Hatchback New Delhi

22 22 22 Hatchback New Delhi

23 23 23 Hatchback New Delhi

24 24 24 Hatchback New Delhi

25 25 25 Hatchback New Delhi

26 26 26 Hatchback New Delhi

27 27 27 Hatchback New Delhi

28 28 28 Hatchback New Delhi

29 29 29 Hatchback New Delhi

30 30 30 Hatchback New Delhi

31 31 31 Hatchback New Delhi

32 32 32 Hatchback New Delhi

33 33 33 Hatchback New Delhi

34 34 34 Hatchback New Delhi

35 35 35 Hatchback New Delhi

36 36 36 Hatchback New Delhi

37 37 37 Hatchback New Delhi

38 38 38 Hatchback New Delhi

39 39 39 Hatchback New Delhi

40 40 40 Hatchback New Delhi

41 41 41 Hatchback New Delhi

42 42 42 Hatchback New Delhi

43 43 43 Hatchback New Delhi

44 44 44 Hatchback New Delhi

45 45 45 Hatchback New Delhi

46 46 46 Hatchback New Delhi

47 47 47 Hatchback New Delhi

48 48 48 Hatchback New Delhi

49 49 49 Hatchback New Delhi

50 50 50 Hatchback New Delhi

51 51 51 Hatchback New Delhi

52 52 52 Hatchback New Delhi

53 53 53 Hatchback New Delhi

54 54 54 Hatchback New Delhi

55 55 55 Hatchback New Delhi

56 56 56 Hatchback New Delhi

57 57 57 Hatchback New Delhi

58 58 58 Hatchback New Delhi

59 59 59 Hatchback New Delhi

60 60 60 Hatchback New Delhi

61 61 61 Hatchback New Delhi

62 62 62 Hatchback New Delhi

63 63 63 Hatchback New Delhi

64 64 64 Hatchback New Delhi

65 65 65 Hatchback New Delhi

66 66 66 Hatchback New Delhi

67 67 67 Hatchback New Delhi

68 68 68 Hatchback New Delhi

69 69 69 Hatchback New Delhi

70 70 70 Hatchback New Delhi

71 71 71 Hatchback New Delhi

72 72 72 Hatchback New Delhi

73 73 73 Hatchback New Delhi

74 74 74 Hatchback New Delhi

75 75 75 Hatchback New Delhi

76 76 76 Hatchback New Delhi

77 77 77 Hatchback New Delhi

78 78 78 Hatchback New Delhi

79 79 79 Hatchback New Delhi

80 80 80 Hatchback New Delhi

81 81 81 Hatchback New Delhi

82 82 82 Hatchback New Delhi

83 83 83 Hatchback New Delhi

84 84 84 Hatchback New Delhi

85 85 85 Hatchback New Delhi

86 86 86 Hatchback New Delhi

87 87 87 Hatchback New Delhi

88 88 88 Hatchback New Delhi

89 89 89 Hatchback New Delhi

90 90 90 Hatchback New Delhi

91 91 91 Hatchback New Delhi

92 92 92 Hatchback New Delhi

93 93 93 Hatchback New Delhi

94 94 94 Hatchback New Delhi

95 95 95 Hatchback New Delhi

96 96 96 Hatchback New Delhi

97 97 97 Hatchback New Delhi

98 98 98 Hatchback New Delhi

99 99 99 Hatchback New Delhi

100 100 100 Sedan New Delhi

101 101 101 Sedan New Delhi

102 102 102 Sedan New Delhi

103 103 103 Sedan New Delhi

104 104 104 Sedan New Delhi

105 105 105 Sedan New Delhi

106 106 106 Sedan New Delhi

107 107 107 Sedan New Delhi

108 108 108 Sedan New Delhi

109 109 109 Sedan New Delhi

110 110 110 Sedan New Delhi

111 111 111 Sedan New Delhi

112 112 112 Sedan New Delhi

113 113 113 Sedan New Delhi

114 114 114 Sedan New Delhi

115 115 115 Sedan New Delhi

116 116 116 Sedan New Delhi

117 117 117 Sedan New Delhi

118 118 118 Sedan New Delhi

119 119 119 Sedan New Delhi

120 120 120 Sedan New Delhi

121 121 121 Sedan New Delhi

122 122 122 Sedan New Delhi

123 123 123 Sedan New Delhi

124 124 124 Sedan New Delhi

125 125 125 Sedan New Delhi

126 126 126 Sedan New Delhi

127 127 127 Sedan New Delhi

128 128 128 Sedan New Delhi

129 129 129 Sedan New Delhi

130 130 130 Sedan New Delhi

131 131 131 Sedan New Delhi

132 132 132 Sedan New Delhi

133 133 133 Sedan New Delhi

134 134 134 Sedan New Delhi

135 135 135 Sedan New Delhi

136 136 136 Sedan New Delhi

137 137 137 Sedan New Delhi

138 138 138 Sedan New Delhi

139 139 139 Sedan New Delhi

140 140 140 Sedan New Delhi

141 141 141 Sedan New Delhi

142 142 142 Sedan New Delhi

143 143 143 Sedan New Delhi

144 144 144 Sedan New Delhi

145 145 145 Sedan New Delhi

146 146 146 Sedan New Delhi

147 147 147 Sedan New Delhi

148 148 148 Sedan New Delhi

149 149 149 Sedan New Delhi

150 150 150 Sedan New Delhi

151 151 151 Sedan New Delhi

152 152 152 Sedan New Delhi

153 153 153 Sedan New Delhi

154 154 154 Sedan New Delhi

155 155 155 Sedan New Delhi

156 156 156 Sedan New Delhi

157 157 157 Sedan New Delhi

158 158 158 Sedan New Delhi

159 159 159 Sedan New Delhi

160 160 160 Sedan New Delhi

161 161 161 Sedan New Delhi

162 162 162 Sedan New Delhi

163 163 163 Sedan New Delhi

164 164 164 Sedan New Delhi

165 165 165 Sedan New Delhi

166 166 166 Sedan New Delhi

167 167 167 Sedan New Delhi

168 168 168 Sedan New Delhi

169 169 169 Sedan New Delhi

170 170 170 Sedan New Delhi

171 171 171 Sedan New Delhi

172 172 172 Sedan New Delhi

173 173 173 Sedan New Delhi

174 174 174 Sedan New Delhi

175 175 175 Sedan New Delhi

176 176 176 Sedan New Delhi

177 177 177 Sedan New Delhi

178 178 178 Sedan New Delhi

179 179 179 Sedan New Delhi

180 180 180 Sedan New Delhi

181 181 181 Sedan New Delhi

182 182 182 Sedan New Delhi

183 183 183 Sedan New Delhi

184 184 184 Sedan New Delhi

185 185 185 Sedan New Delhi

186 186 186 Sedan New Delhi

187 187 187 Sedan New Delhi

188 188 188 Sedan New Delhi

189 189 189 Sedan New Delhi

190 190 190 Sedan New Delhi

191 191 191 Sedan New Delhi

192 192 192 Sedan New Delhi

193 193 193 Sedan New Delhi

194 194 194 Sedan New Delhi

195 195 195 Sedan New Delhi

196 196 196 Sedan New Delhi

197 197 197 Sedan New Delhi

198 198 198 Sedan New Delhi

199 199 199 Sedan New Delhi

200 200 200 Sedan New Delhi

201 201 201 Sedan New Delhi

202 202 202 Sedan New Delhi

203 203 203 Sedan New Delhi

204 204 204 Sedan New Delhi

205 205 205 Sedan New Delhi

206 206 206 Sedan New Delhi

207 207 207 Sedan New Delhi

208 208 208 Sedan New Delhi

209 209 209 Sedan New Delhi

210 210 210 Sedan New Delhi

211 211 211 Sedan New Delhi

212 212 212 Sedan New Delhi

213 213 213 Sedan New Delhi

214 214 214 Sedan New Delhi

215 215 215 Sedan New Delhi

216 216 216 Sedan New Delhi

217 217 217 Sedan New Delhi

218 218 218 Sedan New Delhi

219 219 219 Sedan New Delhi

220 220 220 Sedan New Delhi

221 221 221 Sedan New Delhi

222 222 222 Sedan New Delhi

223 223 223 Sedan New Delhi

224 224 224 Sedan New Delhi

225 225 225 Sedan New Delhi

226 226 226 Sedan New Delhi

227 227 227 Sedan New Delhi

228 228 228 Sedan New Delhi

229 229 229 Sedan New Delhi

230 230 230 Sedan New Delhi

231 231 231 Sedan New Delhi

232 232 232 Sedan New Delhi

233 233 233 Sedan New Delhi

234 234 234 Sedan New Delhi

235 235 235 Sedan New Delhi

236 236 236 Sedan New Delhi

237 237 237 Sedan New Delhi

238 238 238 Sedan New Delhi

239 239 239 Sedan New Delhi

240 240 240 Sedan New Delhi

241 241 241 Sedan New Delhi

242 242 242 Sedan New Delhi

243 243 243 Sedan New Delhi

244 244 244 Sedan New Delhi

245 245 245 Sedan New Delhi

246 246 246 Sedan New Delhi

247 247 247 Sedan New Delhi

248 248 248 Sedan New Delhi

249 249 249 Sedan New Delhi

250 250 250 Sedan New Delhi

251 251 251 Sedan New Delhi

252 252 252 Sedan New Delhi

253 253 253 Sedan New Delhi

254 254 254 Sedan New Delhi

255 255 255 Sedan New Delhi

256 256 256 Sedan New Delhi

257 257 257 Sedan New Delhi

258 258 258 Sedan New Delhi

259 259 259 Sedan New Delhi

260 260 260 Sedan New Delhi

261 261 261 Sedan New Delhi

262 262 262 Sedan New Delhi

263 263 263 Sedan New Delhi

264 264 264 Sedan New Delhi

265 265 265 Sedan New Delhi

266 266 266 Sedan New Delhi

267 267 267 Sedan New Delhi

268 268 268 Sedan New Delhi

269 269 269 Sedan New Delhi

270 270 270 Sedan New Delhi

271 271 271 Sedan New Delhi

272 272 272 Sedan New Delhi

273 273 273 Sedan New Delhi

274 274 274 Sedan New Delhi

275 275 275 Sedan New Delhi

276 276 276 Sedan New Delhi

277 277 277 Sedan New Delhi

278 278 278 Sedan New Delhi

279 279 279 Sedan New Delhi

280 280 280 Sedan New Delhi

281 281 281 Sedan New Delhi

282 282 282 Sedan New Delhi

283 283 283 Sedan New Delhi

284 284 284 Sedan New Delhi

285 285 285 Sedan New Delhi

286 286 286 Sedan New Delhi

287 287 287 Sedan New Delhi

288 288 288 Sedan New Delhi

289 289 289 Sedan New Delhi

290 290 290 Sedan New Delhi

291 291 291 Sedan New Delhi

292 292 292 Sedan New Delhi

293 293 293 Sedan New Delhi

294 294 294 Sedan New Delhi

295 295 295 Sedan New Delhi

296 296 296 Sedan New Delhi

297 297 297 Sedan New Delhi

298 298 298 Sedan New Delhi

299 299 299 Sedan New Delhi

300 300 300 Sedan New Delhi

301 301 301 Sedan New Delhi

302 302 302 Sedan New Delhi

303 303 303 Sedan New Delhi

304 304 304 Sedan New Delhi

305 305 305 Sedan New Delhi

306 306 306 Sedan New Delhi

307 307 307 Sedan New Delhi

308 308 308 Sedan New Delhi

309 309 309 Sedan New Delhi

310 310 310 Sedan New Delhi

311 311 311 Sedan New Delhi

312 312 312 Sedan New Delhi

313 313 313 Sedan New Delhi

314 314 314 Sedan New Delhi

315 315 315 Sedan New Delhi

316 316 316 Sedan New Delhi

317 317 317 Sedan New Delhi

318 318 318 Sedan New Delhi

319 319 319 Sedan New Delhi

320 320 320 Sedan New Delhi

321 321 321 Sedan New Delhi

322 322 322 Sedan New Delhi

323 323 323 Sedan New Delhi

324 324 324 Sedan New Delhi

325 325 325 Sedan New Delhi

326 326 326 Sedan New Delhi

327 327 327 Sedan New Delhi

328 328 328 Sedan New Delhi

329 329 329 Sedan New Delhi

330 330 330 Sedan New Delhi

331 331 331 Sedan New Delhi

332 332 332 Sedan New Delhi

333 333 333 Sedan New Delhi

334 334 334 Sedan New Delhi

335 335 335 Sedan New Delhi

336 336 336 Sedan New Delhi

337 337 337 Sedan New Delhi

338 338 338 Sedan New Delhi

339 339 339 Sedan New Delhi

340 340 340 Sedan New Delhi

341 341 341 Sedan New Delhi

342 342 342 Sedan New Delhi

343 343 343 Sedan New Delhi

344 344 344 Sedan New Delhi

345 345 345 Sedan New Delhi

346 346 346 Sedan New Delhi

347 347 347 Sedan New Delhi

348 348 348 Sedan New Delhi

349 349 349 Sedan New Delhi

350 350 350 Sedan New Delhi

351 351 351 Sedan New Delhi

352 352 352 Sedan New Delhi

353 353 353 Sedan New Delhi

354 354 354 Sedan New Delhi

355 355 355 Sedan New Delhi

356 356 356 Sedan New Delhi

357 357 357 Sedan New Delhi

358 358 358 Sedan New Delhi

359 359 359 Sedan New Delhi

360 360 360 Sedan New Delhi

361 361 361 Sedan New Delhi

362 362 362 Sedan New Delhi

363 363 363 Sedan New Delhi

364 364 364 Sedan New Delhi

365 365 365 Sedan New Delhi

366 366 366 Sedan New Delhi

367 367 367 Sedan New Delhi

368 368 368 Sedan New Delhi

369 369 369 Sedan New Delhi

370 370 370 Sedan New Delhi

371 371 371 Sedan New Delhi

372 372 372 Sedan New Delhi

373 373 373 Sedan New Delhi

374 374 374 Sedan New Delhi

375 375 375 Sedan New Delhi

376 376 376 Sedan New Delhi

377 377 377 Sedan New Delhi

378 378 378 Sedan New Delhi

379 379 379 Sedan New Delhi

380 380 380 Sedan New Delhi

381 381 381 Sedan New Delhi

382 382 382 Sedan New Delhi

383 383 383 Sedan New Delhi

384 384 384 Sedan New Delhi

385 385 385 Sedan New Delhi

386 386 386 Sedan New Delhi

387 387 387 Sedan New Delhi

388 388 388 Sedan New Delhi

389 389 389 Sedan New Delhi

390 390 390 Sedan New Delhi

391 391 391 Sedan New Delhi

392 392 392 Sedan New Delhi

393 393 393 Sedan New Delhi

394 394 394 Sedan New Delhi

395 395 395 Sedan New Delhi

396 396 396 Sedan New Delhi

397 397 397 Sedan New Delhi

398 398 398 Sedan New Delhi

399 399 399 SUV New Delhi

400 400 400 SUV New Delhi

401 401 401 SUV New Delhi

402 402 402 SUV New Delhi

403 403 403 SUV New Delhi

404 404 404 SUV New Delhi

405 405 405 SUV New Delhi

406 406 406 SUV New Delhi

407 407 407 SUV New Delhi

408 408 408 SUV New Delhi

409 409 409 SUV New Delhi

410 410 410 SUV New Delhi

411 411 411 SUV New Delhi

412 412 412 SUV New Delhi

413 413 413 SUV New Delhi

414 414 414 SUV New Delhi

415 415 415 SUV New Delhi

416 416 416 SUV New Delhi

417 417 417 SUV New Delhi

418 418 418 SUV New Delhi

419 419 419 SUV New Delhi

420 420 420 SUV New Delhi

421 421 421 SUV New Delhi

422 422 422 SUV New Delhi

423 423 423 SUV New Delhi

424 424 424 SUV New Delhi

425 425 425 SUV New Delhi

426 426 426 SUV New Delhi

427 427 427 SUV New Delhi

428 428 428 SUV New Delhi

429 429 429 SUV New Delhi

430 430 430 SUV New Delhi

431 431 431 SUV New Delhi

432 432 432 SUV New Delhi

433 433 433 SUV New Delhi

434 434 434 SUV New Delhi

435 435 435 SUV New Delhi

436 436 436 SUV New Delhi

437 437 437 SUV New Delhi

438 438 438 SUV New Delhi

439 439 439 SUV New Delhi

440 440 440 SUV New Delhi

441 441 441 SUV New Delhi

442 442 442 SUV New Delhi

443 443 443 SUV New Delhi

444 444 444 SUV New Delhi

445 445 445 SUV New Delhi

446 446 446 SUV New Delhi

447 447 447 SUV New Delhi

448 448 448 SUV New Delhi

449 449 449 SUV New Delhi

450 450 450 SUV New Delhi

451 451 451 SUV New Delhi

452 452 452 SUV New Delhi

453 453 453 SUV New Delhi

454 454 454 SUV New Delhi

455 455 455 SUV New Delhi

456 456 456 SUV New Delhi

457 457 457 SUV New Delhi

458 458 458 SUV New Delhi

459 459 459 SUV New Delhi

460 460 460 SUV New Delhi

461 461 461 SUV New Delhi

462 462 462 SUV New Delhi

463 463 463 SUV New Delhi

464 464 464 SUV New Delhi

465 465 465 SUV New Delhi

466 466 466 SUV New Delhi

467 467 467 SUV New Delhi

468 468 468 SUV New Delhi

469 469 469 SUV New Delhi

470 470 470 SUV New Delhi

471 471 471 SUV New Delhi

472 472 472 SUV New Delhi

473 473 473 SUV New Delhi

474 474 474 SUV New Delhi

475 475 475 SUV New Delhi

476 476 476 SUV New Delhi

477 477 477 SUV New Delhi

478 478 478 SUV New Delhi

479 479 479 SUV New Delhi

480 480 480 SUV New Delhi

481 481 481 SUV New Delhi

482 482 482 SUV New Delhi

483 483 483 SUV New Delhi

484 484 484 SUV New Delhi

485 485 485 SUV New Delhi

486 486 486 SUV New Delhi

487 487 487 SUV New Delhi

488 488 488 SUV New Delhi

489 489 489 SUV New Delhi

490 490 490 SUV New Delhi

491 491 491 SUV New Delhi

492 492 492 SUV New Delhi

493 493 493 SUV New Delhi

494 494 494 SUV New Delhi

495 495 495 SUV New Delhi

496 496 496 SUV New Delhi

497 497 497 SUV New Delhi

498 498 498 SUV New Delhi

499 499 499 SUV New Delhi

500 500 500 SUV New Delhi

501 501 501 SUV New Delhi

502 502 502 SUV New Delhi

503 503 503 SUV New Delhi

504 504 504 SUV New Delhi

505 505 505 SUV New Delhi

506 506 506 SUV New Delhi

507 507 507 SUV New Delhi

508 508 508 SUV New Delhi

509 509 509 SUV New Delhi

510 510 510 SUV New Delhi

511 511 511 SUV New Delhi

512 512 512 SUV New Delhi

513 513 513 SUV New Delhi

514 514 514 SUV New Delhi

515 515 515 SUV New Delhi

516 516 516 SUV New Delhi

517 517 517 SUV New Delhi

518 518 518 SUV New Delhi

519 519 519 SUV New Delhi

520 520 520 SUV New Delhi

521 521 521 SUV New Delhi

522 522 522 SUV New Delhi

523 523 523 SUV New Delhi

524 524 524 SUV New Delhi

525 525 525 SUV New Delhi

526 526 526 SUV New Delhi

527 527 527 SUV New Delhi

528 528 528 SUV New Delhi

529 529 529 SUV New Delhi

530 530 530 SUV New Delhi

531 531 531 SUV New Delhi

532 532 532 SUV New Delhi

533 533 533 SUV New Delhi

534 534 534 SUV New Delhi

535 535 535 SUV New Delhi

536 536 536 SUV New Delhi

537 537 537 SUV New Delhi

538 538 538 SUV New Delhi

539 539 539 SUV New Delhi

540 540 540 SUV New Delhi

541 541 541 SUV New Delhi

542 542 542 SUV New Delhi

543 543 543 SUV New Delhi

544 544 544 SUV New Delhi

545 545 545 SUV New Delhi

546 546 546 SUV New Delhi

547 547 547 SUV New Delhi

548 548 548 SUV New Delhi

549 549 549 SUV New Delhi

550 550 550 SUV New Delhi

551 551 551 SUV New Delhi

552 552 552 SUV New Delhi

553 553 553 SUV New Delhi

554 554 554 SUV New Delhi

555 555 555 SUV New Delhi

556 556 556 SUV New Delhi

557 557 557 SUV New Delhi

558 558 558 SUV New Delhi

559 559 559 SUV New Delhi

560 560 560 SUV New Delhi

561 561 561 SUV New Delhi

562 562 562 SUV New Delhi

563 563 563 SUV New Delhi

564 564 564 SUV New Delhi

565 565 565 SUV New Delhi

566 566 566 SUV New Delhi

567 567 567 SUV New Delhi

568 568 568 SUV New Delhi

569 569 569 SUV New Delhi

570 570 570 SUV New Delhi

571 571 571 SUV New Delhi

572 572 572 SUV New Delhi

573 573 573 SUV New Delhi

574 574 574 SUV New Delhi

575 575 575 SUV New Delhi

576 576 576 SUV New Delhi

577 577 577 SUV New Delhi

578 578 578 SUV New Delhi

579 579 579 SUV New Delhi

580 580 580 SUV New Delhi

581 581 581 SUV New Delhi

582 582 582 SUV New Delhi

583 583 583 SUV New Delhi

584 584 584 SUV New Delhi

585 585 585 SUV New Delhi

586 586 586 SUV New Delhi

587 587 587 SUV New Delhi

588 588 588 SUV New Delhi

589 589 589 SUV New Delhi

590 590 590 SUV New Delhi

591 591 591 SUV New Delhi

592 592 592 SUV New Delhi

593 593 593 SUV New Delhi

594 594 594 SUV New Delhi

595 595 595 SUV New Delhi

596 596 596 SUV New Delhi

597 597 597 SUV New Delhi

598 598 598 SUV New Delhi

599 599 599 SUV New Delhi

600 600 600 SUV New Delhi

601 601 601 SUV New Delhi

602 602 602 SUV New Delhi

603 603 603 SUV New Delhi

604 604 604 SUV New Delhi

605 605 605 SUV New Delhi

606 606 606 SUV New Delhi

607 607 607 SUV New Delhi

608 608 608 SUV New Delhi

609 609 609 SUV New Delhi

610 610 610 SUV New Delhi

611 611 611 SUV New Delhi

612 612 612 SUV New Delhi

613 613 613 SUV New Delhi

614 614 614 SUV New Delhi

615 615 615 SUV New Delhi

616 616 616 SUV New Delhi

617 617 617 SUV New Delhi

618 618 618 SUV New Delhi

619 619 619 SUV New Delhi

620 620 620 SUV New Delhi

621 621 621 SUV New Delhi

622 622 622 SUV New Delhi

623 623 623 SUV New Delhi

624 624 624 SUV New Delhi

625 625 625 SUV New Delhi

626 626 626 SUV New Delhi

627 627 627 SUV New Delhi

628 628 628 SUV New Delhi

629 629 629 SUV New Delhi

630 630 630 SUV New Delhi

631 631 631 SUV New Delhi

632 632 632 SUV New Delhi

633 633 633 SUV New Delhi

634 634 634 SUV New Delhi

635 635 635 SUV New Delhi

636 636 636 SUV New Delhi

637 637 637 SUV New Delhi

638 638 638 SUV New Delhi

639 639 639 SUV New Delhi

640 640 640 SUV New Delhi

641 641 641 SUV New Delhi

642 642 642 SUV New Delhi

643 643 643 SUV New Delhi

644 644 644 SUV New Delhi

645 645 645 SUV New Delhi

646 646 646 SUV New Delhi

647 647 647 SUV New Delhi

648 648 648 SUV New Delhi

649 649 649 SUV New Delhi

650 650 650 SUV New Delhi

651 651 651 SUV New Delhi

652 652 652 SUV New Delhi

653 653 653 SUV New Delhi

654 654 654 SUV New Delhi

655 655 655 SUV New Delhi

656 656 656 SUV New Delhi

657 657 657 SUV New Delhi

658 658 658 SUV New Delhi

659 659 659 SUV New Delhi

660 660 660 SUV New Delhi

661 661 661 SUV New Delhi

662 662 662 SUV New Delhi

663 663 663 SUV New Delhi

664 664 664 SUV New Delhi

665 665 665 SUV New Delhi

666 666 666 SUV New Delhi

667 667 667 SUV New Delhi

668 668 668 SUV New Delhi

669 669 669 SUV New Delhi

670 670 670 SUV New Delhi

671 671 671 SUV New Delhi

672 672 672 SUV New Delhi

673 673 673 SUV New Delhi

674 674 674 SUV New Delhi

675 675 675 SUV New Delhi

676 676 676 SUV New Delhi

677 677 677 SUV New Delhi

678 678 678 SUV New Delhi

679 679 679 SUV New Delhi

680 680 680 SUV New Delhi

681 681 681 SUV New Delhi

682 682 682 SUV New Delhi

683 683 683 SUV New Delhi

684 684 684 SUV New Delhi

685 685 685 SUV New Delhi

686 686 686 SUV New Delhi

687 687 687 SUV New Delhi

688 688 688 SUV New Delhi

689 689 689 SUV New Delhi

690 690 690 SUV New Delhi

691 691 691 SUV New Delhi

692 692 692 SUV New Delhi

693 693 693 SUV New Delhi

694 694 694 SUV New Delhi

695 695 695 SUV New Delhi

696 696 696 SUV New Delhi

697 697 697 SUV New Delhi

698 698 698 SUV New Delhi

699 699 699 SUV New Delhi

700 700 700 SUV New Delhi

701 701 701 SUV New Delhi

702 702 702 SUV New Delhi

703 703 703 SUV New Delhi

704 704 704 SUV New Delhi

705 705 705 SUV New Delhi

706 706 706 SUV New Delhi

707 707 707 SUV New Delhi

708 708 708 SUV New Delhi

709 709 709 SUV New Delhi

710 710 710 SUV New Delhi

711 711 711 SUV New Delhi

712 712 712 Luxury New Delhi

713 713 713 Luxury New Delhi

714 714 714 Luxury New Delhi

715 715 715 Luxury New Delhi

716 716 716 Luxury New Delhi

717 717 717 Luxury New Delhi

718 718 718 Luxury New Delhi

719 719 719 Luxury New Delhi

720 720 720 Luxury New Delhi

721 721 721 Luxury New Delhi

722 722 722 Luxury New Delhi

723 723 723 Luxury New Delhi

724 724 724 Luxury New Delhi

725 725 725 Luxury New Delhi

726 726 726 Luxury New Delhi

727 727 727 Luxury New Delhi

728 728 728 Luxury New Delhi

729 729 729 Luxury New Delhi

730 730 730 Luxury New Delhi

731 731 731 Luxury New Delhi

732 732 732 Luxury New Delhi

733 733 733 Luxury New Delhi

734 734 734 Luxury New Delhi

735 735 735 Luxury New Delhi

736 736 736 Luxury New Delhi

737 737 737 Luxury New Delhi

738 738 738 Luxury New Delhi

739 739 739 Luxury New Delhi

740 740 740 Luxury New Delhi

741 741 741 Luxury New Delhi

742 742 742 Luxury New Delhi

743 743 743 Luxury New Delhi

744 744 744 Luxury New Delhi

745 745 745 Luxury New Delhi

746 746 746 Luxury New Delhi

747 747 747 Luxury New Delhi

748 748 748 Luxury New Delhi

749 749 749 Luxury New Delhi

750 750 750 Luxury New Delhi

751 751 751 Luxury New Delhi

752 752 752 Luxury New Delhi

753 753 753 Luxury New Delhi

754 754 754 Luxury New Delhi

755 755 755 Luxury New Delhi

756 756 756 Luxury New Delhi

757 757 757 Luxury New Delhi

758 758 758 Luxury New Delhi

759 759 759 Luxury New Delhi

760 760 760 Luxury New Delhi

761 761 761 Luxury New Delhi

762 762 762 Luxury New Delhi

763 763 763 Luxury New Delhi

764 764 764 Luxury New Delhi

765 765 765 Luxury New Delhi

766 766 766 Luxury New Delhi

767 767 767 Luxury New Delhi

768 768 768 Luxury New Delhi

769 769 769 Luxury New Delhi

770 770 770 Luxury New Delhi

771 771 771 Luxury New Delhi

772 772 772 Luxury New Delhi

773 773 773 Luxury New Delhi

774 774 774 Luxury New Delhi

775 775 775 Luxury New Delhi

776 776 776 Luxury New Delhi

777 777 777 Luxury New Delhi

778 778 778 Luxury New Delhi

779 779 779 Luxury New Delhi

780 780 780 Luxury New Delhi

781 781 781 Luxury New Delhi

782 782 782 Luxury New Delhi

783 783 783 Luxury New Delhi

784 784 784 Luxury New Delhi

785 785 785 Luxury New Delhi

786 786 786 Luxury New Delhi

787 787 787 Luxury New Delhi

788 788 788 Luxury New Delhi

789 789 789 Luxury New Delhi

790 790 790 Luxury New Delhi

791 791 791 Luxury New Delhi

792 792 792 Luxury New Delhi

793 793 793 Luxury New Delhi

794 794 794 Luxury New Delhi

795 795 795 Luxury New Delhi

796 796 796 Luxury New Delhi

797 797 797 Luxury New Delhi

798 798 798 Luxury New Delhi

799 799 799 Luxury New Delhi

800 800 800 Luxury New Delhi

801 801 801 Luxury New Delhi

802 802 802 Luxury New Delhi

803 803 803 Luxury New Delhi

804 804 804 Luxury New Delhi

805 805 805 Luxury New Delhi

806 806 806 Luxury New Delhi

807 807 807 Luxury New Delhi

808 808 808 Luxury New Delhi

809 809 809 Luxury New Delhi

810 810 810 Luxury New Delhi

811 811 811 Luxury New Delhi

812 812 812 Luxury New Delhi

813 813 813 Luxury New Delhi

814 814 814 Luxury New Delhi

815 815 815 Luxury New Delhi

816 816 816 Luxury New Delhi

IndexError: list index out of range

In [115]:
cardekho_9=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                  'Engine':(engine),
                  'Number_of_Owners':(owner),
                  'Transmission':(transmission),
                  'Milaege':(mileage),
                  'Max_Power':(max_power),
                  'Torque':(torque),
                   'Body_Type':(body_type),
                   'Location':(city[9]),
                  'Price':(price)})
cardekho_9

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Engine,Number_of_Owners,Transmission,Milaege,Max_Power,Torque,Body_Type,Location,Price
0,Maruti,Maruti Ignis,1.2 Zeta BSIV,2018,Petrol,"29,837",1197,No Of Owner(s)\n1st Owner,,e Type\nZer,Engine\n1197 CC,Max Power\n81.80bhp,Hatchback,New Delhi,520500
1,Maruti,Maruti Baleno,Delta,2018,Petrol,"34,377",1197,No Of Owner(s)\n1st Owner,Manual,21.01,Max Power\n81.80bhp,Torque\n113Nm,Hatchback,New Delhi,563870
2,Hyundai,Hyundai i10,Sportz 1.1L,2015,Petrol,"23,198",1086,No Of Owner(s)\n1st Owner,Manual,19.81,Max Power\n68.05bhp,Torque\n99.04Nm,Hatchback,New Delhi,450000
3,Maruti,Maruti Swift,VDI BSIV,2018,Diesel,"75,710",1248,No Of Owner(s)\n1st Owner,Manual,25.2,Max Power\n74bhp,Torque\n190Nm,Hatchback,New Delhi,618500
4,Hyundai,Hyundai i20,Sportz,2017,Petrol,"36,375",1197,No Of Owner(s)\n1st Owner,Manual,20.35,Max Power\n81.86bhp,Torque\n114.74nm,Hatchback,New Delhi,562000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
812,Audi,Audi Q3 2.0 TDI Quattro Premium Plus,None,2013,Diesel,"83,000",1968,Second Owner,Automatic,15.73,Max Power\n174.33 bhp,Torque\n380Nm@ 1750-2500rpm,Luxury,New Delhi,1350000
813,Audi,Audi A4 35 TFSi Premium,None,2014,Petrol,"35,000",1798,First Owner,Automatic,15.64,Max Power\n167.62 bhp,Torque\n320Nm@ 1400-3700rpm,Luxury,New Delhi,1648999
814,Audi,Audi S5 3.0 TFSIq Tiptronic,None,2020,Petrol,"1,001",2995,First Owner,Automatic,12.28,Max Power\n348.66 bhp,Torque\n500Nm@ 1370-4500rpm,Luxury,New Delhi,7750000
815,BMW,BMW Z4 2009-2013 35i,None,2011,Petrol,"12,000",2979,First Owner,Automatic,10.37,Max Power\n306 bhp,Torque\n400Nm@ 1300-5000rpm,Luxury,New Delhi,3175000
816,BMW,BMW X1 sDrive 20D xLine,None,2012,Diesel,"93,000",l,Second Owner,Automatic,17.05,None,None,Luxury,New Delhi,690000

In [119]:
cardekho_9['Source']='CarDekho'
cardekho_9.to_csv('cardekho9.csv')

In [124]:
model=[]
brand=[]
variant=[]
price=[]
make_year=[]
reg_year=[]
fuel=[]
km=[]
engine=[]
owner=[]
transmission=[]
mileage=[]
max_power=[]
torque=[]
body_type=[]
location=[]

In [125]:
#city 8
for i in range(1):
    for j in range(0,6):
        driver.get(city_url[8])
        for _ in range(100):
            driver.execute_script("window.scrollBy(0,20)")
        body_type_ele=driver.find_elements_by_xpath('//ul[@class="checkBoxWrap bodyTypes cd-bodyTicon"]//li')
        b_type=body_type_ele[j].text
        try:
            driver.implicitly_wait(10)
            ActionChains(driver).move_to_element(body_type_ele[j]).click(body_type_ele[j]).perform()
            
        except ElementNotInteractableException:
            continue
        
        except StaleElementReferenceException:
            continue

        for _ in range(2000):
            driver.execute_script("window.scrollBy(0,20)")

        urls=[]
        url_ele=driver.find_elements_by_xpath('//div[@class="gsc_col-xs-7 carsName"]//a')
        for ele in url_ele:
            try:
                urls.append(ele.get_attribute('href'))
            except StaleElementReferenceException:
                continue
        print(len(urls))
    
        for url in urls:
            driver.get(url)
            for _ in range(50):
                driver.execute_script("window.scrollBy(0,20)")
            try:
                price_ele=driver.find_element_by_xpath('//span[@class="amount"]')
                pr=float(price_ele.text[:-6])
                price.append(int(pr*100000))
                    
                model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1[2]')
                model.append(model_ele.text)
                    
                str=model_ele.text
                for k in range(len(str)):
                    if str[k]==' ':
                        x=k
                        break
                brand.append(str[:x])
                
                info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6"]')
                make_year.append(info_ele[0].text)
                km.append(info_ele[2].text[:-4])
                
                owner.append(info_ele[3].text)
                fuel.append(info_ele[4].text)
                transmission.append(info_ele[5].text)
                mileage.append(info_ele[8].text[8:-5])
                
                if len(info_ele)>8:
                    engine.append(info_ele[9].text[7:-3])
                    
                    if len(info_ele)>=10:
                        max_power.append(info_ele[10].text)
                        torque.append(info_ele[11].text)
                    else:
                        max_power.append(None)
                        torque.append(None)
                    
                else:
                    engine.append(None)
                    max_power.append(None)
                    torque.append(None)
                    
            except NoSuchElementException:
                try:
                    price_ele=driver.find_element_by_xpath('//div[@class="priceSection"]//span[2]')
                    str=price_ele.text
                    price.append(str.replace(',',''))
                
                    model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1')
                    model.append(model_ele.text[5:])
                
                    str=model_ele.text[5:]
                    for k in range(len(str)):
                        if str[k]==' ':
                            x=k
                            break
                    brand.append(str[:x])
                    
                    info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6 gsc_col-md-4"]')
                    make_year.append(info_ele[0].text[10:])
                    fuel.append(info_ele[2].text[5:])
                    km.append(info_ele[3].text[11:-4])
                    engine.append(info_ele[4].text[20:-3])
                    owner.append(info_ele[5].text)
                
                    if len(info_ele)>=12:
                        transmission.append(info_ele[7].text[13:])
                        mileage.append(info_ele[9].text[8:-5])
                        max_power.append(info_ele[11].text)
                        torque.append(info_ele[12].text)
                    else:
                        transmission.append(None)
                        mileage.append(None)
                        max_power.append(None)
                        torque.append(None)
                except NoSuchElementException:
                    continue
    
            try:
                var_ele=driver.find_element_by_xpath('//div[@class="variant-name"]')
                variant.append(var_ele.text)
        
            except NoSuchElementException:
                variant.append(None)
   
            body_type.append(b_type)
            location.append(city[8])
            if len(owner)<len(model):
                owner.append(None)
            print(len(model),len(owner),len(location),b_type,city[8],'\n')

20
1 1 1 Sedan Mumbai

2 2 2 Sedan Mumbai

3 3 3 Sedan Mumbai

4 4 4 Sedan Mumbai

5 5 5 Sedan Mumbai

6 6 6 Sedan Mumbai

7 7 7 Sedan Mumbai

8 8 8 Sedan Mumbai

9 9 9 Sedan Mumbai

10 10 10 Sedan Mumbai

11 11 11 Sedan Mumbai

12 12 12 Sedan Mumbai

13 13 13 Sedan Mumbai

14 14 14 Sedan Mumbai

15 15 15 Sedan Mumbai

16 16 16 Sedan Mumbai

17 17 17 Sedan Mumbai

18 18 18 Sedan Mumbai

19 19 19 Sedan Mumbai

20 20 20 Sedan Mumbai

19
21 21 21 Hatchback Mumbai

22 22 22 Hatchback Mumbai

23 23 23 Hatchback Mumbai

24 24 24 Hatchback Mumbai

25 25 25 Hatchback Mumbai

26 26 26 Hatchback Mumbai

27 27 27 Hatchback Mumbai

28 28 28 Hatchback Mumbai

29 29 29 Hatchback Mumbai

30 30 30 Hatchback Mumbai

31 31 31 Hatchback Mumbai

32 32 32 Hatchback Mumbai

33 33 33 Hatchback Mumbai

34 34 34 Hatchback Mumbai

35 35 35 Hatchback Mumbai

36 36 36 Hatchback Mumbai

37 37 37 Hatchback Mumbai

38 38 38 Hatchback Mumbai

39 39 39 Hatchback Mumbai

20
40 40 40 SUV Mumbai

41 41 41 SUV Mumbai

42 42 42 SUV Mumbai

43 43 43 SUV Mumbai

44 44 44 SUV Mumbai

45 45 45 SUV Mumbai

46 46 46 SUV Mumbai

47 47 47 SUV Mumbai

48 48 48 SUV Mumbai

49 49 49 SUV Mumbai

50 50 50 SUV Mumbai

51 51 51 SUV Mumbai

52 52 52 SUV Mumbai

53 53 53 SUV Mumbai

54 54 54 SUV Mumbai

55 55 55 SUV Mumbai

56 56 56 SUV Mumbai

57 57 57 SUV Mumbai

58 58 58 SUV Mumbai

59 59 59 SUV Mumbai

20
60 60 60 MUV Mumbai

61 61 61 MUV Mumbai

62 62 62 MUV Mumbai

63 63 63 MUV Mumbai

64 64 64 MUV Mumbai

65 65 65 MUV Mumbai

66 66 66 MUV Mumbai

67 67 67 MUV Mumbai

68 68 68 MUV Mumbai

69 69 69 MUV Mumbai

70 70 70 MUV Mumbai

71 71 71 MUV Mumbai

72 72 72 MUV Mumbai

73 73 73 MUV Mumbai

74 74 74 MUV Mumbai

75 75 75 MUV Mumbai

76 76 76 MUV Mumbai

77 77 77 MUV Mumbai

78 78 78 MUV Mumbai

79 79 79 MUV Mumbai

19
80 80 80 Luxury Mumbai

81 81 81 Luxury Mumbai

82 82 82 Luxury Mumbai

83 83 83 Luxury Mumbai

84 84 84 Luxury Mumbai

85 85 85 Luxury Mumbai

86 86 86 Luxury Mumbai

87 87 87 Luxury Mumbai

88 88 88 Luxury Mumbai

89 89 89 Luxury Mumbai

90 90 90 Luxury Mumbai

91 91 91 Luxury Mumbai

92 92 92 Luxury Mumbai

93 93 93 Luxury Mumbai

94 94 94 Luxury Mumbai

95 95 95 Luxury Mumbai

96 96 96 Luxury Mumbai

97 97 97 Luxury Mumbai

98 98 98 Luxury Mumbai

20
99 99 99 Minivan Mumbai

100 100 100 Minivan Mumbai

101 101 101 Minivan Mumbai

102 102 102 Minivan Mumbai

103 103 103 Minivan Mumbai

104 104 104 Minivan Mumbai

105 105 105 Minivan Mumbai

106 106 106 Minivan Mumbai

107 107 107 Minivan Mumbai

108 108 108 Minivan Mumbai

109 109 109 Minivan Mumbai

110 110 110 Minivan Mumbai

111 111 111 Minivan Mumbai

112 112 112 Minivan Mumbai

113 113 113 Minivan Mumbai

114 114 114 Minivan Mumbai

115 115 115 Minivan Mumbai

116 116 116 Minivan Mumbai

117 117 117 Minivan Mumbai

118 118 118 Minivan Mumbai

In [126]:
cardekho_8=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                  'Engine':(engine),
                  'Number_of_Owners':(owner),
                  'Transmission':(transmission),
                  'Milaege':(mileage),
                  'Max_Power':(max_power),
                  'Torque':(torque),
                   'Body_Type':(body_type),
                   'Location':(city[8]),
                  'Price':(price)})
cardekho_8

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Engine,Number_of_Owners,Transmission,Milaege,Max_Power,Torque,Body_Type,Location,Price
0,Tata,Tata Tigor,1.2 Revotron XT,2018,Petrol,"13,205",1199,No Of Owner(s)\n1st Owner,Manual,20.3,Max Power\n84bhp,Torque\n114Nm,Sedan,Mumbai,542500
1,Maruti,Maruti Ciaz,ZXi,2015,Petrol,"28,226",1373,No Of Owner(s)\n1st Owner,Manual,20.73,Max Power\n91.1bhp,Torque\n130Nm,Sedan,Mumbai,605000
2,Maruti,Maruti Ciaz,ZXi Plus,2015,Petrol,"38,058",1373,No Of Owner(s)\n1st Owner,Manual,20.73,Max Power\n91.1bhp,Torque\n130Nm,Sedan,Mumbai,662500
3,Maruti,Maruti Swift Dzire,AMT ZDI Plus,2017,Diesel,"64,535",1248,No Of Owner(s)\n1st Owner,Automatic,28.4,Max Power\n74.02bhp,Torque\n190Nm,Sedan,Mumbai,744500
4,Honda,Honda Amaze,S,2020,Petrol,"27,390",1199,No Of Owner(s)\n1st Owner,Manual,18.6,Max Power\n88.76bhp,Torque\n110nm,Sedan,Mumbai,703000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,Mercedes-Benz,Mercedes-Benz CLA 200 CGI Sport,None,2018,Petrol,"17,300",1991,Second Owner,Automatic,15.04,Max Power\n183 bhp,Torque\n300Nm@ 1200-4000rpm,Minivan,Mumbai,2700000
114,Toyota,Toyota Innova Crysta 2016-2020 2.4 ZX MT,None,2018,Diesel,"18,123",2393,First Owner,Manual,13.68,Max Power\n147.51 bhp,Torque\n343Nm@ 1400-2800rpm,Minivan,Mumbai,1975000
115,Hyundai,Hyundai Verna VTVT 1.6 AT SX Option,None,2018,Petrol,"12,500",1591,First Owner,Automatic,17.0,Max Power\n121.3 bhp,Torque\n151Nm@ 4850rpm,Minivan,Mumbai,1125000
116,Volkswagen,Volkswagen Vento 1.6 Highline,None,2015,Petrol,"46,000",1598,Second Owner,Manual,15.04,Max Power\n103.2 bhp,Torque\n153Nm@ 3800rpm,Minivan,Mumbai,550000
117,Honda,Honda Jazz V CVT,None,2017,Petrol,"33,500",1199,First Owner,Automatic,18.2,Max Power\n88.7 bhp,Torque\n110Nm@ 4800rpm,Minivan,Mumbai,680000

In [127]:
cardekho_8['Source']='CarDekho'
cardekho_8.to_csv('cardekho8.csv')

In [128]:
model=[]
brand=[]
variant=[]
price=[]
make_year=[]
reg_year=[]
fuel=[]
km=[]
engine=[]
owner=[]
transmission=[]
mileage=[]
max_power=[]
torque=[]
body_type=[]
location=[]

In [129]:
#city 7
for i in range(1):
    for j in range(0,6):
        driver.get(city_url[7])
        for _ in range(100):
            driver.execute_script("window.scrollBy(0,20)")
        body_type_ele=driver.find_elements_by_xpath('//ul[@class="checkBoxWrap bodyTypes cd-bodyTicon"]//li')
        b_type=body_type_ele[j].text
        try:
            driver.implicitly_wait(10)
            ActionChains(driver).move_to_element(body_type_ele[j]).click(body_type_ele[j]).perform()
            
        except ElementNotInteractableException:
            continue
        
        except StaleElementReferenceException:
            continue

        for _ in range(2000):
            driver.execute_script("window.scrollBy(0,20)")

        urls=[]
        url_ele=driver.find_elements_by_xpath('//div[@class="gsc_col-xs-7 carsName"]//a')
        for ele in url_ele:
            try:
                urls.append(ele.get_attribute('href'))
            except StaleElementReferenceException:
                continue
    
        for url in urls:
            driver.get(url)
            for _ in range(50):
                driver.execute_script("window.scrollBy(0,20)")
            try:
                price_ele=driver.find_element_by_xpath('//span[@class="amount"]')
                pr=float(price_ele.text[:-6])
                price.append(int(pr*100000))
                    
                model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1[2]')
                model.append(model_ele.text)
                    
                str=model_ele.text
                for k in range(len(str)):
                    if str[k]==' ':
                        x=k
                        break
                brand.append(str[:x])
                
                info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6"]')
                make_year.append(info_ele[0].text)
                km.append(info_ele[2].text[:-4])
                
                owner.append(info_ele[3].text)
                fuel.append(info_ele[4].text)
                transmission.append(info_ele[5].text)
                mileage.append(info_ele[8].text[8:-5])
                
                if len(info_ele)>8:
                    engine.append(info_ele[9].text[7:-3])
                    
                    if len(info_ele)>=10:
                        max_power.append(info_ele[10].text)
                        torque.append(info_ele[11].text)
                    else:
                        max_power.append(None)
                        torque.append(None)
                    
                else:
                    engine.append(None)
                    max_power.append(None)
                    torque.append(None)
                    
            except NoSuchElementException:
                try:
                    price_ele=driver.find_element_by_xpath('//div[@class="priceSection"]//span[2]')
                    str=price_ele.text
                    price.append(str.replace(',',''))
                
                    model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1')
                    model.append(model_ele.text[5:])
                
                    str=model_ele.text[5:]
                    for k in range(len(str)):
                        if str[k]==' ':
                            x=k
                            break
                    brand.append(str[:x])
                    
                    info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6 gsc_col-md-4"]')
                    make_year.append(info_ele[0].text[10:])
                    fuel.append(info_ele[2].text[5:])
                    km.append(info_ele[3].text[11:-4])
                    engine.append(info_ele[4].text[20:-3])
                    owner.append(info_ele[5].text)
                
                    if len(info_ele)>=12:
                        transmission.append(info_ele[7].text[13:])
                        mileage.append(info_ele[9].text[8:-5])
                        max_power.append(info_ele[11].text)
                        torque.append(info_ele[12].text)
                    else:
                        transmission.append(None)
                        mileage.append(None)
                        max_power.append(None)
                        torque.append(None)
                except NoSuchElementException:
                    continue
    
            try:
                var_ele=driver.find_element_by_xpath('//div[@class="variant-name"]')
                variant.append(var_ele.text)
        
            except NoSuchElementException:
                variant.append(None)
   
            body_type.append(b_type)
            location.append(city[7])
            if len(owner)<len(model):
                owner.append(None)
            print(len(model),len(owner),len(location),b_type,city[7],'\n')

1 1 1 Hatchback Kolkata

2 2 2 Hatchback Kolkata

3 3 3 Hatchback Kolkata

4 4 4 Hatchback Kolkata

5 5 5 Hatchback Kolkata

6 6 6 Hatchback Kolkata

7 7 7 Hatchback Kolkata

8 8 8 Hatchback Kolkata

9 9 9 Hatchback Kolkata

10 10 10 Hatchback Kolkata

11 11 11 Hatchback Kolkata

12 12 12 Hatchback Kolkata

13 13 13 Hatchback Kolkata

14 14 14 Hatchback Kolkata

15 15 15 Hatchback Kolkata

16 16 16 Hatchback Kolkata

17 17 17 Hatchback Kolkata

18 18 18 Hatchback Kolkata

19 19 19 Hatchback Kolkata

20 20 20 Hatchback Kolkata

21 21 21 Sedan Kolkata

22 22 22 Sedan Kolkata

23 23 23 Sedan Kolkata

24 24 24 Sedan Kolkata

25 25 25 Sedan Kolkata

26 26 26 Sedan Kolkata

27 27 27 Sedan Kolkata

28 28 28 Sedan Kolkata

29 29 29 Sedan Kolkata

30 30 30 Sedan Kolkata

31 31 31 Sedan Kolkata

32 32 32 Sedan Kolkata

33 33 33 Sedan Kolkata

34 34 34 Sedan Kolkata

35 35 35 Sedan Kolkata

36 36 36 Sedan Kolkata

37 37 37 Sedan Kolkata

38 38 38 Sedan Kolkata

39 39 39 Sedan Kolkata

40 40 40 Sedan Kolkata

41 41 41 SUV Kolkata

42 42 42 SUV Kolkata

43 43 43 SUV Kolkata

44 44 44 SUV Kolkata

45 45 45 SUV Kolkata

46 46 46 SUV Kolkata

47 47 47 SUV Kolkata

48 48 48 SUV Kolkata

49 49 49 SUV Kolkata

50 50 50 SUV Kolkata

51 51 51 SUV Kolkata

52 52 52 SUV Kolkata

53 53 53 SUV Kolkata

54 54 54 SUV Kolkata

55 55 55 SUV Kolkata

56 56 56 SUV Kolkata

57 57 57 SUV Kolkata

58 58 58 SUV Kolkata

59 59 59 SUV Kolkata

60 60 60 SUV Kolkata

61 61 61 Luxury Kolkata

62 62 62 Luxury Kolkata

63 63 63 Luxury Kolkata

64 64 64 Luxury Kolkata

65 65 65 Luxury Kolkata

66 66 66 Luxury Kolkata

67 67 67 Luxury Kolkata

68 68 68 Luxury Kolkata

69 69 69 Luxury Kolkata

70 70 70 Luxury Kolkata

71 71 71 Luxury Kolkata

72 72 72 Luxury Kolkata

73 73 73 Luxury Kolkata

74 74 74 Luxury Kolkata

75 75 75 Luxury Kolkata

76 76 76 Luxury Kolkata

77 77 77 Luxury Kolkata

78 78 78 Luxury Kolkata

79 79 79 Luxury Kolkata

80 80 80 Luxury Kolkata

81 81 81 MUV Kolkata

82 82 82 MUV Kolkata

83 83 83 MUV Kolkata

84 84 84 MUV Kolkata

85 85 85 MUV Kolkata

86 86 86 MUV Kolkata

87 87 87 MUV Kolkata

88 88 88 MUV Kolkata

89 89 89 MUV Kolkata

90 90 90 MUV Kolkata

91 91 91 MUV Kolkata

92 92 92 MUV Kolkata

93 93 93 MUV Kolkata

94 94 94 MUV Kolkata

95 95 95 MUV Kolkata

96 96 96 MUV Kolkata

97 97 97 MUV Kolkata

98 98 98 MUV Kolkata

99 99 99 MUV Kolkata

100 100 100 MUV Kolkata

101 101 101 Minivan Kolkata

102 102 102 Minivan Kolkata

103 103 103 Minivan Kolkata

104 104 104 Minivan Kolkata

In [130]:
cardekho_7=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                  'Engine':(engine),
                  'Number_of_Owners':(owner),
                  'Transmission':(transmission),
                  'Milaege':(mileage),
                  'Max_Power':(max_power),
                  'Torque':(torque),
                   'Body_Type':(body_type),
                   'Location':(city[7]),
                  'Price':(price)})
cardekho_7

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Engine,Number_of_Owners,Transmission,Milaege,Max_Power,Torque,Body_Type,Location,Price
0,Hyundai,Hyundai i10 Magna,None,2015,Petrol,"49,000",1197,First Owner,Manual,20.36,Max Power\n78.9 bhp,Torque\n111.7Nm@ 4000rpm,Hatchback,Kolkata,300000
1,Maruti,Maruti Wagon R Stingray VXI Optional,None,2015,Petrol,"12,000",998,First Owner,Manual,20.51,Max Power\n67.04 bhp,Torque\n90Nm@ 3500rpm,Hatchback,Kolkata,390000
2,Hyundai,Hyundai i20 Magna 1.2,None,2015,Petrol,"41,000",1197,Second Owner,Manual,18.6,Max Power\n81.83 bhp,Torque\n114.7Nm@ 4000rpm,Hatchback,Kolkata,445000
3,Skoda,Skoda Fabia 1.2 Petrol Active,None,2012,Petrol,"29,658",1198,First Owner,Manual,16.25,Max Power\n73.9 bhp,Torque\n110Nm@ 3750rpm,Hatchback,Kolkata,219000
4,Honda,Honda Jazz 1.2 V i VTEC,None,2016,Petrol,"37,256",1199,First Owner,Manual,18.7,Max Power\n88.7 bhp,Torque\n110Nm@ 4800rpm,Hatchback,Kolkata,449000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,Maruti,Maruti Ertiga BSIV VXI,None,2017,Petrol,"11,000",1373,First Owner,Manual,17.5,Max Power\n91.1 bhp,Torque\n130Nm@ 4000rpm,MUV,Kolkata,650000
100,Maruti,Maruti Eeco 7 Seater STD,None,2010,Petrol,"20,000",1196,First Owner,Manual,16.11,Max Power\n72.42 bhp,Torque\n98Nm@ 3000rpm,Minivan,Kolkata,199000
101,Maruti,Maruti Omni 8 Seater BSIV,None,2014,Petrol,"55,000",796,First Owner,Manual,14.0,Max Power\n35 bhp,Torque\n6.1kgm@ 3000rpm,Minivan,Kolkata,165000
102,Maruti,Maruti Eeco 5 Seater AC BSIV,None,2017,Petrol,"10,000",1196,First Owner,Manual,15.37,Max Power\n73 bhp,Torque\n101Nm@ 3000rpm,Minivan,Kolkata,361000
103,Maruti,Maruti Omni MPI Ambulance BSIV,None,2015,Petrol,"1,20,000",796,First Owner,Manual,16.8,Max Power\n34.2 bhp,Torque\n59Nm@ 2500rpm,Minivan,Kolkata,281000

In [131]:
cardekho_7['Source']='CarDekho'
cardekho_7.to_csv('cardekho7.csv')

In [132]:
model=[]
brand=[]
variant=[]
price=[]
make_year=[]
reg_year=[]
fuel=[]
km=[]
engine=[]
owner=[]
transmission=[]
mileage=[]
max_power=[]
torque=[]
body_type=[]
location=[]

In [133]:
#city 6
for i in range(1):
    for j in range(0,6):
        driver.get(city_url[6])
        for _ in range(100):
            driver.execute_script("window.scrollBy(0,20)")
        body_type_ele=driver.find_elements_by_xpath('//ul[@class="checkBoxWrap bodyTypes cd-bodyTicon"]//li')
        b_type=body_type_ele[j].text
        try:
            driver.implicitly_wait(10)
            ActionChains(driver).move_to_element(body_type_ele[j]).click(body_type_ele[j]).perform()
            
        except ElementNotInteractableException:
            continue
        
        except StaleElementReferenceException:
            continue

        for _ in range(2000):
            driver.execute_script("window.scrollBy(0,20)")

        urls=[]
        url_ele=driver.find_elements_by_xpath('//div[@class="gsc_col-xs-7 carsName"]//a')
        for ele in url_ele:
            try:
                urls.append(ele.get_attribute('href'))
            except StaleElementReferenceException:
                continue
    
        for url in urls:
            driver.get(url)
            for _ in range(50):
                driver.execute_script("window.scrollBy(0,20)")
            try:
                price_ele=driver.find_element_by_xpath('//span[@class="amount"]')
                pr=float(price_ele.text[:-6])
                price.append(int(pr*100000))
                    
                model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1[2]')
                model.append(model_ele.text)
                    
                str=model_ele.text
                for k in range(len(str)):
                    if str[k]==' ':
                        x=k
                        break
                brand.append(str[:x])
                
                info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6"]')
                make_year.append(info_ele[0].text)
                km.append(info_ele[2].text[:-4])
                
                owner.append(info_ele[3].text)
                fuel.append(info_ele[4].text)
                transmission.append(info_ele[5].text)
                mileage.append(info_ele[8].text[8:-5])
                
                if len(info_ele)>8:
                    engine.append(info_ele[9].text[7:-3])
                    
                    if len(info_ele)>=10:
                        max_power.append(info_ele[10].text)
                        torque.append(info_ele[11].text)
                    else:
                        max_power.append(None)
                        torque.append(None)
                    
                else:
                    engine.append(None)
                    max_power.append(None)
                    torque.append(None)
                    
            except NoSuchElementException:
                try:
                    price_ele=driver.find_element_by_xpath('//div[@class="priceSection"]//span[2]')
                    str=price_ele.text
                    price.append(str.replace(',',''))
                
                    model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1')
                    model.append(model_ele.text[5:])
                
                    str=model_ele.text[5:]
                    for k in range(len(str)):
                        if str[k]==' ':
                            x=k
                            break
                    brand.append(str[:x])
                    
                    info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6 gsc_col-md-4"]')
                    make_year.append(info_ele[0].text[10:])
                    fuel.append(info_ele[2].text[5:])
                    km.append(info_ele[3].text[11:-4])
                    engine.append(info_ele[4].text[20:-3])
                    owner.append(info_ele[5].text)
                
                    if len(info_ele)>=12:
                        transmission.append(info_ele[7].text[13:])
                        mileage.append(info_ele[9].text[8:-5])
                        max_power.append(info_ele[11].text)
                        torque.append(info_ele[12].text)
                    else:
                        transmission.append(None)
                        mileage.append(None)
                        max_power.append(None)
                        torque.append(None)
                except NoSuchElementException:
                    continue
    
            try:
                var_ele=driver.find_element_by_xpath('//div[@class="variant-name"]')
                variant.append(var_ele.text)
        
            except NoSuchElementException:
                variant.append(None)
   
            body_type.append(b_type)
            location.append(city[6])
            if len(owner)<len(model):
                owner.append(None)
            print(len(model),len(owner),len(location),b_type,city[6],'\n')

1 1 1 Hatchback Jaipur

2 2 2 Hatchback Jaipur

3 3 3 Hatchback Jaipur

4 4 4 Hatchback Jaipur

5 5 5 Hatchback Jaipur

6 6 6 Hatchback Jaipur

7 7 7 Hatchback Jaipur

8 8 8 Hatchback Jaipur

9 9 9 Hatchback Jaipur

10 10 10 Hatchback Jaipur

11 11 11 Hatchback Jaipur

12 12 12 Hatchback Jaipur

13 13 13 Hatchback Jaipur

14 14 14 Hatchback Jaipur

15 15 15 Hatchback Jaipur

16 16 16 Hatchback Jaipur

17 17 17 Hatchback Jaipur

18 18 18 Hatchback Jaipur

19 19 19 Hatchback Jaipur

20 20 20 Hatchback Jaipur

21 21 21 Sedan Jaipur

22 22 22 Sedan Jaipur

23 23 23 Sedan Jaipur

24 24 24 Sedan Jaipur

25 25 25 Sedan Jaipur

26 26 26 Sedan Jaipur

27 27 27 Sedan Jaipur

28 28 28 Sedan Jaipur

29 29 29 Sedan Jaipur

30 30 30 Sedan Jaipur

31 31 31 Sedan Jaipur

32 32 32 Sedan Jaipur

33 33 33 Sedan Jaipur

34 34 34 Sedan Jaipur

35 35 35 Sedan Jaipur

36 36 36 Sedan Jaipur

37 37 37 Sedan Jaipur

38 38 38 Sedan Jaipur

39 39 39 Sedan Jaipur

40 40 40 Sedan Jaipur

41 41 41 SUV Jaipur

42 42 42 SUV Jaipur

43 43 43 SUV Jaipur

44 44 44 SUV Jaipur

45 45 45 SUV Jaipur

46 46 46 SUV Jaipur

47 47 47 SUV Jaipur

48 48 48 SUV Jaipur

49 49 49 SUV Jaipur

50 50 50 SUV Jaipur

51 51 51 SUV Jaipur

52 52 52 SUV Jaipur

53 53 53 SUV Jaipur

54 54 54 SUV Jaipur

55 55 55 SUV Jaipur

56 56 56 SUV Jaipur

57 57 57 SUV Jaipur

58 58 58 SUV Jaipur

59 59 59 SUV Jaipur

60 60 60 SUV Jaipur

61 61 61 Luxury Jaipur

62 62 62 Luxury Jaipur

63 63 63 Luxury Jaipur

64 64 64 Luxury Jaipur

65 65 65 Luxury Jaipur

66 66 66 Luxury Jaipur

67 67 67 Luxury Jaipur

68 68 68 Luxury Jaipur

69 69 69 Luxury Jaipur

70 70 70 Luxury Jaipur

71 71 71 Luxury Jaipur

72 72 72 Luxury Jaipur

73 73 73 Luxury Jaipur

74 74 74 Luxury Jaipur

75 75 75 Luxury Jaipur

76 76 76 MUV Jaipur

77 77 77 MUV Jaipur

78 78 78 MUV Jaipur

79 79 79 MUV Jaipur

80 80 80 MUV Jaipur

81 81 81 MUV Jaipur

82 82 82 MUV Jaipur

83 83 83 MUV Jaipur

84 84 84 MUV Jaipur

85 85 85 MUV Jaipur

86 86 86 MUV Jaipur

87 87 87 MUV Jaipur

88 88 88 Minivan Jaipur

89 89 89 Minivan Jaipur

90 90 90 Minivan Jaipur

91 91 91 Minivan Jaipur

92 92 92 Minivan Jaipur

93 93 93 Minivan Jaipur

94 94 94 Minivan Jaipur

95 95 95 Minivan Jaipur

96 96 96 Minivan Jaipur

97 97 97 Minivan Jaipur

In [134]:
cardekho_6=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                  'Engine':(engine),
                  'Number_of_Owners':(owner),
                  'Transmission':(transmission),
                  'Milaege':(mileage),
                  'Max_Power':(max_power),
                  'Torque':(torque),
                   'Body_Type':(body_type),
                   'Location':(city[6]),
                  'Price':(price)})
cardekho_6

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Engine,Number_of_Owners,Transmission,Milaege,Max_Power,Torque,Body_Type,Location,Price
0,Hyundai,Hyundai i20,Magna Plus,2019,Petrol,"7,000",1197,No Of Owner(s)\n1st Owner,,e Type\nThird,Engine\n1197 CC,Max Power\n81.86bhp,Hatchback,Jaipur,690000
1,Maruti,Maruti Baleno,1.2 Delta,2016,Petrol,"73,454",1197,No Of Owner(s)\n1st Owner,Manual,21.4,Max Power\n83.1bhp,Torque\n115Nm,Hatchback,Jaipur,499776
2,Maruti,Maruti Ignis,1.2 Sigma BSIV,2018,Petrol,"21,295",1197,No Of Owner(s)\n1st Owner,Manual,20.89,Max Power\n81.80bhp,Torque\n113Nm,Hatchback,Jaipur,474791
3,Maruti,Maruti Wagon R,VXI,2010,Petrol,"75,180",998,No Of Owner(s)\n2nd Owner,Manual,21.79,Max Power\n67.05bhp,Torque\n90Nm,Hatchback,Jaipur,215361
4,Renault,Renault KWID,RXL,2019,Petrol,"52,771",799,No Of Owner(s)\n1st Owner,Manual,20.71,Max Power\n53.26bhp,Torque\n72Nm,Hatchback,Jaipur,311015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,Maruti,Maruti Omni 8 Seater BSII,None,2010,Petrol,"88,700",796,Third Owner,Manual,19.7,Max Power\n35 bhp,Torque\n6.1kgm@ 3000rpm,Minivan,Jaipur,105000
93,Maruti,Maruti Omni E MPI STD BS IV,None,2011,Petrol,"85,086",796,Second Owner,Manual,16.8,Max Power\n34.2 bhp,Torque\n59Nm@ 2500rpm,Minivan,Jaipur,111000
94,Maruti,Maruti Omni E MPI STD,None,2007,Petrol,"58,972",796,Fourth & Above Owner,Manual,16.8,Max Power\n34.2 bhp,Torque\n59Nm@ 2500rpm,Minivan,Jaipur,800000
95,Maruti,Maruti Versa DX,None,2003,Petrol,"80,000",1298,Second Owner,Manual,11.3,Max Power\n83.1 bhp,"Torque\n10.4@ 3,000(kgm@ rpm)",Minivan,Jaipur,900000
96,Maruti,Maruti Omni MPI CARGO BSIV,None,2015,Petrol,"50,000",796,Second Owner,Manual,16.8,Max Power\n34.2 bhp,Torque\n59Nm@ 2500rpm,Minivan,Jaipur,225000

In [135]:
cardekho_6['Source']='CarDekho'
cardekho_6.to_csv('cardekho6.csv')

In [136]:
model=[]
brand=[]
variant=[]
price=[]
make_year=[]
reg_year=[]
fuel=[]
km=[]
engine=[]
owner=[]
transmission=[]
mileage=[]
max_power=[]
torque=[]
body_type=[]
location=[]

In [137]:
#city 5
for i in range(1):
    for j in range(0,6):
        driver.get(city_url[5])
        for _ in range(100):
            driver.execute_script("window.scrollBy(0,20)")
        body_type_ele=driver.find_elements_by_xpath('//ul[@class="checkBoxWrap bodyTypes cd-bodyTicon"]//li')
        b_type=body_type_ele[j].text
        try:
            driver.implicitly_wait(10)
            ActionChains(driver).move_to_element(body_type_ele[j]).click(body_type_ele[j]).perform()
            
        except ElementNotInteractableException:
            continue
        
        except StaleElementReferenceException:
            continue

        for _ in range(2000):
            driver.execute_script("window.scrollBy(0,20)")

        urls=[]
        url_ele=driver.find_elements_by_xpath('//div[@class="gsc_col-xs-7 carsName"]//a')
        for ele in url_ele:
            try:
                urls.append(ele.get_attribute('href'))
            except StaleElementReferenceException:
                continue
    
        for url in urls:
            driver.get(url)
            for _ in range(50):
                driver.execute_script("window.scrollBy(0,20)")
            try:
                price_ele=driver.find_element_by_xpath('//span[@class="amount"]')
                pr=float(price_ele.text[:-6])
                price.append(int(pr*100000))
                    
                model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1[2]')
                model.append(model_ele.text)
                    
                str=model_ele.text
                for k in range(len(str)):
                    if str[k]==' ':
                        x=k
                        break
                brand.append(str[:x])
                
                info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6"]')
                make_year.append(info_ele[0].text)
                km.append(info_ele[2].text[:-4])
                
                owner.append(info_ele[3].text)
                fuel.append(info_ele[4].text)
                transmission.append(info_ele[5].text)
                mileage.append(info_ele[8].text[8:-5])
                
                if len(info_ele)>8:
                    engine.append(info_ele[9].text[7:-3])
                    
                    if len(info_ele)>=10:
                        max_power.append(info_ele[10].text)
                        torque.append(info_ele[11].text)
                    else:
                        max_power.append(None)
                        torque.append(None)
                    
                else:
                    engine.append(None)
                    max_power.append(None)
                    torque.append(None)
                    
            except NoSuchElementException:
                try:
                    price_ele=driver.find_element_by_xpath('//div[@class="priceSection"]//span[2]')
                    str=price_ele.text
                    price.append(str.replace(',',''))
                
                    model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1')
                    model.append(model_ele.text[5:])
                
                    str=model_ele.text[5:]
                    for k in range(len(str)):
                        if str[k]==' ':
                            x=k
                            break
                    brand.append(str[:x])
                    
                    info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6 gsc_col-md-4"]')
                    make_year.append(info_ele[0].text[10:])
                    fuel.append(info_ele[2].text[5:])
                    km.append(info_ele[3].text[11:-4])
                    engine.append(info_ele[4].text[20:-3])
                    owner.append(info_ele[5].text)
                
                    if len(info_ele)>=12:
                        transmission.append(info_ele[7].text[13:])
                        mileage.append(info_ele[9].text[8:-5])
                        max_power.append(info_ele[11].text)
                        torque.append(info_ele[12].text)
                    else:
                        transmission.append(None)
                        mileage.append(None)
                        max_power.append(None)
                        torque.append(None)
                except NoSuchElementException:
                    continue
    
            try:
                var_ele=driver.find_element_by_xpath('//div[@class="variant-name"]')
                variant.append(var_ele.text)
        
            except NoSuchElementException:
                variant.append(None)
   
            body_type.append(b_type)
            location.append(city[5])
            if len(owner)<len(model):
                owner.append(None)
            print(len(model),len(owner),len(location),b_type,city[5],'\n')

1 1 1 Hatchback Hyderabad

2 2 2 Hatchback Hyderabad

3 3 3 Hatchback Hyderabad

4 4 4 Hatchback Hyderabad

5 5 5 Hatchback Hyderabad

6 6 6 Hatchback Hyderabad

7 7 7 Hatchback Hyderabad

8 8 8 Hatchback Hyderabad

9 9 9 Hatchback Hyderabad

10 10 10 Hatchback Hyderabad

11 11 11 Hatchback Hyderabad

12 12 12 Hatchback Hyderabad

13 13 13 Hatchback Hyderabad

14 14 14 Hatchback Hyderabad

15 15 15 Hatchback Hyderabad

16 16 16 Hatchback Hyderabad

17 17 17 Hatchback Hyderabad

18 18 18 Hatchback Hyderabad

19 19 19 Hatchback Hyderabad

20 20 20 Sedan Hyderabad

21 21 21 Sedan Hyderabad

22 22 22 Sedan Hyderabad

23 23 23 Sedan Hyderabad

24 24 24 Sedan Hyderabad

25 25 25 Sedan Hyderabad

26 26 26 Sedan Hyderabad

27 27 27 Sedan Hyderabad

28 28 28 Sedan Hyderabad

29 29 29 Sedan Hyderabad

30 30 30 Sedan Hyderabad

31 31 31 Sedan Hyderabad

32 32 32 Sedan Hyderabad

33 33 33 Sedan Hyderabad

34 34 34 Sedan Hyderabad

35 35 35 Sedan Hyderabad

36 36 36 Sedan Hyderabad

37 37 37 Sedan Hyderabad

38 38 38 Sedan Hyderabad

39 39 39 SUV Hyderabad

40 40 40 SUV Hyderabad

41 41 41 SUV Hyderabad

42 42 42 SUV Hyderabad

43 43 43 SUV Hyderabad

44 44 44 SUV Hyderabad

45 45 45 SUV Hyderabad

46 46 46 SUV Hyderabad

47 47 47 SUV Hyderabad

48 48 48 SUV Hyderabad

49 49 49 SUV Hyderabad

50 50 50 SUV Hyderabad

51 51 51 SUV Hyderabad

52 52 52 SUV Hyderabad

53 53 53 SUV Hyderabad

54 54 54 SUV Hyderabad

55 55 55 SUV Hyderabad

56 56 56 SUV Hyderabad

57 57 57 SUV Hyderabad

58 58 58 Luxury Hyderabad

59 59 59 Luxury Hyderabad

60 60 60 Luxury Hyderabad

61 61 61 Luxury Hyderabad

62 62 62 Luxury Hyderabad

63 63 63 Luxury Hyderabad

64 64 64 Luxury Hyderabad

65 65 65 Luxury Hyderabad

66 66 66 Luxury Hyderabad

67 67 67 Luxury Hyderabad

68 68 68 Luxury Hyderabad

69 69 69 Luxury Hyderabad

70 70 70 Luxury Hyderabad

71 71 71 Luxury Hyderabad

72 72 72 Luxury Hyderabad

73 73 73 Luxury Hyderabad

74 74 74 Luxury Hyderabad

75 75 75 Luxury Hyderabad

76 76 76 Luxury Hyderabad

77 77 77 MUV Hyderabad

78 78 78 MUV Hyderabad

79 79 79 MUV Hyderabad

80 80 80 MUV Hyderabad

81 81 81 MUV Hyderabad

82 82 82 MUV Hyderabad

83 83 83 MUV Hyderabad

84 84 84 MUV Hyderabad

85 85 85 MUV Hyderabad

86 86 86 MUV Hyderabad

87 87 87 MUV Hyderabad

88 88 88 MUV Hyderabad

89 89 89 MUV Hyderabad

90 90 90 MUV Hyderabad

91 91 91 MUV Hyderabad

92 92 92 MUV Hyderabad

93 93 93 MUV Hyderabad

94 94 94 MUV Hyderabad

95 95 95 MUV Hyderabad

96 96 96 Minivan Hyderabad

97 97 97 Minivan Hyderabad

98 98 98 Minivan Hyderabad

99 99 99 Minivan Hyderabad

100 100 100 Minivan Hyderabad

101 101 101 Minivan Hyderabad

102 102 102 Minivan Hyderabad

103 103 103 Minivan Hyderabad

104 104 104 Minivan Hyderabad

105 105 105 Minivan Hyderabad

106 106 106 Minivan Hyderabad

107 107 107 Minivan Hyderabad

108 108 108 Minivan Hyderabad

109 109 109 Minivan Hyderabad

110 110 110 Minivan Hyderabad

111 111 111 Minivan Hyderabad

In [138]:
cardekho_5=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                  'Engine':(engine),
                  'Number_of_Owners':(owner),
                  'Transmission':(transmission),
                  'Milaege':(mileage),
                  'Max_Power':(max_power),
                  'Torque':(torque),
                   'Body_Type':(body_type),
                   'Location':(city[5]),
                  'Price':(price)})
cardekho_5

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Engine,Number_of_Owners,Transmission,Milaege,Max_Power,Torque,Body_Type,Location,Price
0,Hyundai,Hyundai Grand i10,1.2 Kappa Asta,2017,Petrol,"25,760",1197,No Of Owner(s)\n1st Owner,Manual,18.9,Max Power\n81.86bhp,Torque\n113.75nm,Hatchback,Hyderabad,588000
1,Maruti,Maruti Ignis,Alpha,2017,Petrol,"19,957",1197,No Of Owner(s)\n1st Owner,Manual,20.89,Max Power\n81.80bhp,Torque\n113Nm,Hatchback,Hyderabad,573500
2,Maruti,Maruti Celerio,ZXI Optional AMT BSIV,2018,Petrol,"14,610",998,No Of Owner(s)\n1st Owner,Automatic,23.1,Max Power\n67.04bhp,Torque\n90Nm,Hatchback,Hyderabad,540000
3,Hyundai,Hyundai i20,1.4 Magna Executive,2017,Diesel,"40,899",1396,No Of Owner(s)\n1st Owner,Manual,22.54,Max Power\n88.73bhp,Torque\n219.7Nm,Hatchback,Hyderabad,608500
4,Maruti,Maruti Swift,AMT VXI,2018,Petrol,"45,536",1197,No Of Owner(s)\n1st Owner,Automatic,22,Max Power\n81.80bhp,Torque\n113Nm,Hatchback,Hyderabad,645000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,Hyundai,Hyundai Santro Sportz AMT BSIV,None,2019,Petrol,"11,262",1086,First Owner,Automatic,20.3,Max Power\n68 bhp,Torque\n99Nm@ 4500rpm,Minivan,Hyderabad,632000
107,Hyundai,Hyundai Grand i10 1.2 CRDi Sportz Option,None,2017,Diesel,"30,946",1186,First Owner,Manual,24.0,Max Power\n73.97 bhp,Torque\n190.24nm@ 1750-2250rpm,Minivan,Hyderabad,616000
108,Hyundai,Hyundai i20 Petrol Asta,None,2018,Petrol,"22,643",1197,First Owner,Manual,18.6,Max Power\n81.86 bhp,Torque\n114.73nm@ 4000rpm,Minivan,Hyderabad,794000
109,Nissan,Nissan Sunny XL D,None,2018,Diesel,"35,013",1461,First Owner,Manual,22.71,Max Power\n84.8 bhp,Torque\n200Nm@ 2000rpm,Minivan,Hyderabad,842000
110,Maruti,Maruti Ciaz VDI SHVS,None,2015,Diesel,"67,213",1248,First Owner,Manual,28.09,Max Power\n88.5 bhp,Torque\n200Nm@ 1750rpm,Minivan,Hyderabad,713000

In [139]:
cardekho_5['Source']='CarDekho'
cardekho_5.to_csv('cardekho5.csv')

In [140]:
model=[]
brand=[]
variant=[]
price=[]
make_year=[]
reg_year=[]
fuel=[]
km=[]
engine=[]
owner=[]
transmission=[]
mileage=[]
max_power=[]
torque=[]
body_type=[]
location=[]

In [141]:
#city 4
for i in range(1):
    for j in range(0,6):
        driver.get(city_url[4])
        for _ in range(100):
            driver.execute_script("window.scrollBy(0,20)")
        body_type_ele=driver.find_elements_by_xpath('//ul[@class="checkBoxWrap bodyTypes cd-bodyTicon"]//li')
        b_type=body_type_ele[j].text
        try:
            driver.implicitly_wait(10)
            ActionChains(driver).move_to_element(body_type_ele[j]).click(body_type_ele[j]).perform()
            
        except ElementNotInteractableException:
            continue
        
        except StaleElementReferenceException:
            continue

        for _ in range(2000):
            driver.execute_script("window.scrollBy(0,20)")

        urls=[]
        url_ele=driver.find_elements_by_xpath('//div[@class="gsc_col-xs-7 carsName"]//a')
        for ele in url_ele:
            try:
                urls.append(ele.get_attribute('href'))
            except StaleElementReferenceException:
                continue
    
        for url in urls:
            driver.get(url)
            for _ in range(50):
                driver.execute_script("window.scrollBy(0,20)")
            try:
                price_ele=driver.find_element_by_xpath('//span[@class="amount"]')
                pr=float(price_ele.text[:-6])
                price.append(int(pr*100000))
                    
                model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1[2]')
                model.append(model_ele.text)
                    
                str=model_ele.text
                for k in range(len(str)):
                    if str[k]==' ':
                        x=k
                        break
                brand.append(str[:x])
                
                info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6"]')
                make_year.append(info_ele[0].text)
                km.append(info_ele[2].text[:-4])
                
                owner.append(info_ele[3].text)
                fuel.append(info_ele[4].text)
                transmission.append(info_ele[5].text)
                mileage.append(info_ele[8].text[8:-5])
                
                if len(info_ele)>8:
                    engine.append(info_ele[9].text[7:-3])
                    
                    if len(info_ele)>=10:
                        max_power.append(info_ele[10].text)
                        torque.append(info_ele[11].text)
                    else:
                        max_power.append(None)
                        torque.append(None)
                    
                else:
                    engine.append(None)
                    max_power.append(None)
                    torque.append(None)
                    
            except NoSuchElementException:
                try:
                    price_ele=driver.find_element_by_xpath('//div[@class="priceSection"]//span[2]')
                    str=price_ele.text
                    price.append(str.replace(',',''))
                
                    model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1')
                    model.append(model_ele.text[5:])
                
                    str=model_ele.text[5:]
                    for k in range(len(str)):
                        if str[k]==' ':
                            x=k
                            break
                    brand.append(str[:x])
                    
                    info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6 gsc_col-md-4"]')
                    make_year.append(info_ele[0].text[10:])
                    fuel.append(info_ele[2].text[5:])
                    km.append(info_ele[3].text[11:-4])
                    engine.append(info_ele[4].text[20:-3])
                    owner.append(info_ele[5].text)
                
                    if len(info_ele)>=12:
                        transmission.append(info_ele[7].text[13:])
                        mileage.append(info_ele[9].text[8:-5])
                        max_power.append(info_ele[11].text)
                        torque.append(info_ele[12].text)
                    else:
                        transmission.append(None)
                        mileage.append(None)
                        max_power.append(None)
                        torque.append(None)
                except NoSuchElementException:
                    continue
    
            try:
                var_ele=driver.find_element_by_xpath('//div[@class="variant-name"]')
                variant.append(var_ele.text)
        
            except NoSuchElementException:
                variant.append(None)
   
            body_type.append(b_type)
            location.append(city[4])
            if len(owner)<len(model):
                owner.append(None)
            print(len(model),len(owner),len(location),b_type,city[4],'\n')

1 1 1 Hatchback Gurgaon

2 2 2 Hatchback Gurgaon

3 3 3 Hatchback Gurgaon

4 4 4 Hatchback Gurgaon

5 5 5 Hatchback Gurgaon

6 6 6 Hatchback Gurgaon

7 7 7 Hatchback Gurgaon

8 8 8 Hatchback Gurgaon

9 9 9 Hatchback Gurgaon

10 10 10 Hatchback Gurgaon

11 11 11 Hatchback Gurgaon

12 12 12 Hatchback Gurgaon

13 13 13 Hatchback Gurgaon

14 14 14 Hatchback Gurgaon

15 15 15 Hatchback Gurgaon

16 16 16 Hatchback Gurgaon

17 17 17 Hatchback Gurgaon

18 18 18 Hatchback Gurgaon

19 19 19 Hatchback Gurgaon

20 20 20 Sedan Gurgaon

21 21 21 Sedan Gurgaon

22 22 22 Sedan Gurgaon

23 23 23 Sedan Gurgaon

24 24 24 Sedan Gurgaon

25 25 25 Sedan Gurgaon

26 26 26 Sedan Gurgaon

27 27 27 Sedan Gurgaon

28 28 28 Sedan Gurgaon

29 29 29 Sedan Gurgaon

30 30 30 Sedan Gurgaon

31 31 31 Sedan Gurgaon

32 32 32 Sedan Gurgaon

33 33 33 Sedan Gurgaon

34 34 34 Sedan Gurgaon

35 35 35 Sedan Gurgaon

36 36 36 Sedan Gurgaon

37 37 37 Sedan Gurgaon

38 38 38 Sedan Gurgaon

39 39 39 Sedan Gurgaon

40 40 40 SUV Gurgaon

41 41 41 SUV Gurgaon

42 42 42 SUV Gurgaon

43 43 43 SUV Gurgaon

44 44 44 SUV Gurgaon

45 45 45 SUV Gurgaon

46 46 46 SUV Gurgaon

47 47 47 SUV Gurgaon

48 48 48 SUV Gurgaon

49 49 49 SUV Gurgaon

50 50 50 SUV Gurgaon

51 51 51 SUV Gurgaon

52 52 52 SUV Gurgaon

53 53 53 SUV Gurgaon

54 54 54 SUV Gurgaon

55 55 55 SUV Gurgaon

56 56 56 SUV Gurgaon

57 57 57 SUV Gurgaon

58 58 58 SUV Gurgaon

59 59 59 SUV Gurgaon

60 60 60 Luxury Gurgaon

61 61 61 Luxury Gurgaon

62 62 62 Luxury Gurgaon

63 63 63 Luxury Gurgaon

64 64 64 Luxury Gurgaon

65 65 65 Luxury Gurgaon

66 66 66 Luxury Gurgaon

67 67 67 Luxury Gurgaon

68 68 68 Luxury Gurgaon

69 69 69 Luxury Gurgaon

70 70 70 Luxury Gurgaon

71 71 71 Luxury Gurgaon

72 72 72 Luxury Gurgaon

73 73 73 Luxury Gurgaon

74 74 74 Luxury Gurgaon

75 75 75 Luxury Gurgaon

76 76 76 Luxury Gurgaon

77 77 77 Luxury Gurgaon

78 78 78 Luxury Gurgaon

79 79 79 Luxury Gurgaon

80 80 80 MUV Gurgaon

81 81 81 MUV Gurgaon

82 82 82 MUV Gurgaon

83 83 83 MUV Gurgaon

84 84 84 MUV Gurgaon

85 85 85 MUV Gurgaon

86 86 86 MUV Gurgaon

87 87 87 MUV Gurgaon

88 88 88 MUV Gurgaon

89 89 89 MUV Gurgaon

90 90 90 MUV Gurgaon

91 91 91 MUV Gurgaon

92 92 92 MUV Gurgaon

93 93 93 MUV Gurgaon

94 94 94 MUV Gurgaon

95 95 95 MUV Gurgaon

96 96 96 MUV Gurgaon

97 97 97 MUV Gurgaon

98 98 98 MUV Gurgaon

99 99 99 MUV Gurgaon

100 100 100 Minivan Gurgaon

101 101 101 Minivan Gurgaon

102 102 102 Minivan Gurgaon

103 103 103 Minivan Gurgaon

104 104 104 Minivan Gurgaon

105 105 105 Minivan Gurgaon

106 106 106 Minivan Gurgaon

107 107 107 Minivan Gurgaon

108 108 108 Minivan Gurgaon

109 109 109 Minivan Gurgaon

110 110 110 Minivan Gurgaon

In [142]:
cardekho_4=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                  'Engine':(engine),
                  'Number_of_Owners':(owner),
                  'Transmission':(transmission),
                  'Milaege':(mileage),
                  'Max_Power':(max_power),
                  'Torque':(torque),
                   'Body_Type':(body_type),
                   'Location':(city[4]),
                  'Price':(price)})
cardekho_4

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Engine,Number_of_Owners,Transmission,Milaege,Max_Power,Torque,Body_Type,Location,Price
0,Toyota,Toyota Etios Cross,1.2L G,2015,Petrol,"35,717",1197,No Of Owner(s)\n1st Owner,Manual,18.16,Max Power\n78.8bhp,Torque\n104Nm,Hatchback,Gurgaon,412855
1,Tata,Tata Tiago,1.2 Revotron XZ,2019,Petrol,"18,833",1199,No Of Owner(s)\n1st Owner,Manual,23.84,Max Power\n84bhp,Torque\n114Nm,Hatchback,Gurgaon,500000
2,Maruti,Maruti Wagon R,VXI AMT,2017,Petrol,"55,892",998,No Of Owner(s)\n1st Owner,Automatic,21.79,Max Power\n67.05bhp,Torque\n90Nm,Hatchback,Gurgaon,383000
3,Honda,Honda Jazz,V CVT,2016,Petrol,"21,369",1199,No Of Owner(s)\n1st Owner,Automatic,17.1,Max Power\n88.50bhp,Torque\n110Nm,Hatchback,Gurgaon,594000
4,Maruti,Maruti Baleno,Delta,2018,Petrol,"34,377",1197,No Of Owner(s)\n1st Owner,Manual,21.01,Max Power\n81.80bhp,Torque\n113Nm,Hatchback,Gurgaon,563870
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,Maruti,Maruti Eeco,CNG 5 Seater AC,2016,CNG,"14,342",1196,No Of Owner(s)\n1st Owner,Manual,20.88,Max Power\n61.7bhp,Torque\n85Nm,Minivan,Gurgaon,294500
106,Maruti,Maruti Eeco,5 STR With AC Plus HTR CNG,2019,CNG,"75,659",1196,No Of Owner(s)\n1st Owner,Manual,15.1,Max Power\n73bhp,Torque\n101Nm,Minivan,Gurgaon,370500
107,Maruti,Maruti Eeco 5 Seater AC BSIV,None,2019,Petrol,"34,000",1196,First Owner,Manual,15.37,Max Power\n73 bhp,Torque\n101Nm@ 3000rpm,Minivan,Gurgaon,350000
108,Maruti,Maruti Omni E MPI STD BS IV,None,2014,Petrol,"95,000",796,First Owner,Manual,16.8,Max Power\n34.2 bhp,Torque\n59Nm@ 2500rpm,Minivan,Gurgaon,114999
109,Maruti,Maruti Eeco 5 STR With AC Plus HTR CNG,None,2015,CNG,"55,000",1196,Second Owner,Manual,15.1,Max Power\n73 bhp,Torque\n101Nm@ 3000rpm,Minivan,Gurgaon,310000

In [143]:
cardekho_4['Source']='CarDekho'
cardekho_4.to_csv('cardekho4.csv')

In [144]:
model=[]
brand=[]
variant=[]
price=[]
make_year=[]
reg_year=[]
fuel=[]
km=[]
engine=[]
owner=[]
transmission=[]
mileage=[]
max_power=[]
torque=[]
body_type=[]
location=[]

In [145]:
#city 3
for i in range(1):
    for j in range(0,6):
        driver.get(city_url[3])
        for _ in range(100):
            driver.execute_script("window.scrollBy(0,20)")
        body_type_ele=driver.find_elements_by_xpath('//ul[@class="checkBoxWrap bodyTypes cd-bodyTicon"]//li')
        b_type=body_type_ele[j].text
        try:
            driver.implicitly_wait(10)
            ActionChains(driver).move_to_element(body_type_ele[j]).click(body_type_ele[j]).perform()
            
        except ElementNotInteractableException:
            continue
        
        except StaleElementReferenceException:
            continue

        for _ in range(2000):
            driver.execute_script("window.scrollBy(0,20)")

        urls=[]
        url_ele=driver.find_elements_by_xpath('//div[@class="gsc_col-xs-7 carsName"]//a')
        for ele in url_ele:
            try:
                urls.append(ele.get_attribute('href'))
            except StaleElementReferenceException:
                continue
    
        for url in urls:
            driver.get(url)
            for _ in range(50):
                driver.execute_script("window.scrollBy(0,20)")
            try:
                price_ele=driver.find_element_by_xpath('//span[@class="amount"]')
                pr=float(price_ele.text[:-6])
                price.append(int(pr*100000))
                    
                model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1[2]')
                model.append(model_ele.text)
                    
                str=model_ele.text
                for k in range(len(str)):
                    if str[k]==' ':
                        x=k
                        break
                brand.append(str[:x])
                
                info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6"]')
                make_year.append(info_ele[0].text)
                km.append(info_ele[2].text[:-4])
                
                owner.append(info_ele[3].text)
                fuel.append(info_ele[4].text)
                transmission.append(info_ele[5].text)
                mileage.append(info_ele[8].text[8:-5])
                
                if len(info_ele)>8:
                    engine.append(info_ele[9].text[7:-3])
                    
                    if len(info_ele)>=10:
                        max_power.append(info_ele[10].text)
                        torque.append(info_ele[11].text)
                    else:
                        max_power.append(None)
                        torque.append(None)
                    
                else:
                    engine.append(None)
                    max_power.append(None)
                    torque.append(None)
                    
            except NoSuchElementException:
                try:
                    price_ele=driver.find_element_by_xpath('//div[@class="priceSection"]//span[2]')
                    str=price_ele.text
                    price.append(str.replace(',',''))
                
                    model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1')
                    model.append(model_ele.text[5:])
                
                    str=model_ele.text[5:]
                    for k in range(len(str)):
                        if str[k]==' ':
                            x=k
                            break
                    brand.append(str[:x])
                    
                    info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6 gsc_col-md-4"]')
                    make_year.append(info_ele[0].text[10:])
                    fuel.append(info_ele[2].text[5:])
                    km.append(info_ele[3].text[11:-4])
                    engine.append(info_ele[4].text[20:-3])
                    owner.append(info_ele[5].text)
                
                    if len(info_ele)>=12:
                        transmission.append(info_ele[7].text[13:])
                        mileage.append(info_ele[9].text[8:-5])
                        max_power.append(info_ele[11].text)
                        torque.append(info_ele[12].text)
                    else:
                        transmission.append(None)
                        mileage.append(None)
                        max_power.append(None)
                        torque.append(None)
                except NoSuchElementException:
                    continue
    
            try:
                var_ele=driver.find_element_by_xpath('//div[@class="variant-name"]')
                variant.append(var_ele.text)
        
            except NoSuchElementException:
                variant.append(None)
   
            body_type.append(b_type)
            location.append(city[3])
            if len(owner)<len(model):
                owner.append(None)
            print(len(model),len(owner),len(location),b_type,city[3],'\n')

1 1 1 Hatchback Delhi NCR

2 2 2 Hatchback Delhi NCR

3 3 3 Hatchback Delhi NCR

4 4 4 Hatchback Delhi NCR

5 5 5 Hatchback Delhi NCR

6 6 6 Hatchback Delhi NCR

7 7 7 Hatchback Delhi NCR

8 8 8 Hatchback Delhi NCR

9 9 9 Hatchback Delhi NCR

10 10 10 Hatchback Delhi NCR

11 11 11 Hatchback Delhi NCR

12 12 12 Hatchback Delhi NCR

13 13 13 Hatchback Delhi NCR

14 14 14 Hatchback Delhi NCR

15 15 15 Hatchback Delhi NCR

16 16 16 Hatchback Delhi NCR

17 17 17 Hatchback Delhi NCR

18 18 18 Hatchback Delhi NCR

19 19 19 Sedan Delhi NCR

20 20 20 Sedan Delhi NCR

21 21 21 Sedan Delhi NCR

22 22 22 Sedan Delhi NCR

23 23 23 Sedan Delhi NCR

24 24 24 Sedan Delhi NCR

25 25 25 Sedan Delhi NCR

26 26 26 Sedan Delhi NCR

27 27 27 Sedan Delhi NCR

28 28 28 Sedan Delhi NCR

29 29 29 Sedan Delhi NCR

30 30 30 Sedan Delhi NCR

31 31 31 Sedan Delhi NCR

32 32 32 Sedan Delhi NCR

33 33 33 Sedan Delhi NCR

34 34 34 Sedan Delhi NCR

35 35 35 Sedan Delhi NCR

36 36 36 Sedan Delhi NCR

37 37 37 Sedan Delhi NCR

38 38 38 SUV Delhi NCR

39 39 39 SUV Delhi NCR

40 40 40 SUV Delhi NCR

41 41 41 SUV Delhi NCR

42 42 42 SUV Delhi NCR

43 43 43 SUV Delhi NCR

44 44 44 SUV Delhi NCR

45 45 45 SUV Delhi NCR

46 46 46 SUV Delhi NCR

47 47 47 SUV Delhi NCR

48 48 48 SUV Delhi NCR

49 49 49 SUV Delhi NCR

50 50 50 SUV Delhi NCR

51 51 51 SUV Delhi NCR

52 52 52 SUV Delhi NCR

53 53 53 SUV Delhi NCR

54 54 54 SUV Delhi NCR

55 55 55 SUV Delhi NCR

56 56 56 SUV Delhi NCR

57 57 57 Luxury Delhi NCR

58 58 58 Luxury Delhi NCR

59 59 59 Luxury Delhi NCR

60 60 60 Luxury Delhi NCR

61 61 61 Luxury Delhi NCR

62 62 62 Luxury Delhi NCR

63 63 63 Luxury Delhi NCR

64 64 64 Luxury Delhi NCR

65 65 65 Luxury Delhi NCR

66 66 66 Luxury Delhi NCR

67 67 67 Luxury Delhi NCR

68 68 68 Luxury Delhi NCR

69 69 69 Luxury Delhi NCR

70 70 70 Luxury Delhi NCR

71 71 71 Luxury Delhi NCR

72 72 72 Luxury Delhi NCR

73 73 73 Luxury Delhi NCR

74 74 74 MUV Delhi NCR

75 75 75 MUV Delhi NCR

76 76 76 MUV Delhi NCR

77 77 77 MUV Delhi NCR

78 78 78 MUV Delhi NCR

79 79 79 MUV Delhi NCR

80 80 80 MUV Delhi NCR

81 81 81 MUV Delhi NCR

82 82 82 MUV Delhi NCR

83 83 83 MUV Delhi NCR

84 84 84 MUV Delhi NCR

85 85 85 MUV Delhi NCR

86 86 86 MUV Delhi NCR

87 87 87 MUV Delhi NCR

88 88 88 MUV Delhi NCR

89 89 89 MUV Delhi NCR

90 90 90 MUV Delhi NCR

91 91 91 MUV Delhi NCR

92 92 92 MUV Delhi NCR

93 93 93 Minivan Delhi NCR

94 94 94 Minivan Delhi NCR

95 95 95 Minivan Delhi NCR

96 96 96 Minivan Delhi NCR

97 97 97 Minivan Delhi NCR

98 98 98 Minivan Delhi NCR

99 99 99 Minivan Delhi NCR

100 100 100 Minivan Delhi NCR

101 101 101 Minivan Delhi NCR

102 102 102 Minivan Delhi NCR

103 103 103 Minivan Delhi NCR

104 104 104 Minivan Delhi NCR

105 105 105 Minivan Delhi NCR

106 106 106 Minivan Delhi NCR

107 107 107 Minivan Delhi NCR

108 108 108 Minivan Delhi NCR

109 109 109 Minivan Delhi NCR

110 110 110 Minivan Delhi NCR

111 111 111 Minivan Delhi NCR

In [146]:
cardekho_3=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                  'Engine':(engine),
                  'Number_of_Owners':(owner),
                  'Transmission':(transmission),
                  'Milaege':(mileage),
                  'Max_Power':(max_power),
                  'Torque':(torque),
                   'Body_Type':(body_type),
                   'Location':(city[3]),
                  'Price':(price)})
cardekho_3

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Engine,Number_of_Owners,Transmission,Milaege,Max_Power,Torque,Body_Type,Location,Price
0,Tata,Tata Tiago,1.2 Revotron XZ,2019,Petrol,"18,833",1199,No Of Owner(s)\n1st Owner,Manual,23.84,Max Power\n84bhp,Torque\n114Nm,Hatchback,Delhi NCR,500000
1,Maruti,Maruti Wagon R,VXI AMT,2017,Petrol,"55,892",998,No Of Owner(s)\n1st Owner,Automatic,21.79,Max Power\n67.05bhp,Torque\n90Nm,Hatchback,Delhi NCR,383000
2,Honda,Honda Jazz,V CVT,2016,Petrol,"21,369",1199,No Of Owner(s)\n1st Owner,Automatic,17.1,Max Power\n88.50bhp,Torque\n110Nm,Hatchback,Delhi NCR,594000
3,Toyota,Toyota Etios Cross,1.2L G,2015,Petrol,"35,717",1197,No Of Owner(s)\n1st Owner,Manual,18.16,Max Power\n78.8bhp,Torque\n104Nm,Hatchback,Delhi NCR,412855
4,Maruti,Maruti Swift,LXI BSIV,2015,Petrol,"79,620",1197,No Of Owner(s)\n1st Owner,Manual,22,Max Power\n81.80bhp,Torque\n113Nm,Hatchback,Delhi NCR,368500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,Maruti,Maruti Swift VDI,None,2014,Diesel,"1,19,653",1248,First Owner,Manual,28.4,Max Power\n74 bhp,Torque\n190Nm@ 2000rpm,Minivan,Delhi NCR,335000
107,Maruti,Maruti Swift Dzire VDi,None,2012,Diesel,"92,819",1248,First Owner,Manual,19.3,Max Power\n73.9 bhp,Torque\n190Nm@ 2000rpm,Minivan,Delhi NCR,303000
108,Toyota,Toyota Etios Cross 1.4L VD,None,2014,Diesel,"1,68,945",1364,First Owner,Manual,23.59,Max Power\n67.06 bhp,Torque\n170Nm@ 1800-2400rpm,Minivan,Delhi NCR,328000
109,Volkswagen,Volkswagen Polo Diesel Comfortline 1.2L,None,2013,Diesel,"1,00,232",1199,First Owner,Manual,22.07,Max Power\n73.9 bhp,Torque\n180Nm@ 2000rpm,Minivan,Delhi NCR,242000
110,Volkswagen,Volkswagen Polo 2015-2019 GT 1.5 TDI,None,2015,Diesel,"1,87,721",1498,First Owner,Manual,21.49,Max Power\n108.5 bhp,Torque\n250nm@ 1500-3000rpm,Minivan,Delhi NCR,336000

In [147]:
cardekho_3['Source']='CarDekho'
cardekho_3.to_csv('cardekho3.csv')

In [148]:
model=[]
brand=[]
variant=[]
price=[]
make_year=[]
reg_year=[]
fuel=[]
km=[]
engine=[]
owner=[]
transmission=[]
mileage=[]
max_power=[]
torque=[]
body_type=[]
location=[]

In [149]:
#city 2
for i in range(1):
    for j in range(0,6):
        driver.get(city_url[2])
        for _ in range(100):
            driver.execute_script("window.scrollBy(0,20)")
        body_type_ele=driver.find_elements_by_xpath('//ul[@class="checkBoxWrap bodyTypes cd-bodyTicon"]//li')
        b_type=body_type_ele[j].text
        try:
            driver.implicitly_wait(10)
            ActionChains(driver).move_to_element(body_type_ele[j]).click(body_type_ele[j]).perform()
            
        except ElementNotInteractableException:
            continue
        
        except StaleElementReferenceException:
            continue

        for _ in range(2000):
            driver.execute_script("window.scrollBy(0,20)")

        urls=[]
        url_ele=driver.find_elements_by_xpath('//div[@class="gsc_col-xs-7 carsName"]//a')
        for ele in url_ele:
            try:
                urls.append(ele.get_attribute('href'))
            except StaleElementReferenceException:
                continue
    
        for url in urls:
            driver.get(url)
            for _ in range(50):
                driver.execute_script("window.scrollBy(0,20)")
            try:
                price_ele=driver.find_element_by_xpath('//span[@class="amount"]')
                pr=float(price_ele.text[:-6])
                price.append(int(pr*100000))
                    
                model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1[2]')
                model.append(model_ele.text)
                    
                str=model_ele.text
                for k in range(len(str)):
                    if str[k]==' ':
                        x=k
                        break
                brand.append(str[:x])
                
                info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6"]')
                make_year.append(info_ele[0].text)
                km.append(info_ele[2].text[:-4])
                
                owner.append(info_ele[3].text)
                fuel.append(info_ele[4].text)
                transmission.append(info_ele[5].text)
                mileage.append(info_ele[8].text[8:-5])
                
                if len(info_ele)>8:
                    engine.append(info_ele[9].text[7:-3])
                    
                    if len(info_ele)>=10:
                        max_power.append(info_ele[10].text)
                        torque.append(info_ele[11].text)
                    else:
                        max_power.append(None)
                        torque.append(None)
                    
                else:
                    engine.append(None)
                    max_power.append(None)
                    torque.append(None)
                    
            except NoSuchElementException:
                try:
                    price_ele=driver.find_element_by_xpath('//div[@class="priceSection"]//span[2]')
                    str=price_ele.text
                    price.append(str.replace(',',''))
                
                    model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1')
                    model.append(model_ele.text[5:])
                
                    str=model_ele.text[5:]
                    for k in range(len(str)):
                        if str[k]==' ':
                            x=k
                            break
                    brand.append(str[:x])
                    
                    info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6 gsc_col-md-4"]')
                    make_year.append(info_ele[0].text[10:])
                    fuel.append(info_ele[2].text[5:])
                    km.append(info_ele[3].text[11:-4])
                    engine.append(info_ele[4].text[20:-3])
                    owner.append(info_ele[5].text)
                
                    if len(info_ele)>=12:
                        transmission.append(info_ele[7].text[13:])
                        mileage.append(info_ele[9].text[8:-5])
                        max_power.append(info_ele[11].text)
                        torque.append(info_ele[12].text)
                    else:
                        transmission.append(None)
                        mileage.append(None)
                        max_power.append(None)
                        torque.append(None)
                except NoSuchElementException:
                    continue
    
            try:
                var_ele=driver.find_element_by_xpath('//div[@class="variant-name"]')
                variant.append(var_ele.text)
        
            except NoSuchElementException:
                variant.append(None)
   
            body_type.append(b_type)
            location.append(city[2])
            if len(owner)<len(model):
                owner.append(None)
            print(len(model),len(owner),len(location),b_type,city[2],'\n')

1 1 1 Hatchback Chennai

2 2 2 Hatchback Chennai

3 3 3 Hatchback Chennai

4 4 4 Hatchback Chennai

5 5 5 Hatchback Chennai

6 6 6 Hatchback Chennai

7 7 7 Hatchback Chennai

8 8 8 Hatchback Chennai

9 9 9 Hatchback Chennai

10 10 10 Hatchback Chennai

11 11 11 Hatchback Chennai

12 12 12 Hatchback Chennai

13 13 13 Hatchback Chennai

14 14 14 Hatchback Chennai

15 15 15 Hatchback Chennai

16 16 16 Hatchback Chennai

17 17 17 Hatchback Chennai

18 18 18 Hatchback Chennai

19 19 19 Hatchback Chennai

20 20 20 Hatchback Chennai

21 21 21 Sedan Chennai

22 22 22 Sedan Chennai

23 23 23 Sedan Chennai

24 24 24 Sedan Chennai

25 25 25 Sedan Chennai

26 26 26 Sedan Chennai

27 27 27 Sedan Chennai

28 28 28 Sedan Chennai

29 29 29 Sedan Chennai

30 30 30 Sedan Chennai

31 31 31 Sedan Chennai

32 32 32 Sedan Chennai

33 33 33 Sedan Chennai

34 34 34 Sedan Chennai

35 35 35 Sedan Chennai

36 36 36 Sedan Chennai

37 37 37 Sedan Chennai

38 38 38 Sedan Chennai

39 39 39 Sedan Chennai

40 40 40 Sedan Chennai

41 41 41 SUV Chennai

42 42 42 SUV Chennai

43 43 43 SUV Chennai

44 44 44 SUV Chennai

45 45 45 SUV Chennai

46 46 46 SUV Chennai

47 47 47 SUV Chennai

48 48 48 SUV Chennai

49 49 49 SUV Chennai

50 50 50 SUV Chennai

51 51 51 SUV Chennai

52 52 52 SUV Chennai

53 53 53 SUV Chennai

54 54 54 SUV Chennai

55 55 55 SUV Chennai

56 56 56 SUV Chennai

57 57 57 SUV Chennai

58 58 58 SUV Chennai

59 59 59 SUV Chennai

60 60 60 SUV Chennai

61 61 61 MUV Chennai

62 62 62 MUV Chennai

63 63 63 MUV Chennai

64 64 64 MUV Chennai

65 65 65 MUV Chennai

66 66 66 MUV Chennai

67 67 67 MUV Chennai

68 68 68 MUV Chennai

69 69 69 MUV Chennai

70 70 70 MUV Chennai

71 71 71 MUV Chennai

72 72 72 MUV Chennai

73 73 73 MUV Chennai

74 74 74 MUV Chennai

75 75 75 MUV Chennai

76 76 76 MUV Chennai

77 77 77 MUV Chennai

78 78 78 MUV Chennai

79 79 79 MUV Chennai

80 80 80 MUV Chennai

81 81 81 Luxury Chennai

82 82 82 Luxury Chennai

83 83 83 Luxury Chennai

84 84 84 Luxury Chennai

85 85 85 Luxury Chennai

86 86 86 Luxury Chennai

87 87 87 Luxury Chennai

88 88 88 Luxury Chennai

89 89 89 Luxury Chennai

90 90 90 Luxury Chennai

91 91 91 Luxury Chennai

92 92 92 Luxury Chennai

93 93 93 Luxury Chennai

94 94 94 Luxury Chennai

95 95 95 Luxury Chennai

96 96 96 Luxury Chennai

97 97 97 Luxury Chennai

98 98 98 Luxury Chennai

99 99 99 Luxury Chennai

100 100 100 Luxury Chennai

101 101 101 Minivan Chennai

102 102 102 Minivan Chennai

103 103 103 Minivan Chennai

104 104 104 Minivan Chennai

105 105 105 Minivan Chennai

106 106 106 Minivan Chennai

107 107 107 Minivan Chennai

108 108 108 Minivan Chennai

109 109 109 Minivan Chennai

110 110 110 Minivan Chennai

111 111 111 Minivan Chennai

112 112 112 Minivan Chennai

113 113 113 Minivan Chennai

114 114 114 Minivan Chennai

115 115 115 Minivan Chennai

116 116 116 Minivan Chennai

In [150]:
cardekho_2=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                  'Engine':(engine),
                  'Number_of_Owners':(owner),
                  'Transmission':(transmission),
                  'Milaege':(mileage),
                  'Max_Power':(max_power),
                  'Torque':(torque),
                   'Body_Type':(body_type),
                   'Location':(city[2]),
                  'Price':(price)})
cardekho_2

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Engine,Number_of_Owners,Transmission,Milaege,Max_Power,Torque,Body_Type,Location,Price
0,Fiat,Fiat Grande Punto 1.3 Dynamic (Diesel),None,2013,Diesel,"68,803",1248,First Owner,Manual,20.3,Max Power\n75 bhp,Torque\n197Nm@ 1750rpm,Hatchback,Chennai,350000
1,Volkswagen,Volkswagen Polo 2015-2019 1.0 MPI Highline Plus,None,2018,Petrol,"35,000",999,First Owner,Manual,18.78,Max Power\n75 bhp,Torque\n95Nm@ 3000-4300rpm,Hatchback,Chennai,690000
2,Ford,Ford Figo Petrol EXI,None,2013,Petrol,"32,000",1196,First Owner,Manual,15.6,Max Power\n70 bhp,Torque\n102Nm@ 4000rpm,Hatchback,Chennai,295000
3,Maruti,Maruti Baleno Zeta 1.2,None,2018,Petrol,"34,000",1197,First Owner,Manual,21.4,Max Power\n83.1 bhp,Torque\n115Nm@ 4000rpm,Hatchback,Chennai,690000
4,Honda,Honda Jazz V Diesel,None,2018,Diesel,"29,055",1498,First Owner,Manual,27.3,Max Power\n98.6 bhp,Torque\n200Nm@ 1750rpm,Hatchback,Chennai,750000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,Maruti,Maruti Omni 5 Seater BSIV,None,2001,Petrol,"37,539",796,Third Owner,Manual,14.0,Max Power\n35 bhp,Torque\n6.1kgm@ 3000rpm,Minivan,Chennai,800000
112,Maruti,Maruti Versa DX2 8-SEATER BSIII TWIN A/C,None,2005,Petrol,"96,000",1298,First Owner,Manual,11.3,Max Power\n83.1 bhp,"Torque\n10.4@ 3,000(kgm@ rpm)",Minivan,Chennai,150000
113,Maruti,Maruti Omni 5 Seater,None,2006,Petrol,"70,000",796,Second Owner,Manual,14.0,Max Power\n35 bhp,Torque\n6.1kgm@ 3000rpm,Minivan,Chennai,110000
114,Maruti,Maruti Eeco 7 Seater Standard BSIV,None,2012,Petrol,"70,000",1196,First Owner,Manual,15.37,Max Power\n73 bhp,Torque\n101Nm@ 3000rpm,Minivan,Chennai,210000
115,Toyota,Toyota Innova Crysta 2016-2020 2.4 ZX AT,None,2020,Diesel,"2,500",2393,First Owner,Automatic,13.68,Max Power\n147.51 bhp,Torque\n360Nm@ 1400-2600rpm,Minivan,Chennai,2800000

In [151]:
cardekho_2['Source']='CarDekho'
cardekho_2.to_csv('cardekho2.csv')

In [152]:
model=[]
brand=[]
variant=[]
price=[]
make_year=[]
reg_year=[]
fuel=[]
km=[]
engine=[]
owner=[]
transmission=[]
mileage=[]
max_power=[]
torque=[]
body_type=[]
location=[]

In [153]:
#city 1
for i in range(1):
    for j in range(0,6):
        driver.get(city_url[1])
        for _ in range(100):
            driver.execute_script("window.scrollBy(0,20)")
        body_type_ele=driver.find_elements_by_xpath('//ul[@class="checkBoxWrap bodyTypes cd-bodyTicon"]//li')
        b_type=body_type_ele[j].text
        try:
            driver.implicitly_wait(10)
            ActionChains(driver).move_to_element(body_type_ele[j]).click(body_type_ele[j]).perform()
            
        except ElementNotInteractableException:
            continue
        
        except StaleElementReferenceException:
            continue

        for _ in range(2000):
            driver.execute_script("window.scrollBy(0,20)")

        urls=[]
        url_ele=driver.find_elements_by_xpath('//div[@class="gsc_col-xs-7 carsName"]//a')
        for ele in url_ele:
            try:
                urls.append(ele.get_attribute('href'))
            except StaleElementReferenceException:
                continue
    
        for url in urls:
            driver.get(url)
            for _ in range(50):
                driver.execute_script("window.scrollBy(0,20)")
            try:
                price_ele=driver.find_element_by_xpath('//span[@class="amount"]')
                pr=float(price_ele.text[:-6])
                price.append(int(pr*100000))
                    
                model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1[2]')
                model.append(model_ele.text)
                    
                str=model_ele.text
                for k in range(len(str)):
                    if str[k]==' ':
                        x=k
                        break
                brand.append(str[:x])
                
                info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6"]')
                make_year.append(info_ele[0].text)
                km.append(info_ele[2].text[:-4])
                
                owner.append(info_ele[3].text)
                fuel.append(info_ele[4].text)
                transmission.append(info_ele[5].text)
                mileage.append(info_ele[8].text[8:-5])
                
                if len(info_ele)>8:
                    engine.append(info_ele[9].text[7:-3])
                    
                    if len(info_ele)>=10:
                        max_power.append(info_ele[10].text)
                        torque.append(info_ele[11].text)
                    else:
                        max_power.append(None)
                        torque.append(None)
                    
                else:
                    engine.append(None)
                    max_power.append(None)
                    torque.append(None)
                    
            except NoSuchElementException:
                try:
                    price_ele=driver.find_element_by_xpath('//div[@class="priceSection"]//span[2]')
                    str=price_ele.text
                    price.append(str.replace(',',''))
                
                    model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1')
                    model.append(model_ele.text[5:])
                
                    str=model_ele.text[5:]
                    for k in range(len(str)):
                        if str[k]==' ':
                            x=k
                            break
                    brand.append(str[:x])
                    
                    info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6 gsc_col-md-4"]')
                    make_year.append(info_ele[0].text[10:])
                    fuel.append(info_ele[2].text[5:])
                    km.append(info_ele[3].text[11:-4])
                    engine.append(info_ele[4].text[20:-3])
                    owner.append(info_ele[5].text)
                
                    if len(info_ele)>=12:
                        transmission.append(info_ele[7].text[13:])
                        mileage.append(info_ele[9].text[8:-5])
                        max_power.append(info_ele[11].text)
                        torque.append(info_ele[12].text)
                    else:
                        transmission.append(None)
                        mileage.append(None)
                        max_power.append(None)
                        torque.append(None)
                except NoSuchElementException:
                    continue
    
            try:
                var_ele=driver.find_element_by_xpath('//div[@class="variant-name"]')
                variant.append(var_ele.text)
        
            except NoSuchElementException:
                variant.append(None)
   
            body_type.append(b_type)
            location.append(city[1])
            if len(owner)<len(model):
                owner.append(None)
            print(len(model),len(owner),len(location),b_type,city[1],'\n')

1 1 1 Hatchback Bangalore

2 2 2 Hatchback Bangalore

3 3 3 Hatchback Bangalore

4 4 4 Hatchback Bangalore

5 5 5 Hatchback Bangalore

6 6 6 Hatchback Bangalore

7 7 7 Hatchback Bangalore

8 8 8 Hatchback Bangalore

9 9 9 Hatchback Bangalore

10 10 10 Hatchback Bangalore

11 11 11 Hatchback Bangalore

12 12 12 Hatchback Bangalore

13 13 13 Hatchback Bangalore

14 14 14 Hatchback Bangalore

15 15 15 Hatchback Bangalore

16 16 16 Hatchback Bangalore

17 17 17 Hatchback Bangalore

18 18 18 Hatchback Bangalore

19 19 19 Hatchback Bangalore

20 20 20 Hatchback Bangalore

21 21 21 Sedan Bangalore

22 22 22 Sedan Bangalore

23 23 23 Sedan Bangalore

24 24 24 Sedan Bangalore

25 25 25 Sedan Bangalore

26 26 26 Sedan Bangalore

27 27 27 Sedan Bangalore

28 28 28 Sedan Bangalore

29 29 29 Sedan Bangalore

30 30 30 Sedan Bangalore

31 31 31 Sedan Bangalore

32 32 32 Sedan Bangalore

33 33 33 Sedan Bangalore

34 34 34 Sedan Bangalore

35 35 35 Sedan Bangalore

36 36 36 Sedan Bangalore

37 37 37 Sedan Bangalore

38 38 38 Sedan Bangalore

39 39 39 Sedan Bangalore

40 40 40 Sedan Bangalore

41 41 41 SUV Bangalore

42 42 42 SUV Bangalore

43 43 43 SUV Bangalore

44 44 44 SUV Bangalore

45 45 45 SUV Bangalore

46 46 46 SUV Bangalore

47 47 47 SUV Bangalore

48 48 48 SUV Bangalore

49 49 49 SUV Bangalore

50 50 50 SUV Bangalore

51 51 51 SUV Bangalore

52 52 52 SUV Bangalore

53 53 53 SUV Bangalore

54 54 54 SUV Bangalore

55 55 55 SUV Bangalore

56 56 56 SUV Bangalore

57 57 57 SUV Bangalore

58 58 58 SUV Bangalore

59 59 59 SUV Bangalore

60 60 60 SUV Bangalore

61 61 61 Luxury Bangalore

62 62 62 Luxury Bangalore

63 63 63 Luxury Bangalore

64 64 64 Luxury Bangalore

65 65 65 Luxury Bangalore

66 66 66 Luxury Bangalore

67 67 67 Luxury Bangalore

68 68 68 Luxury Bangalore

69 69 69 Luxury Bangalore

70 70 70 Luxury Bangalore

71 71 71 Luxury Bangalore

72 72 72 Luxury Bangalore

73 73 73 Luxury Bangalore

74 74 74 Luxury Bangalore

75 75 75 Luxury Bangalore

76 76 76 Luxury Bangalore

77 77 77 Luxury Bangalore

78 78 78 Luxury Bangalore

79 79 79 Luxury Bangalore

80 80 80 Luxury Bangalore

81 81 81 MUV Bangalore

82 82 82 MUV Bangalore

83 83 83 MUV Bangalore

84 84 84 MUV Bangalore

85 85 85 MUV Bangalore

86 86 86 MUV Bangalore

87 87 87 MUV Bangalore

88 88 88 MUV Bangalore

89 89 89 MUV Bangalore

90 90 90 MUV Bangalore

91 91 91 MUV Bangalore

92 92 92 MUV Bangalore

93 93 93 MUV Bangalore

94 94 94 MUV Bangalore

95 95 95 MUV Bangalore

96 96 96 MUV Bangalore

97 97 97 MUV Bangalore

98 98 98 MUV Bangalore

99 99 99 MUV Bangalore

100 100 100 MUV Bangalore

101 101 101 Minivan Bangalore

102 102 102 Minivan Bangalore

103 103 103 Minivan Bangalore

104 104 104 Minivan Bangalore

105 105 105 Minivan Bangalore

106 106 106 Minivan Bangalore

107 107 107 Minivan Bangalore

108 108 108 Minivan Bangalore

109 109 109 Minivan Bangalore

110 110 110 Minivan Bangalore

111 111 111 Minivan Bangalore

112 112 112 Minivan Bangalore

113 113 113 Minivan Bangalore

114 114 114 Minivan Bangalore

115 115 115 Minivan Bangalore

116 116 116 Minivan Bangalore

117 117 117 Minivan Bangalore

118 118 118 Minivan Bangalore

119 119 119 Minivan Bangalore

120 120 120 Minivan Bangalore

In [154]:
cardekho_1=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                  'Engine':(engine),
                  'Number_of_Owners':(owner),
                  'Transmission':(transmission),
                  'Milaege':(mileage),
                  'Max_Power':(max_power),
                  'Torque':(torque),
                   'Body_Type':(body_type),
                   'Location':(city[1]),
                  'Price':(price)})
cardekho_1

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Engine,Number_of_Owners,Transmission,Milaege,Max_Power,Torque,Body_Type,Location,Price
0,Hyundai,Hyundai EON,Magna Plus,2015,Petrol,"4,924",814,No Of Owner(s)\n1st Owner,Manual,21.1,Max Power\n55.2bhp,Torque\n74.5Nm,Hatchback,Bangalore,347500
1,Maruti,Maruti Celerio,ZXI AMT,2015,Petrol,"50,200",998,No Of Owner(s)\n2nd Owner,Automatic,21.63,Max Power\n67.05bhp,Torque\n90Nm,Hatchback,Bangalore,410000
2,Ford,Ford Figo,Titanium Diesel,2017,Diesel,"5,545",1499,No Of Owner(s)\n1st Owner,Manual,24.4,Max Power\n98.96bhp,Torque\n215Nm,Hatchback,Bangalore,581000
3,Renault,Renault KWID,1.0 RXT Optional,2018,Petrol,"22,912",999,No Of Owner(s)\n1st Owner,Manual,23.01,Max Power\n67bhp,Torque\n91Nm,Hatchback,Bangalore,444500
4,Maruti,Maruti Celerio,VXI AT,2015,Petrol,"29,406",998,No Of Owner(s)\n1st Owner,Automatic,23.1,Max Power\n67.04bhp,Torque\n90Nm,Hatchback,Bangalore,463500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,Audi,Audi A6 2.0 TDI,None,2014,Diesel,"97,021",1968,First Owner,Automatic,17.68,Max Power\n174.33 bhp,Torque\n380Nm@ 1750-2500rpm,Minivan,Bangalore,2275000
116,Tata,Tata Nexon 1.2 Revotron XMA,None,2019,Petrol,"19,000",1198,First Owner,Automatic,17.0,Max Power\n108.5 bhp,Torque\n170Nm@ 1750-4000rpm,Minivan,Bangalore,894999
117,Lexus,Lexus NX 300h,None,2018,Petrol,"7,622",2499,First Owner,Automatic,18.32,Max Power\n194.3 bhp,Torque\n210nm@ 4200-4400rpm,Minivan,Bangalore,6395000
118,Audi,Audi Q5 3.0 TDI,None,2010,Diesel,"80,000",2967,First Owner,Automatic,12.19,Max Power\n236 bhp,Torque\n500Nm@ 1500-3000rpm,Minivan,Bangalore,1250000
119,Audi,Audi Q3 2.0 TDI,None,2013,Diesel,"67,000",1968,Third Owner,Automatic,17.32,Max Power\n150 bhp,Torque\n380Nm@ 1750-2500rpm,Minivan,Bangalore,1350000

In [155]:
cardekho_1['Source']='CarDekho'
cardekho_1.to_csv('cardekho1.csv')

In [8]:
model=[]
brand=[]
variant=[]
price=[]
make_year=[]
fuel=[]
km=[]
engine=[]
owner=[]
transmission=[]
mileage=[]
max_power=[]
torque=[]
body_type=[]
location=[]

In [ ]:
#city 0
for i in range(1):
    for j in range(0,6):
        driver.get(city_url[0])
        for _ in range(100):
            driver.execute_script("window.scrollBy(0,20)")
        body_type_ele=driver.find_elements_by_xpath('//ul[@class="checkBoxWrap bodyTypes cd-bodyTicon"]//li')
        b_type=body_type_ele[j].text
        try:
            driver.implicitly_wait(10)
            ActionChains(driver).move_to_element(body_type_ele[j]).click(body_type_ele[j]).perform()
            
        except ElementNotInteractableException:
            continue
        
        except StaleElementReferenceException:
            continue

        for _ in range(2000):
            driver.execute_script("window.scrollBy(0,20)")

        urls=[]
        url_ele=driver.find_elements_by_xpath('//div[@class="gsc_col-xs-7 carsName"]//a')
        for ele in url_ele:
            try:
                urls.append(ele.get_attribute('href'))
            except StaleElementReferenceException:
                continue
    
        for url in urls:
            driver.get(url)
            for _ in range(50):
                driver.execute_script("window.scrollBy(0,20)")
            try:
                price_ele=driver.find_element_by_xpath('//span[@class="amount"]')
                pr=float(price_ele.text[:-6])
                price.append(int(pr*100000))
                    
                model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1[2]')
                model.append(model_ele.text)
                    
                str=model_ele.text
                for k in range(len(str)):
                    if str[k]==' ':
                        x=k
                        break
                brand.append(str[:x])
                
                info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6"]')
                make_year.append(info_ele[0].text)
                km.append(info_ele[2].text[:-4])
                
                owner.append(info_ele[3].text)
                fuel.append(info_ele[4].text)
                transmission.append(info_ele[5].text)
                mileage.append(info_ele[8].text[8:-5])
                
                if len(info_ele)>8:
                    engine.append(info_ele[9].text[7:-3])
                    
                    if len(info_ele)>=10:
                        max_power.append(info_ele[10].text)
                        torque.append(info_ele[11].text)
                    else:
                        max_power.append(None)
                        torque.append(None)
                    
                else:
                    engine.append(None)
                    max_power.append(None)
                    torque.append(None)
                    
            except NoSuchElementException:
                try:
                    price_ele=driver.find_element_by_xpath('//div[@class="priceSection"]//span[2]')
                    str=price_ele.text
                    price.append(str.replace(',',''))
                
                    model_ele=driver.find_element_by_xpath('//div[@class="gsc_col-xs-12"]//h1')
                    model.append(model_ele.text[5:])
                
                    str=model_ele.text[5:]
                    for k in range(len(str)):
                        if str[k]==' ':
                            x=k
                            break
                    brand.append(str[:x])
                    
                    info_ele=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6 gsc_col-md-4"]')
                    make_year.append(info_ele[0].text[10:])
                    fuel.append(info_ele[2].text[5:])
                    km.append(info_ele[3].text[11:-4])
                    engine.append(info_ele[4].text[20:-3])
                    owner.append(info_ele[5].text)
                
                    if len(info_ele)>=12:
                        transmission.append(info_ele[7].text[13:])
                        mileage.append(info_ele[9].text[8:-5])
                        max_power.append(info_ele[11].text)
                        torque.append(info_ele[12].text)
                    else:
                        transmission.append(None)
                        mileage.append(None)
                        max_power.append(None)
                        torque.append(None)
                except NoSuchElementException:
                    continue
    
            try:
                var_ele=driver.find_element_by_xpath('//div[@class="variant-name"]')
                variant.append(var_ele.text)
        
            except NoSuchElementException:
                variant.append(None)
   
            body_type.append(b_type)
            location.append(city[0])
            if len(owner)<len(model):
                owner.append(None)
            print(len(model),len(owner),len(location),b_type,city[0],'\n')

1 1 1 Sedan Ahmedabad

2 2 2 Sedan Ahmedabad

3 3 3 Sedan Ahmedabad

4 4 4 Sedan Ahmedabad

5 5 5 Sedan Ahmedabad

6 6 6 Sedan Ahmedabad

7 7 7 Sedan Ahmedabad

8 8 8 Sedan Ahmedabad

9 9 9 Sedan Ahmedabad

10 10 10 Sedan Ahmedabad

11 11 11 Sedan Ahmedabad

12 12 12 Sedan Ahmedabad

13 13 13 Sedan Ahmedabad

14 14 14 Sedan Ahmedabad

15 15 15 Sedan Ahmedabad

16 16 16 Sedan Ahmedabad

17 17 17 Sedan Ahmedabad

18 18 18 Sedan Ahmedabad

19 19 19 Sedan Ahmedabad

20 20 20 Sedan Ahmedabad

21 21 21 Sedan Ahmedabad

22 22 22 Sedan Ahmedabad

23 23 23 Sedan Ahmedabad

24 24 24 Sedan Ahmedabad

25 25 25 Sedan Ahmedabad

26 26 26 Sedan Ahmedabad

27 27 27 Sedan Ahmedabad

28 28 28 Sedan Ahmedabad

29 29 29 Sedan Ahmedabad

30 30 30 Sedan Ahmedabad

31 31 31 Sedan Ahmedabad

32 32 32 Sedan Ahmedabad

33 33 33 Sedan Ahmedabad

34 34 34 Sedan Ahmedabad

35 35 35 Sedan Ahmedabad

36 36 36 Sedan Ahmedabad

37 37 37 Sedan Ahmedabad

38 38 38 Sedan Ahmedabad

39 39 39 Sedan Ahmedabad

40 40 40 Sedan Ahmedabad

41 41 41 Sedan Ahmedabad

42 42 42 Sedan Ahmedabad

43 43 43 Sedan Ahmedabad

44 44 44 Sedan Ahmedabad

45 45 45 Sedan Ahmedabad

46 46 46 Sedan Ahmedabad

47 47 47 Sedan Ahmedabad

48 48 48 Sedan Ahmedabad

49 49 49 Sedan Ahmedabad

50 50 50 Sedan Ahmedabad

51 51 51 Sedan Ahmedabad

52 52 52 Sedan Ahmedabad

53 53 53 Sedan Ahmedabad

54 54 54 Sedan Ahmedabad

55 55 55 Sedan Ahmedabad

56 56 56 Sedan Ahmedabad

57 57 57 Sedan Ahmedabad

58 58 58 Sedan Ahmedabad

59 59 59 Sedan Ahmedabad

60 60 60 Sedan Ahmedabad

61 61 61 Sedan Ahmedabad

62 62 62 Sedan Ahmedabad

63 63 63 Sedan Ahmedabad

64 64 64 Sedan Ahmedabad

65 65 65 Sedan Ahmedabad

66 66 66 Sedan Ahmedabad

67 67 67 Sedan Ahmedabad

68 68 68 Sedan Ahmedabad

69 69 69 Sedan Ahmedabad

70 70 70 Sedan Ahmedabad

71 71 71 Sedan Ahmedabad

72 72 72 Sedan Ahmedabad

73 73 73 Sedan Ahmedabad

74 74 74 Sedan Ahmedabad

75 75 75 Sedan Ahmedabad

76 76 76 Sedan Ahmedabad

77 77 77 Sedan Ahmedabad

78 78 78 Sedan Ahmedabad

79 79 79 Sedan Ahmedabad

80 80 80 Sedan Ahmedabad

81 81 81 Sedan Ahmedabad

82 82 82 Sedan Ahmedabad

83 83 83 Sedan Ahmedabad

84 84 84 Sedan Ahmedabad

85 85 85 Sedan Ahmedabad

86 86 86 Sedan Ahmedabad

87 87 87 Sedan Ahmedabad

88 88 88 Sedan Ahmedabad

89 89 89 Sedan Ahmedabad

90 90 90 Sedan Ahmedabad

91 91 91 Sedan Ahmedabad

92 92 92 Sedan Ahmedabad

93 93 93 Sedan Ahmedabad

94 94 94 Sedan Ahmedabad

95 95 95 Sedan Ahmedabad

96 96 96 Sedan Ahmedabad

97 97 97 Sedan Ahmedabad

98 98 98 Sedan Ahmedabad

99 99 99 Sedan Ahmedabad

100 100 100 Sedan Ahmedabad

101 101 101 Sedan Ahmedabad

102 102 102 Sedan Ahmedabad

103 103 103 Sedan Ahmedabad

104 104 104 Sedan Ahmedabad

105 105 105 Sedan Ahmedabad

106 106 106 Sedan Ahmedabad

107 107 107 Sedan Ahmedabad

108 108 108 Sedan Ahmedabad

109 109 109 Sedan Ahmedabad

110 110 110 Sedan Ahmedabad

111 111 111 Sedan Ahmedabad

112 112 112 Sedan Ahmedabad

113 113 113 Sedan Ahmedabad

114 114 114 Sedan Ahmedabad

In [158]:
cardekho_0=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                  'Engine':(engine),
                  'Number_of_Owners':(owner),
                  'Transmission':(transmission),
                  'Milaege':(mileage),
                  'Max_Power':(max_power),
                  'Torque':(torque),
                   'Body_Type':(body_type),
                   'Location':(city[0]),
                  'Price':(price)})
cardekho_0

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Engine,Number_of_Owners,Transmission,Milaege,Max_Power,Torque,Body_Type,Location,Price
0,Maruti,Maruti Alto K10,LXI,2012,Petrol,"89,579",998,No Of Owner(s)\n1st Owner,Manual,20.92,Max Power\n67.1bhp,Torque\n90Nm,Hatchback,Ahmedabad,177500
1,Maruti,Maruti Wagon R,VXI,2016,Petrol,"81,674",998,No Of Owner(s)\n1st Owner,Manual,21.79,Max Power\n67.05bhp,Torque\n90Nm,Hatchback,Ahmedabad,360000
2,Maruti,Maruti S-Presso,VXI,2019,Petrol,"24,230",998,No Of Owner(s)\n1st Owner,Manual,21.7,Max Power\n67.05bhp,Torque\n90nm,Hatchback,Ahmedabad,422000
3,Maruti,Maruti Swift,VDI,2018,Diesel,"31,694",1248,No Of Owner(s)\n1st Owner,Manual,28.4,Max Power\n74bhp,Torque\n190Nm,Hatchback,Ahmedabad,585000
4,Maruti,Maruti Baleno,Alpha,2017,Petrol,"49,072",1197,No Of Owner(s)\n1st Owner,Manual,21.01,Max Power\n81.80bhp,Torque\n113Nm,Hatchback,Ahmedabad,610000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,Ford,Ford EcoSport 1.5 Diesel Trend,None,2015,Diesel,"49,000",1498,First Owner,Manual,21.7,Max Power\n98.96 bhp,Torque\n215Nm@ 1750-2500rpm,Minivan,Ahmedabad,515000
115,Maruti,Maruti Alto 800 LXI,None,2018,Petrol,"41,000",796,First Owner,Manual,24.7,Max Power\n47.3 bhp,Torque\n69Nm@ 3500rpm,Minivan,Ahmedabad,345000
116,Tata,Tata Tiago Wizz 1.2 Revotron,None,2017,Petrol,"59,000",1199,First Owner,Manual,23.84,Max Power\n84 bhp,Torque\n114Nm@ 3500rpm,Minivan,Ahmedabad,474000
117,Hyundai,Hyundai EON D Lite Plus,None,2013,Petrol,"52,000",814,First Owner,Manual,21.1,Max Power\n55.2 bhp,Torque\n74.5Nm@ 4000rpm,Minivan,Ahmedabad,264000
118,Volvo,Volvo XC 90 3.2 AWD,None,2008,Petrol,"51,000",3192,First Owner,Automatic,8.3,Max Power\n200 bhp,Torque\n420Nm@ 3200rpm,Minivan,Ahmedabad,789000

In [159]:
cardekho_0['Source']='CarDekho'
cardekho_0.to_csv('cardekho0.csv')

In [160]:
#len(max_power),len(torque),len(location),len(body_type),len(variant),len(model)

max_power.append(None)
torque.append(None)
location.append('New Delhi')
body_type.append('Luxury')
variant.append(None)

In [196]:
import selenium
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException
from selenium.common.exceptions import ElementNotInteractableException
import pandas as pd
import numpy as np
import time

In [197]:
driver=webdriver.Chrome("chromedriver.exe")
driver.get('https://www.cars24.com')

In [198]:
driver.implicitly_wait(10)
button_ele=driver.find_element_by_xpath('//div[@class="_1K8Qe"]//button')
button_ele.click()

In [199]:
city=[]
city_ele=driver.find_elements_by_xpath('//ul[@class="_16Bvy"]//li')
for ele in city_ele:
    city.append(ele.text)
city_ele[0].click()
city[0]

'New Delhi'

In [200]:
viewallcars_ele=driver.find_element_by_xpath('//span[@class="jVs6G"]//a')
viewallcars_ele.click()

In [201]:
for _ in range(2000):
    driver.execute_script('window.scrollBy(0,20)')

In [202]:
url_ele=driver.find_elements_by_xpath('//div[@class="col-4"]//a')
urls=[]
for info in url_ele:
    urls.append(info.get_attribute('href'))
len(urls)

240

In [203]:
model=[]
brand=[]
variant=[]
price=[]
make_year=[]
fuel=[]
km=[]
owner=[]
transmission=[]
location=[]

In [204]:
#city[0]
for url in urls:
    driver.get(url)
    model_ele=driver.find_element_by_xpath('//div[@class="_10kZS"]//h2')
    model.append(model_ele.text[5:])
    
    str=model_ele.text
    for i in range(len(str)):
        if str[i]==' ':
            x=i
            break

    for i in range(x+1,len(str)):
        if str[i]==' ':
            y=i
            break

    brand.append(str[x+1:y])
    
    var_ele=driver.find_element_by_xpath('//div[@class="_10kZS"]//h2//span')
    variant.append(var_ele.text)
    
    info_ele=driver.find_elements_by_xpath('//strong[@class="_1-PH2"]')
    if len(info_ele)==9:
        make_year.append(info_ele[8].text[-4:])
        fuel.append(info_ele[3].text)
        km.append(info_ele[2].text[:-3].replace(',',''))
        owner.append(info_ele[1].text[0])
        transmission.append(info_ele[5].text)   
        location.append(city[0])
        
    elif len(info_ele)==8:
        make_year.append(info_ele[7].text[-4:])
        fuel.append(info_ele[3].text)
        km.append(info_ele[2].text[:-3].replace(',',''))
        owner.append(info_ele[1].text[0])
        transmission.append(info_ele[4].text)   
        location.append(city[0])
    
    price_ele=driver.find_element_by_xpath('//strong[@class="_2yYvS"]')
    str=price_ele.text
    for i in range(1,len(str)):
        if str[i]=='₹':
            x=i

    price.append(str[x+1:].replace(',',''))
    print(len(urls),len(model),len(km),len(location),len(price))

240 1 1 1 1
240 2 2 2 2
240 3 3 3 3
240 4 4 4 4
240 5 5 5 5
240 6 6 6 6
240 7 7 7 7
240 8 8 8 8
240 9 9 9 9
240 10 10 10 10
240 11 11 11 11
240 12 12 12 12
240 13 13 13 13
240 14 14 14 14
240 15 15 15 15
240 16 16 16 16
240 17 17 17 17
240 18 18 18 18
240 19 19 19 19
240 20 20 20 20
240 21 21 21 21
240 22 22 22 22
240 23 23 23 23
240 24 24 24 24
240 25 25 25 25
240 26 26 26 26
240 27 27 27 27
240 28 28 28 28
240 29 29 29 29
240 30 30 30 30
240 31 31 31 31
240 32 32 32 32
240 33 33 33 33
240 34 34 34 34
240 35 35 35 35
240 36 36 36 36
240 37 37 37 37
240 38 38 38 38
240 39 39 39 39
240 40 40 40 40
240 41 41 41 41
240 42 42 42 42
240 43 43 43 43
240 44 44 44 44
240 45 45 45 45
240 46 46 46 46
240 47 47 47 47
240 48 48 48 48
240 49 49 49 49
240 50 50 50 50
240 51 51 51 51
240 52 52 52 52
240 53 53 53 53
240 54 54 54 54
240 55 55 55 55
240 56 56 56 56
240 57 57 57 57
240 58 58 58 58
240 59 59 59 59
240 60 60 60 60
240 61 61 61 61
240 62 62 62 62
240 63 63 63 63
240 64 64 64 64
240 65 65 65 65
240 66 66 66 66
240 67 67 67 67
240 68 68 68 68
240 69 69 69 69
240 70 70 70 70
240 71 71 71 71
240 72 72 72 72
240 73 73 73 73
240 74 74 74 74
240 75 75 75 75
240 76 76 76 76
240 77 77 77 77
240 78 78 78 78
240 79 79 79 79
240 80 80 80 80
240 81 81 81 81
240 82 82 82 82
240 83 83 83 83
240 84 84 84 84
240 85 85 85 85
240 86 86 86 86
240 87 87 87 87
240 88 88 88 88
240 89 89 89 89
240 90 90 90 90
240 91 91 91 91
240 92 92 92 92
240 93 93 93 93
240 94 94 94 94
240 95 95 95 95
240 96 96 96 96
240 97 97 97 97
240 98 98 98 98
240 99 99 99 99
240 100 100 100 100
240 101 101 101 101
240 102 102 102 102
240 103 103 103 103
240 104 104 104 104
240 105 105 105 105
240 106 106 106 106
240 107 107 107 107
240 108 108 108 108
240 109 109 109 109
240 110 110 110 110
240 111 111 111 111
240 112 112 112 112
240 113 113 113 113
240 114 114 114 114
240 115 115 115 115
240 116 116 116 116
240 117 117 117 117
240 118 118 118 118
240 119 119 119 119
240 120 120 120 120
240 121 121 121 121
240 122 122 122 122
240 123 123 123 123
240 124 124 124 124
240 125 125 125 125
240 126 126 126 126
240 127 127 127 127
240 128 128 128 128
240 129 129 129 129
240 130 130 130 130
240 131 131 131 131
240 132 132 132 132
240 133 133 133 133
240 134 134 134 134
240 135 135 135 135
240 136 136 136 136
240 137 137 137 137
240 138 138 138 138
240 139 139 139 139
240 140 140 140 140
240 141 141 141 141
240 142 142 142 142
240 143 143 143 143
240 144 144 144 144
240 145 145 145 145
240 146 146 146 146
240 147 147 147 147
240 148 148 148 148
240 149 149 149 149
240 150 150 150 150
240 151 151 151 151
240 152 152 152 152
240 153 153 153 153
240 154 154 154 154
240 155 155 155 155
240 156 156 156 156
240 157 157 157 157
240 158 158 158 158
240 159 159 159 159
240 160 160 160 160
240 161 161 161 161
240 162 162 162 162
240 163 163 163 163
240 164 164 164 164
240 165 165 165 165
240 166 166 166 166
240 167 167 167 167
240 168 168 168 168
240 169 169 169 169
240 170 170 170 170
240 171 171 171 171
240 172 172 172 172
240 173 173 173 173
240 174 174 174 174
240 175 175 175 175
240 176 176 176 176
240 177 177 177 177
240 178 178 178 178
240 179 179 179 179
240 180 180 180 180
240 181 181 181 181
240 182 182 182 182
240 183 183 183 183
240 184 184 184 184
240 185 185 185 185
240 186 186 186 186
240 187 187 187 187
240 188 188 188 188
240 189 189 189 189
240 190 190 190 190
240 191 191 191 191
240 192 192 192 192
240 193 193 193 193
240 194 194 194 194
240 195 195 195 195
240 196 196 196 196
240 197 197 197 197
240 198 198 198 198
240 199 199 199 199
240 200 200 200 200
240 201 201 201 201
240 202 202 202 202
240 203 203 203 203
240 204 204 204 204
240 205 205 205 205
240 206 206 206 206
240 207 207 207 207
240 208 208 208 208
240 209 209 209 209
240 210 210 210 210
240 211 211 211 211
240 212 212 212 212
240 213 213 213 213
240 214 214 214 214
240 215 215 215 215
240 216 216 216 216
240 217 217 217 217
240 218 218 218 218
240 219 219 219 219
240 220 220 220 220
240 221 221 221 221
240 222 222 222 222
240 223 223 223 223
240 224 224 224 224
240 225 225 225 225
240 226 226 226 226
240 227 227 227 227
240 228 228 228 228
240 229 229 229 229
240 230 230 230 230
240 231 231 231 231
240 232 232 232 232
240 233 233 233 233
240 234 234 234 234
240 235 235 235 235
240 236 236 236 236
240 237 237 237 237
240 238 238 238 238
240 239 239 239 239
240 240 240 240 240

In [205]:
len(price),len(owner),len(location)

(240, 240, 240)

In [206]:
cars24_0=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                       'Transmission':(transmission),
                  'Number_of_Owners':(owner),
                   'Location':(city[0]),
                  'Price':(price)})
cars24_0

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Transmission,Number_of_Owners,Location,Price
0,Maruti,Maruti Baleno SIGMA 1.2 K12 MANUAL,SIGMA 1.2 K12 MANUAL,2020,Petrol,5645,MANUAL,1,New Delhi,574999
1,Maruti,Maruti Alto 800 VXI MANUAL,VXI MANUAL,2014,Petrol,12535,MANUAL,1,New Delhi,293599
2,Maruti,Maruti Baleno DELTA 1.2 K12 MANUAL,DELTA 1.2 K12 MANUAL,2020,Petrol,8206,MANUAL,1,New Delhi,680799
3,Hyundai,Hyundai Grand i10 MAGNA 1.2 VTVT MANUAL,MAGNA 1.2 VTVT MANUAL,2014,Petrol,16795,MANUAL,1,New Delhi,386099
4,Chevrolet,Chevrolet Beat LS PETROL MANUAL,LS PETROL MANUAL,2011,Petrol,33519,MANUAL,1,New Delhi,179599
...,...,...,...,...,...,...,...,...,...,...
235,Hyundai,Hyundai Eon ERA PLUS MANUAL,ERA PLUS MANUAL,2014,Petrol,40438,MANUAL,2,New Delhi,226899
236,Hyundai,Hyundai Grand i10 MAGNA 1.2 VTVT MANUAL,MAGNA 1.2 VTVT MANUAL,2016,Petrol,34013,MANUAL,2,New Delhi,351499
237,Maruti,Maruti Alto 800 LXI MANUAL,LXI MANUAL,2018,Petrol,11373,MANUAL,1,New Delhi,290000
238,Maruti,Maruti Baleno DELTA 1.2 K12 MANUAL,DELTA 1.2 K12 MANUAL,2017,Petrol,12117,MANUAL,2,New Delhi,526499
239,Hyundai,Hyundai Grand i10 SPORTZ 1.2 KAPPA VTVT MANUAL,SPORTZ 1.2 KAPPA VTVT MANUAL,2019,Petrol,12301,MANUAL,1,New Delhi,559099

In [207]:
cars24_0['Source']='Cars24'
cars24_0.to_csv('cars24_0.csv')

In [208]:
driver.close()

In [209]:
#city_1

In [235]:
driver=webdriver.Chrome("chromedriver.exe")
driver.get('https://www.cars24.com')

In [236]:
button_ele=driver.find_element_by_xpath('//div[@class="_1K8Qe"]//button')
button_ele.click()

In [237]:
city_ele=driver.find_elements_by_xpath('//ul[@class="_16Bvy"]//li')
for ele in city_ele:
    city.append(ele.text)
city_ele[1].click()
city[1]

'Noida'

In [238]:
for _ in range(50):
    driver.execute_script('window.scrollBy(0,20)')
    
viewallcars_ele=driver.find_element_by_xpath('//span[@class="jVs6G"]//a')
viewallcars_ele.click()

for _ in range(2000):
    driver.execute_script('window.scrollBy(0,20)')

In [239]:
url_ele=driver.find_elements_by_xpath('//div[@class="col-4"]//a')
urls=[]
for info in url_ele:
    urls.append(info.get_attribute('href'))
len(urls)

220

In [240]:
#city[1]
for url in urls:
    driver.get(url)
    model_ele=driver.find_element_by_xpath('//div[@class="_10kZS"]//h2')
    model.append(model_ele.text[5:])
    
    str=model_ele.text
    for i in range(len(str)):
        if str[i]==' ':
            x=i
            break

    for i in range(x+1,len(str)):
        if str[i]==' ':
            y=i
            break

    brand.append(str[x+1:y])
    
    var_ele=driver.find_element_by_xpath('//div[@class="_10kZS"]//h2//span')
    variant.append(var_ele.text)
    
    info_ele=driver.find_elements_by_xpath('//strong[@class="_1-PH2"]')
    if len(info_ele)==9:
        make_year.append(info_ele[8].text[-4:])
        fuel.append(info_ele[3].text)
        km.append(info_ele[2].text[:-3].replace(',',''))
        owner.append(info_ele[1].text[0])
        transmission.append(info_ele[5].text)   
        location.append(city[1])
        
    elif len(info_ele)==8:
        make_year.append(info_ele[7].text[-4:])
        fuel.append(info_ele[3].text)
        km.append(info_ele[2].text[:-3].replace(',',''))
        owner.append(info_ele[1].text[0])
        transmission.append(info_ele[4].text)   
        location.append(city[1])
    
    price_ele=driver.find_element_by_xpath('//strong[@class="_2yYvS"]')
    str=price_ele.text
    for i in range(1,len(str)):
        if str[i]=='₹':
            x=i

    price.append(str[x+1:].replace(',',''))
    print(len(urls),len(model),len(km),len(location),len(price))

220 1 1 1 1
220 2 2 2 2
220 3 3 3 3
220 4 4 4 4
220 5 5 5 5
220 6 6 6 6
220 7 7 7 7
220 8 8 8 8
220 9 9 9 9
220 10 10 10 10
220 11 11 11 11
220 12 12 12 12
220 13 13 13 13
220 14 14 14 14
220 15 15 15 15
220 16 16 16 16
220 17 17 17 17
220 18 18 18 18
220 19 19 19 19
220 20 20 20 20
220 21 21 21 21
220 22 22 22 22
220 23 23 23 23
220 24 24 24 24
220 25 25 25 25
220 26 26 26 26
220 27 27 27 27
220 28 28 28 28
220 29 29 29 29
220 30 30 30 30
220 31 31 31 31
220 32 32 32 32
220 33 33 33 33
220 34 34 34 34
220 35 35 35 35
220 36 36 36 36
220 37 37 37 37
220 38 38 38 38
220 39 39 39 39
220 40 40 40 40
220 41 41 41 41
220 42 42 42 42
220 43 43 43 43
220 44 44 44 44
220 45 45 45 45
220 46 46 46 46
220 47 47 47 47
220 48 48 48 48
220 49 49 49 49
220 50 50 50 50
220 51 51 51 51
220 52 52 52 52
220 53 53 53 53
220 54 54 54 54
220 55 55 55 55
220 56 56 56 56
220 57 57 57 57
220 58 58 58 58
220 59 59 59 59
220 60 60 60 60
220 61 61 61 61
220 62 62 62 62
220 63 63 63 63
220 64 64 64 64
220 65 65 65 65
220 66 66 66 66
220 67 67 67 67
220 68 68 68 68
220 69 69 69 69
220 70 70 70 70
220 71 71 71 71
220 72 72 72 72
220 73 73 73 73
220 74 74 74 74
220 75 75 75 75
220 76 76 76 76
220 77 77 77 77
220 78 78 78 78
220 79 79 79 79
220 80 80 80 80
220 81 81 81 81
220 82 82 82 82
220 83 83 83 83
220 84 84 84 84
220 85 85 85 85
220 86 86 86 86
220 87 87 87 87
220 88 88 88 88
220 89 89 89 89
220 90 90 90 90
220 91 91 91 91
220 92 92 92 92
220 93 93 93 93
220 94 94 94 94
220 95 95 95 95
220 96 96 96 96
220 97 97 97 97
220 98 98 98 98
220 99 99 99 99
220 100 100 100 100
220 101 101 101 101
220 102 102 102 102
220 103 103 103 103
220 104 104 104 104
220 105 105 105 105
220 106 106 106 106
220 107 107 107 107
220 108 108 108 108
220 109 109 109 109
220 110 110 110 110
220 111 111 111 111
220 112 112 112 112
220 113 113 113 113
220 114 114 114 114
220 115 115 115 115
220 116 116 116 116
220 117 117 117 117
220 118 118 118 118
220 119 119 119 119
220 120 120 120 120
220 121 121 121 121
220 122 122 122 122
220 123 123 123 123
220 124 124 124 124
220 125 125 125 125
220 126 126 126 126
220 127 127 127 127
220 128 128 128 128
220 129 129 129 129
220 130 130 130 130
220 131 131 131 131
220 132 132 132 132
220 133 133 133 133
220 134 134 134 134
220 135 135 135 135
220 136 136 136 136
220 137 137 137 137
220 138 138 138 138
220 139 139 139 139
220 140 140 140 140
220 141 141 141 141
220 142 142 142 142
220 143 143 143 143
220 144 144 144 144
220 145 145 145 145
220 146 146 146 146
220 147 147 147 147
220 148 148 148 148
220 149 149 149 149
220 150 150 150 150
220 151 151 151 151
220 152 152 152 152
220 153 153 153 153
220 154 154 154 154
220 155 155 155 155
220 156 156 156 156
220 157 157 157 157
220 158 158 158 158
220 159 159 159 159
220 160 160 160 160
220 161 161 161 161
220 162 162 162 162
220 163 163 163 163
220 164 164 164 164
220 165 165 165 165
220 166 166 166 166
220 167 167 167 167
220 168 168 168 168
220 169 169 169 169
220 170 170 170 170
220 171 171 171 171
220 172 172 172 172
220 173 173 173 173
220 174 174 174 174
220 175 175 175 175
220 176 176 176 176
220 177 177 177 177
220 178 178 178 178
220 179 179 179 179
220 180 180 180 180
220 181 181 181 181
220 182 182 182 182
220 183 183 183 183
220 184 184 184 184
220 185 185 185 185
220 186 186 186 186
220 187 187 187 187
220 188 188 188 188
220 189 189 189 189
220 190 190 190 190
220 191 191 191 191
220 192 192 192 192
220 193 193 193 193
220 194 194 194 194
220 195 195 195 195
220 196 196 196 196
220 197 197 197 197
220 198 198 198 198
220 199 199 199 199
220 200 200 200 200
220 201 201 201 201
220 202 202 202 202
220 203 203 203 203
220 204 204 204 204
220 205 205 205 205
220 206 206 206 206
220 207 207 207 207
220 208 208 208 208
220 209 209 209 209
220 210 210 210 210
220 211 211 211 211
220 212 212 212 212
220 213 213 213 213
220 214 214 214 214
220 215 215 215 215
220 216 216 216 216
220 217 217 217 217
220 218 218 218 218
220 219 219 219 219
220 220 220 220 220

In [241]:
cars24_1=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                       'Transmission':(transmission),
                  'Number_of_Owners':(owner),
                   'Location':(city[1]),
                  'Price':(price)})
cars24_1

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Transmission,Number_of_Owners,Location,Price
0,Maruti,Maruti S PRESSO VXI,VXI,2020,Petrol,3176,NA,1,Noida,402199
1,Hyundai,Hyundai GRAND I10 NIOS MAGNA 1.2 MT MANUAL,MAGNA 1.2 MT MANUAL,2020,Petrol,4955,MANUAL,1,Noida,584299
2,Maruti,Maruti Baleno SIGMA 1.2 K12 MANUAL,SIGMA 1.2 K12 MANUAL,2020,Petrol,5645,MANUAL,1,Noida,574999
3,Maruti,Maruti Alto 800 VXI MANUAL,VXI MANUAL,2014,Petrol,12535,MANUAL,1,Noida,293599
4,Maruti,Maruti Baleno DELTA 1.2 K12 MANUAL,DELTA 1.2 K12 MANUAL,2020,Petrol,8206,MANUAL,1,Noida,680799
...,...,...,...,...,...,...,...,...,...,...
215,Honda,Honda Mobilio 1.5 S I DTEC MANUAL,1.5 S I DTEC MANUAL,2015,Diesel,43196,MANUAL,2,Noida,431099
216,Maruti,Maruti Alto LXI MANUAL,LXI MANUAL,2020,Petrol,11520,MANUAL,1,Noida,383599
217,Maruti,Maruti Alto K10 LXI MANUAL,LXI MANUAL,2012,Petrol,44508,MANUAL,1,Noida,000
218,Maruti,Maruti Baleno SIGMA DDIS 190 MANUAL,SIGMA DDIS 190 MANUAL,2015,Diesel,59364,MANUAL,1,Noida,413999
219,Maruti,Maruti Swift VDI MANUAL,VDI MANUAL,2012,Diesel,30589,MANUAL,1,Noida,304899

In [242]:
cars24_1['Source']='Cars24'
cars24_1.to_csv('cars24_1.csv')

In [243]:
driver.close()

In [244]:
#city_2

In [245]:
driver=webdriver.Chrome("chromedriver.exe")
driver.get('https://www.cars24.com')

In [246]:
button_ele=driver.find_element_by_xpath('//div[@class="_1K8Qe"]//button')
button_ele.click()

In [247]:
city_ele=driver.find_elements_by_xpath('//ul[@class="_16Bvy"]//li')
for ele in city_ele:
    city.append(ele.text)
city_ele[2].click()
city[2]

'Gurgaon'

In [248]:
viewallcars_ele=driver.find_element_by_xpath('//span[@class="jVs6G"]//a')
viewallcars_ele.click()

for _ in range(2000):
    driver.execute_script('window.scrollBy(0,20)')

In [249]:
url_ele=driver.find_elements_by_xpath('//div[@class="col-4"]//a')
urls=[]
for info in url_ele:
    urls.append(info.get_attribute('href'))
len(urls)

240

In [250]:
#city[2]
for url in urls:
    driver.get(url)
    model_ele=driver.find_element_by_xpath('//div[@class="_10kZS"]//h2')
    model.append(model_ele.text[5:])
    
    str=model_ele.text
    for i in range(len(str)):
        if str[i]==' ':
            x=i
            break

    for i in range(x+1,len(str)):
        if str[i]==' ':
            y=i
            break

    brand.append(str[x+1:y])
    
    var_ele=driver.find_element_by_xpath('//div[@class="_10kZS"]//h2//span')
    variant.append(var_ele.text)
    
    info_ele=driver.find_elements_by_xpath('//strong[@class="_1-PH2"]')
    if len(info_ele)==9:
        make_year.append(info_ele[8].text[-4:])
        fuel.append(info_ele[3].text)
        km.append(info_ele[2].text[:-3].replace(',',''))
        owner.append(info_ele[1].text[0])
        transmission.append(info_ele[5].text)   
        location.append(city[2])
        
    elif len(info_ele)==8:
        make_year.append(info_ele[7].text[-4:])
        fuel.append(info_ele[3].text)
        km.append(info_ele[2].text[:-3].replace(',',''))
        owner.append(info_ele[1].text[0])
        transmission.append(info_ele[4].text)   
        location.append(city[2])
    
    price_ele=driver.find_element_by_xpath('//strong[@class="_2yYvS"]')
    str=price_ele.text
    for i in range(1,len(str)):
        if str[i]=='₹':
            x=i

    price.append(str[x+1:].replace(',',''))
    print(len(urls),len(model),len(km),len(location),len(price))

240 221 221 221 221
240 222 222 222 222
240 223 223 223 223
240 224 224 224 224
240 225 225 225 225
240 226 226 226 226
240 227 227 227 227
240 228 228 228 228
240 229 229 229 229
240 230 230 230 230
240 231 231 231 231
240 232 232 232 232
240 233 233 233 233
240 234 234 234 234
240 235 235 235 235
240 236 236 236 236
240 237 237 237 237
240 238 238 238 238
240 239 239 239 239
240 240 240 240 240
240 241 241 241 241
240 242 242 242 242
240 243 243 243 243
240 244 244 244 244
240 245 245 245 245
240 246 246 246 246
240 247 247 247 247
240 248 248 248 248
240 249 249 249 249
240 250 250 250 250
240 251 251 251 251
240 252 252 252 252
240 253 253 253 253
240 254 254 254 254
240 255 255 255 255
240 256 256 256 256
240 257 257 257 257
240 258 258 258 258
240 259 259 259 259
240 260 260 260 260
240 261 261 261 261
240 262 262 262 262
240 263 263 263 263
240 264 264 264 264
240 265 265 265 265
240 266 266 266 266
240 267 267 267 267
240 268 268 268 268
240 269 269 269 269
240 270 270 270 270
240 271 271 271 271
240 272 272 272 272
240 273 273 273 273
240 274 274 274 274
240 275 275 275 275
240 276 276 276 276
240 277 277 277 277
240 278 278 278 278
240 279 279 279 279
240 280 280 280 280
240 281 281 281 281
240 282 282 282 282
240 283 283 283 283
240 284 284 284 284
240 285 285 285 285
240 286 286 286 286
240 287 287 287 287
240 288 288 288 288
240 289 289 289 289
240 290 290 290 290
240 291 291 291 291
240 292 292 292 292
240 293 293 293 293
240 294 294 294 294
240 295 295 295 295
240 296 296 296 296
240 297 297 297 297
240 298 298 298 298
240 299 299 299 299
240 300 300 300 300
240 301 301 301 301
240 302 302 302 302
240 303 303 303 303
240 304 304 304 304
240 305 305 305 305
240 306 306 306 306
240 307 307 307 307
240 308 308 308 308
240 309 309 309 309
240 310 310 310 310
240 311 311 311 311
240 312 312 312 312
240 313 313 313 313
240 314 314 314 314
240 315 315 315 315
240 316 316 316 316
240 317 317 317 317
240 318 318 318 318
240 319 319 319 319
240 320 320 320 320
240 321 321 321 321
240 322 322 322 322
240 323 323 323 323
240 324 324 324 324
240 325 325 325 325
240 326 326 326 326
240 327 327 327 327
240 328 328 328 328
240 329 329 329 329
240 330 330 330 330
240 331 331 331 331
240 332 332 332 332
240 333 333 333 333
240 334 334 334 334
240 335 335 335 335
240 336 336 336 336
240 337 337 337 337
240 338 338 338 338
240 339 339 339 339
240 340 340 340 340
240 341 341 341 341
240 342 342 342 342
240 343 343 343 343
240 344 344 344 344
240 345 345 345 345
240 346 346 346 346
240 347 347 347 347
240 348 348 348 348
240 349 349 349 349
240 350 350 350 350
240 351 351 351 351
240 352 352 352 352
240 353 353 353 353
240 354 354 354 354
240 355 355 355 355
240 356 356 356 356
240 357 357 357 357
240 358 358 358 358
240 359 359 359 359
240 360 360 360 360
240 361 361 361 361
240 362 362 362 362
240 363 363 363 363
240 364 364 364 364
240 365 365 365 365
240 366 366 366 366
240 367 367 367 367
240 368 368 368 368
240 369 369 369 369
240 370 370 370 370
240 371 371 371 371
240 372 372 372 372
240 373 373 373 373
240 374 374 374 374
240 375 375 375 375
240 376 376 376 376
240 377 377 377 377
240 378 378 378 378
240 379 379 379 379
240 380 380 380 380
240 381 381 381 381
240 382 382 382 382
240 383 383 383 383
240 384 384 384 384
240 385 385 385 385
240 386 386 386 386
240 387 387 387 387
240 388 388 388 388
240 389 389 389 389
240 390 390 390 390
240 391 391 391 391
240 392 392 392 392
240 393 393 393 393
240 394 394 394 394
240 395 395 395 395
240 396 396 396 396
240 397 397 397 397
240 398 398 398 398
240 399 399 399 399
240 400 400 400 400
240 401 401 401 401
240 402 402 402 402
240 403 403 403 403
240 404 404 404 404
240 405 405 405 405
240 406 406 406 406
240 407 407 407 407
240 408 408 408 408
240 409 409 409 409
240 410 410 410 410
240 411 411 411 411
240 412 412 412 412
240 413 413 413 413
240 414 414 414 414
240 415 415 415 415
240 416 416 416 416
240 417 417 417 417
240 418 418 418 418
240 419 419 419 419
240 420 420 420 420
240 421 421 421 421
240 422 422 422 422
240 423 423 423 423
240 424 424 424 424
240 425 425 425 425
240 426 426 426 426
240 427 427 427 427
240 428 428 428 428
240 429 429 429 429
240 430 430 430 430
240 431 431 431 431
240 432 432 432 432
240 433 433 433 433
240 434 434 434 434
240 435 435 435 435
240 436 436 436 436
240 437 437 437 437
240 438 438 438 438
240 439 439 439 439
240 440 440 440 440
240 441 441 441 441
240 442 442 442 442
240 443 443 443 443
240 444 444 444 444
240 445 445 445 445
240 446 446 446 446
240 447 447 447 447
240 448 448 448 448
240 449 449 449 449
240 450 450 450 450
240 451 451 451 451
240 452 452 452 452
240 453 453 453 453
240 454 454 454 454
240 455 455 455 455
240 456 456 456 456
240 457 457 457 457
240 458 458 458 458
240 459 459 459 459
240 460 460 460 460

In [251]:
cars24_2=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                       'Transmission':(transmission),
                  'Number_of_Owners':(owner),
                   'Location':(city[2]),
                  'Price':(price)})
cars24_2

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Transmission,Number_of_Owners,Location,Price
0,Maruti,Maruti S PRESSO VXI,VXI,2020,Petrol,3176,NA,1,Gurgaon,402199
1,Hyundai,Hyundai GRAND I10 NIOS MAGNA 1.2 MT MANUAL,MAGNA 1.2 MT MANUAL,2020,Petrol,4955,MANUAL,1,Gurgaon,584299
2,Maruti,Maruti Baleno SIGMA 1.2 K12 MANUAL,SIGMA 1.2 K12 MANUAL,2020,Petrol,5645,MANUAL,1,Gurgaon,574999
3,Maruti,Maruti Alto 800 VXI MANUAL,VXI MANUAL,2014,Petrol,12535,MANUAL,1,Gurgaon,293599
4,Maruti,Maruti Baleno DELTA 1.2 K12 MANUAL,DELTA 1.2 K12 MANUAL,2020,Petrol,8206,MANUAL,1,Gurgaon,680799
...,...,...,...,...,...,...,...,...,...,...
455,Hyundai,Hyundai Eon ERA PLUS MANUAL,ERA PLUS MANUAL,2014,Petrol,40438,MANUAL,2,Gurgaon,226899
456,Hyundai,Hyundai Grand i10 MAGNA 1.2 VTVT MANUAL,MAGNA 1.2 VTVT MANUAL,2016,Petrol,34013,MANUAL,2,Gurgaon,351499
457,Maruti,Maruti Alto 800 LXI MANUAL,LXI MANUAL,2018,Petrol,11373,MANUAL,1,Gurgaon,290000
458,Maruti,Maruti Baleno DELTA 1.2 K12 MANUAL,DELTA 1.2 K12 MANUAL,2017,Petrol,12117,MANUAL,2,Gurgaon,526499
459,Hyundai,Hyundai Grand i10 SPORTZ 1.2 KAPPA VTVT MANUAL,SPORTZ 1.2 KAPPA VTVT MANUAL,2019,Petrol,12301,MANUAL,1,Gurgaon,559099

In [252]:
cars24_2['Source']='Cars24'
cars24_2.to_csv('cars24_2.csv')

In [265]:
driver.close()

In [260]:
#city_3

In [266]:
driver=webdriver.Chrome("chromedriver.exe")
driver.get('https://www.cars24.com')

In [267]:
button_ele=driver.find_element_by_xpath('//div[@class="_1K8Qe"]//button')
button_ele.click()

In [268]:
city_ele=driver.find_elements_by_xpath('//ul[@class="_16Bvy"]//li')
for ele in city_ele:
    city.append(ele.text)
city_ele[3].click()
city[3]

'Mumbai'

In [269]:
viewallcars_ele=driver.find_element_by_xpath('//span[@class="jVs6G"]//a')
viewallcars_ele.click()

In [271]:
for _ in range(2000):
    driver.execute_script('window.scrollBy(0,20)')

In [272]:
url_ele=driver.find_elements_by_xpath('//div[@class="col-4"]//a')
urls=[]
for info in url_ele:
    urls.append(info.get_attribute('href'))
len(urls)

2128

In [276]:
#city[3]
for z in range(1197,len(urls)):
    driver.get(urls[z])
    model_ele=driver.find_element_by_xpath('//div[@class="_10kZS"]//h2')
    model.append(model_ele.text[5:])
    
    str=model_ele.text
    for i in range(len(str)):
        if str[i]==' ':
            x=i
            break

    for i in range(x+1,len(str)):
        if str[i]==' ':
            y=i
            break

    brand.append(str[x+1:y])
    
    var_ele=driver.find_element_by_xpath('//div[@class="_10kZS"]//h2//span')
    variant.append(var_ele.text)
    
    info_ele=driver.find_elements_by_xpath('//strong[@class="_1-PH2"]')
    if len(info_ele)==9:
        make_year.append(info_ele[8].text[-4:])
        fuel.append(info_ele[3].text)
        km.append(info_ele[2].text[:-3].replace(',',''))
        owner.append(info_ele[1].text[0])
        transmission.append(info_ele[5].text)   
        location.append(city[3])
        
    elif len(info_ele)==8:
        make_year.append(info_ele[7].text[-4:])
        fuel.append(info_ele[3].text)
        km.append(info_ele[2].text[:-3].replace(',',''))
        owner.append(info_ele[1].text[0])
        transmission.append(info_ele[4].text)   
        location.append(city[3])
    
    price_ele=driver.find_element_by_xpath('//strong[@class="_2yYvS"]')
    str=price_ele.text
    for i in range(1,len(str)):
        if str[i]=='₹':
            x=i

    price.append(str[x+1:].replace(',',''))
    print(len(urls),len(model),len(km),len(location),len(price))

NoSuchWindowException: Message: no such window: window was already closed
  (Session info: chrome=93.0.4577.82)

In [274]:
cars24_3=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                       'Transmission':(transmission),
                  'Number_of_Owners':(owner),
                   'Location':(city[3]),
                  'Price':(price)})
cars24_3

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Transmission,Number_of_Owners,Location,Price
0,Maruti,Maruti S PRESSO VXI,VXI,2020,Petrol,3176,NA,1,Mumbai,402199
1,Hyundai,Hyundai GRAND I10 NIOS MAGNA 1.2 MT MANUAL,MAGNA 1.2 MT MANUAL,2020,Petrol,4955,MANUAL,1,Mumbai,584299
2,Maruti,Maruti Baleno SIGMA 1.2 K12 MANUAL,SIGMA 1.2 K12 MANUAL,2020,Petrol,5645,MANUAL,1,Mumbai,574999
3,Maruti,Maruti Alto 800 VXI MANUAL,VXI MANUAL,2014,Petrol,12535,MANUAL,1,Mumbai,293599
4,Maruti,Maruti Baleno DELTA 1.2 K12 MANUAL,DELTA 1.2 K12 MANUAL,2020,Petrol,8206,MANUAL,1,Mumbai,680799
...,...,...,...,...,...,...,...,...,...,...
1191,Maruti,Maruti Alto K10 VXI MANUAL,VXI MANUAL,2016,Petrol,21933,MANUAL,1,Mumbai,289799
1192,Maruti,Maruti Wagon R 1.0 VXI MANUAL,VXI MANUAL,2014,Petrol,32984,MANUAL,2,Mumbai,330599
1193,Maruti,Maruti Wagon R 1.0 VXI MANUAL,VXI MANUAL,2012,Petrol,40091,MANUAL,1,Mumbai,284999
1194,Maruti,Maruti Alto K10 VXI AMT MANUAL,VXI AMT MANUAL,2016,Petrol,15842,MANUAL,1,Mumbai,332699
1195,Maruti,Maruti Alto 800 LXI MANUAL,LXI MANUAL,2018,Petrol,9833,MANUAL,2,Mumbai,305299

In [275]:
cars24_3['Source']='Cars24'
cars24_3.to_csv('cars24_3.csv')

In [277]:
driver.close()

NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=93.0.4577.82)

In [290]:
#city_4

In [291]:
driver=webdriver.Chrome("chromedriver.exe")
driver.get('https://www.cars24.com')

In [292]:
button_ele=driver.find_element_by_xpath('//div[@class="_1K8Qe"]//button')
button_ele.click()

In [293]:
city_ele=driver.find_elements_by_xpath('//ul[@class="_16Bvy"]//li')
for ele in city_ele:
    city.append(ele.text)
city_ele[4].click()
city[4]

'Pune'

In [295]:
viewallcars_ele=driver.find_element_by_xpath('//span[@class="jVs6G"]//a')
viewallcars_ele.click()

In [296]:
time.sleep(10)
for _ in range(2000):
    driver.execute_script('window.scrollBy(0,20)')

In [299]:
url_ele=driver.find_elements_by_xpath('//div[@class="col-4"]//a')
urls=[]
for info in url_ele:
    urls.append(info.get_attribute('href'))
len(urls)

1020

In [301]:
brand=[]
model=[]
variant=[]
make_year=[]
fuel=[]
km=[]
transmission=[]
owner=[]
location=[]
price=[]

In [302]:
#city[4]
for url in urls:
    driver.get(url)
    model_ele=driver.find_element_by_xpath('//div[@class="_10kZS"]//h2')
    model.append(model_ele.text[5:])
    
    str=model_ele.text
    for i in range(len(str)):
        if str[i]==' ':
            x=i
            break

    for i in range(x+1,len(str)):
        if str[i]==' ':
            y=i
            break

    brand.append(str[x+1:y])
    
    var_ele=driver.find_element_by_xpath('//div[@class="_10kZS"]//h2//span')
    variant.append(var_ele.text)
    
    info_ele=driver.find_elements_by_xpath('//strong[@class="_1-PH2"]')
    if len(info_ele)==9:
        make_year.append(info_ele[8].text[-4:])
        fuel.append(info_ele[3].text)
        km.append(info_ele[2].text[:-3].replace(',',''))
        owner.append(info_ele[1].text[0])
        transmission.append(info_ele[5].text)   
        location.append(city[4])
        
    elif len(info_ele)==8:
        make_year.append(info_ele[7].text[-4:])
        fuel.append(info_ele[3].text)
        km.append(info_ele[2].text[:-3].replace(',',''))
        owner.append(info_ele[1].text[0])
        transmission.append(info_ele[4].text)   
        location.append(city[4])
    price_ele=driver.find_element_by_xpath('//strong[@class="_2yYvS"]')
    str=price_ele.text
    for i in range(1,len(str)):
        if str[i]=='₹':
            x=i

    price.append(str[x+1:].replace(',',''))
    print(len(urls),len(model),len(km),len(location),len(price))

1020 1 1 1 1
1020 2 2 2 2
1020 3 3 3 3
1020 4 4 4 4
1020 5 5 5 5
1020 6 6 6 6
1020 7 7 7 7
1020 8 8 8 8
1020 9 9 9 9
1020 10 10 10 10
1020 11 11 11 11
1020 12 12 12 12
1020 13 13 13 13
1020 14 14 14 14
1020 15 15 15 15
1020 16 16 16 16
1020 17 17 17 17
1020 18 18 18 18
1020 19 19 19 19
1020 20 20 20 20
1020 21 21 21 21
1020 22 22 22 22
1020 23 23 23 23
1020 24 24 24 24
1020 25 25 25 25
1020 26 26 26 26
1020 27 27 27 27
1020 28 28 28 28
1020 29 29 29 29
1020 30 30 30 30
1020 31 31 31 31
1020 32 32 32 32
1020 33 33 33 33
1020 34 34 34 34
1020 35 35 35 35
1020 36 36 36 36
1020 37 37 37 37
1020 38 38 38 38
1020 39 39 39 39
1020 40 40 40 40
1020 41 41 41 41
1020 42 42 42 42
1020 43 43 43 43
1020 44 44 44 44
1020 45 45 45 45
1020 46 46 46 46
1020 47 47 47 47
1020 48 48 48 48
1020 49 49 49 49
1020 50 50 50 50
1020 51 51 51 51
1020 52 52 52 52
1020 53 53 53 53
1020 54 54 54 54
1020 55 55 55 55
1020 56 56 56 56
1020 57 57 57 57
1020 58 58 58 58
1020 59 59 59 59
1020 60 60 60 60
1020 61 61 61 61
1020 62 62 62 62
1020 63 63 63 63
1020 64 64 64 64
1020 65 65 65 65
1020 66 66 66 66
1020 67 67 67 67
1020 68 68 68 68
1020 69 69 69 69
1020 70 70 70 70
1020 71 71 71 71
1020 72 72 72 72
1020 73 73 73 73
1020 74 74 74 74
1020 75 75 75 75
1020 76 76 76 76
1020 77 77 77 77
1020 78 78 78 78
1020 79 79 79 79
1020 80 80 80 80
1020 81 81 81 81
1020 82 82 82 82
1020 83 83 83 83
1020 84 84 84 84
1020 85 85 85 85
1020 86 86 86 86
1020 87 87 87 87
1020 88 88 88 88
1020 89 89 89 89
1020 90 90 90 90
1020 91 91 91 91
1020 92 92 92 92
1020 93 93 93 93
1020 94 94 94 94
1020 95 95 95 95
1020 96 96 96 96
1020 97 97 97 97
1020 98 98 98 98
1020 99 99 99 99
1020 100 100 100 100
1020 101 101 101 101
1020 102 102 102 102
1020 103 103 103 103
1020 104 104 104 104
1020 105 105 105 105
1020 106 106 106 106
1020 107 107 107 107
1020 108 108 108 108
1020 109 109 109 109
1020 110 110 110 110
1020 111 111 111 111
1020 112 112 112 112
1020 113 113 113 113
1020 114 114 114 114
1020 115 115 115 115
1020 116 116 116 116
1020 117 117 117 117
1020 118 118 118 118
1020 119 119 119 119
1020 120 120 120 120
1020 121 121 121 121
1020 122 122 122 122
1020 123 123 123 123
1020 124 124 124 124
1020 125 125 125 125
1020 126 126 126 126
1020 127 127 127 127
1020 128 128 128 128
1020 129 129 129 129
1020 130 130 130 130
1020 131 131 131 131
1020 132 132 132 132
1020 133 133 133 133
1020 134 134 134 134
1020 135 135 135 135
1020 136 136 136 136
1020 137 137 137 137
1020 138 138 138 138
1020 139 139 139 139
1020 140 140 140 140
1020 141 141 141 141
1020 142 142 142 142
1020 143 143 143 143
1020 144 144 144 144
1020 145 145 145 145
1020 146 146 146 146
1020 147 147 147 147
1020 148 148 148 148
1020 149 149 149 149
1020 150 150 150 150
1020 151 151 151 151
1020 152 152 152 152
1020 153 153 153 153
1020 154 154 154 154
1020 155 155 155 155
1020 156 156 156 156
1020 157 157 157 157
1020 158 158 158 158
1020 159 159 159 159
1020 160 160 160 160
1020 161 161 161 161
1020 162 162 162 162
1020 163 163 163 163
1020 164 164 164 164
1020 165 165 165 165
1020 166 166 166 166
1020 167 167 167 167
1020 168 168 168 168
1020 169 169 169 169
1020 170 170 170 170
1020 171 171 171 171
1020 172 172 172 172
1020 173 173 173 173
1020 174 174 174 174
1020 175 175 175 175
1020 176 176 176 176
1020 177 177 177 177
1020 178 178 178 178
1020 179 179 179 179
1020 180 180 180 180
1020 181 181 181 181
1020 182 182 182 182
1020 183 183 183 183
1020 184 184 184 184
1020 185 185 185 185
1020 186 186 186 186
1020 187 187 187 187
1020 188 188 188 188
1020 189 189 189 189
1020 190 190 190 190
1020 191 191 191 191
1020 192 192 192 192
1020 193 193 193 193
1020 194 194 194 194
1020 195 195 195 195
1020 196 196 196 196
1020 197 197 197 197
1020 198 198 198 198
1020 199 199 199 199
1020 200 200 200 200
1020 201 201 201 201
1020 202 202 202 202
1020 203 203 203 203
1020 204 204 204 204
1020 205 205 205 205
1020 206 206 206 206
1020 207 207 207 207
1020 208 208 208 208
1020 209 209 209 209
1020 210 210 210 210
1020 211 211 211 211
1020 212 212 212 212
1020 213 213 213 213
1020 214 214 214 214
1020 215 215 215 215
1020 216 216 216 216
1020 217 217 217 217
1020 218 218 218 218
1020 219 219 219 219
1020 220 220 220 220
1020 221 221 221 221
1020 222 222 222 222
1020 223 223 223 223
1020 224 224 224 224
1020 225 225 225 225
1020 226 226 226 226
1020 227 227 227 227
1020 228 228 228 228
1020 229 229 229 229
1020 230 230 230 230
1020 231 231 231 231
1020 232 232 232 232
1020 233 233 233 233
1020 234 234 234 234
1020 235 235 235 235
1020 236 236 236 236
1020 237 237 237 237
1020 238 238 238 238
1020 239 239 239 239
1020 240 240 240 240
1020 241 241 241 241
1020 242 242 242 242
1020 243 243 243 243
1020 244 244 244 244
1020 245 245 245 245
1020 246 246 246 246
1020 247 247 247 247
1020 248 248 248 248
1020 249 249 249 249
1020 250 250 250 250
1020 251 251 251 251
1020 252 252 252 252
1020 253 253 253 253
1020 254 254 254 254
1020 255 255 255 255
1020 256 256 256 256
1020 257 257 257 257
1020 258 258 258 258
1020 259 259 259 259
1020 260 260 260 260
1020 261 261 261 261
1020 262 262 262 262
1020 263 263 263 263
1020 264 264 264 264
1020 265 265 265 265
1020 266 266 266 266
1020 267 267 267 267
1020 268 268 268 268
1020 269 269 269 269
1020 270 270 270 270
1020 271 271 271 271
1020 272 272 272 272
1020 273 273 273 273
1020 274 274 274 274
1020 275 275 275 275
1020 276 276 276 276
1020 277 277 277 277
1020 278 278 278 278
1020 279 279 279 279
1020 280 280 280 280
1020 281 281 281 281
1020 282 282 282 282
1020 283 283 283 283
1020 284 284 284 284
1020 285 285 285 285
1020 286 286 286 286
1020 287 287 287 287
1020 288 288 288 288
1020 289 289 289 289
1020 290 290 290 290
1020 291 291 291 291
1020 292 292 292 292
1020 293 293 293 293
1020 294 294 294 294
1020 295 295 295 295
1020 296 296 296 296
1020 297 297 297 297
1020 298 298 298 298
1020 299 299 299 299
1020 300 300 300 300
1020 301 301 301 301
1020 302 302 302 302
1020 303 303 303 303
1020 304 304 304 304
1020 305 305 305 305
1020 306 306 306 306
1020 307 307 307 307
1020 308 308 308 308
1020 309 309 309 309
1020 310 310 310 310
1020 311 311 311 311
1020 312 312 312 312
1020 313 313 313 313
1020 314 314 314 314
1020 315 315 315 315
1020 316 316 316 316
1020 317 317 317 317
1020 318 318 318 318
1020 319 319 319 319
1020 320 320 320 320
1020 321 321 321 321
1020 322 322 322 322
1020 323 323 323 323
1020 324 324 324 324
1020 325 325 325 325
1020 326 326 326 326
1020 327 327 327 327
1020 328 328 328 328
1020 329 329 329 329
1020 330 330 330 330
1020 331 331 331 331
1020 332 332 332 332
1020 333 333 333 333
1020 334 334 334 334
1020 335 335 335 335
1020 336 336 336 336
1020 337 337 337 337
1020 338 338 338 338
1020 339 339 339 339
1020 340 340 340 340
1020 341 341 341 341
1020 342 342 342 342
1020 343 343 343 343
1020 344 344 344 344
1020 345 345 345 345
1020 346 346 346 346
1020 347 347 347 347
1020 348 348 348 348
1020 349 349 349 349
1020 350 350 350 350
1020 351 351 351 351
1020 352 352 352 352
1020 353 353 353 353
1020 354 354 354 354
1020 355 355 355 355
1020 356 356 356 356
1020 357 357 357 357
1020 358 358 358 358
1020 359 359 359 359
1020 360 360 360 360
1020 361 361 361 361
1020 362 362 362 362
1020 363 363 363 363
1020 364 364 364 364
1020 365 365 365 365
1020 366 366 366 366
1020 367 367 367 367
1020 368 368 368 368
1020 369 369 369 369
1020 370 370 370 370
1020 371 371 371 371
1020 372 372 372 372
1020 373 373 373 373
1020 374 374 374 374
1020 375 375 375 375
1020 376 376 376 376
1020 377 377 377 377
1020 378 378 378 378
1020 379 379 379 379
1020 380 380 380 380
1020 381 381 381 381
1020 382 382 382 382
1020 383 383 383 383
1020 384 384 384 384
1020 385 385 385 385
1020 386 386 386 386
1020 387 387 387 387
1020 388 388 388 388
1020 389 389 389 389
1020 390 390 390 390
1020 391 391 391 391
1020 392 392 392 392
1020 393 393 393 393
1020 394 394 394 394
1020 395 395 395 395
1020 396 396 396 396
1020 397 397 397 397
1020 398 398 398 398
1020 399 399 399 399
1020 400 400 400 400
1020 401 401 401 401
1020 402 402 402 402
1020 403 403 403 403
1020 404 404 404 404
1020 405 405 405 405
1020 406 406 406 406
1020 407 407 407 407
1020 408 408 408 408
1020 409 409 409 409
1020 410 410 410 410
1020 411 411 411 411

1020 412 412 412 412
1020 413 413 413 413
1020 414 414 414 414
1020 415 415 415 415
1020 416 416 416 416
1020 417 417 417 417
1020 418 418 418 418
1020 419 419 419 419
1020 420 420 420 420
1020 421 421 421 421
1020 422 422 422 422
1020 423 423 423 423
1020 424 424 424 424
1020 425 425 425 425
1020 426 426 426 426
1020 427 427 427 427
1020 428 428 428 428
1020 429 429 429 429
1020 430 430 430 430
1020 431 431 431 431
1020 432 432 432 432
1020 433 433 433 433
1020 434 434 434 434
1020 435 435 435 435
1020 436 436 436 436
1020 437 437 437 437
1020 438 438 438 438
1020 439 439 439 439
1020 440 440 440 440
1020 441 441 441 441
1020 442 442 442 442
1020 443 443 443 443
1020 444 444 444 444
1020 445 445 445 445
1020 446 446 446 446
1020 447 447 447 447
1020 448 448 448 448
1020 449 449 449 449
1020 450 450 450 450
1020 451 451 451 451
1020 452 452 452 452
1020 453 453 453 453
1020 454 454 454 454
1020 455 455 455 455
1020 456 456 456 456
1020 457 457 457 457
1020 458 458 458 458
1020 459 459 459 459
1020 460 460 460 460
1020 461 461 461 461
1020 462 462 462 462
1020 463 463 463 463
1020 464 464 464 464
1020 465 465 465 465
1020 466 466 466 466
1020 467 467 467 467
1020 468 468 468 468
1020 469 469 469 469
1020 470 470 470 470
1020 471 471 471 471
1020 472 472 472 472
1020 473 473 473 473
1020 474 474 474 474
1020 475 475 475 475
1020 476 476 476 476
1020 477 477 477 477
1020 478 478 478 478
1020 479 479 479 479
1020 480 480 480 480
1020 481 481 481 481
1020 482 482 482 482
1020 483 483 483 483
1020 484 484 484 484
1020 485 485 485 485
1020 486 486 486 486
1020 487 487 487 487
1020 488 488 488 488
1020 489 489 489 489
1020 490 490 490 490
1020 491 491 491 491
1020 492 492 492 492
1020 493 493 493 493
1020 494 494 494 494
1020 495 495 495 495
1020 496 496 496 496
1020 497 497 497 497
1020 498 498 498 498
1020 499 499 499 499
1020 500 500 500 500
1020 501 501 501 501
1020 502 502 502 502
1020 503 503 503 503
1020 504 504 504 504
1020 505 505 505 505
1020 506 506 506 506
1020 507 507 507 507
1020 508 508 508 508
1020 509 509 509 509
1020 510 510 510 510
1020 511 511 511 511
1020 512 512 512 512
1020 513 513 513 513
1020 514 514 514 514
1020 515 515 515 515
1020 516 516 516 516
1020 517 517 517 517
1020 518 518 518 518
1020 519 519 519 519
1020 520 520 520 520
1020 521 521 521 521
1020 522 522 522 522
1020 523 523 523 523
1020 524 524 524 524
1020 525 525 525 525
1020 526 526 526 526
1020 527 527 527 527
1020 528 528 528 528
1020 529 529 529 529
1020 530 530 530 530
1020 531 531 531 531
1020 532 532 532 532
1020 533 533 533 533
1020 534 534 534 534
1020 535 535 535 535
1020 536 536 536 536
1020 537 537 537 537
1020 538 538 538 538
1020 539 539 539 539
1020 540 540 540 540
1020 541 541 541 541
1020 542 542 542 542
1020 543 543 543 543
1020 544 544 544 544
1020 545 545 545 545
1020 546 546 546 546
1020 547 547 547 547
1020 548 548 548 548
1020 549 549 549 549
1020 550 550 550 550
1020 551 551 551 551
1020 552 552 552 552
1020 553 553 553 553
1020 554 554 554 554
1020 555 555 555 555
1020 556 556 556 556
1020 557 557 557 557
1020 558 558 558 558
1020 559 559 559 559
1020 560 560 560 560
1020 561 561 561 561
1020 562 562 562 562
1020 563 563 563 563
1020 564 564 564 564
1020 565 565 565 565
1020 566 566 566 566
1020 567 567 567 567
1020 568 568 568 568
1020 569 569 569 569
1020 570 570 570 570
1020 571 571 571 571
1020 572 572 572 572
1020 573 573 573 573
1020 574 574 574 574
1020 575 575 575 575
1020 576 576 576 576
1020 577 577 577 577
1020 578 578 578 578
1020 579 579 579 579
1020 580 580 580 580
1020 581 581 581 581
1020 582 582 582 582
1020 583 583 583 583
1020 584 584 584 584
1020 585 585 585 585
1020 586 586 586 586
1020 587 587 587 587
1020 588 588 588 588
1020 589 589 589 589
1020 590 590 590 590
1020 591 591 591 591

WebDriverException: Message: unknown error: cannot determine loading status
from disconnected: received Inspector.detached event
  (Session info: chrome=93.0.4577.82)

In [303]:
print(len(urls),len(model),len(km),len(location),len(price))

1020 591 591 591 591

In [304]:
cars24_4=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                       'Transmission':(transmission),
                  'Number_of_Owners':(owner),
                   'Location':(city[4]),
                  'Price':(price)})
cars24_4

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Transmission,Number_of_Owners,Location,Price
0,Maruti,Maruti Alto K10 VXI MANUAL,VXI MANUAL,2015,Petrol,12341,MANUAL,2,Pune,328599
1,Maruti,Maruti Alto K10 LXI MANUAL,LXI MANUAL,2010,Petrol,28869,MANUAL,2,Pune,167499
2,Maruti,Maruti Swift Dzire VDI BS IV MANUAL,VDI BS IV MANUAL,2013,Diesel,53675,MANUAL,1,Pune,457299
3,Maruti,Maruti Wagon R 1.0 VXI MANUAL,VXI MANUAL,2017,Petrol,11047,MANUAL,3,Pune,403799
4,Hyundai,Hyundai Grand i10 SPORTS 1.2 VTVT MANUAL,SPORTS 1.2 VTVT MANUAL,2016,Petrol,10484,MANUAL,1,Pune,452099
...,...,...,...,...,...,...,...,...,...,...
586,Maruti,Maruti Swift Dzire VXI 1.2 BS IV MANUAL,VXI 1.2 BS IV MANUAL,2015,Petrol,57742,MANUAL,2,Pune,427299
587,Hyundai,Hyundai Creta 1.6 SX (O) CRDI MANUAL,1.6 SX (O) CRDI MANUAL,2015,Diesel,41245,MANUAL,1,Pune,869199
588,Maruti,Maruti Celerio VXI AMT AUTOMATIC,VXI AMT AUTOMATIC,2017,Petrol,89173,AUTOMATIC,1,Pune,374299
589,Honda,Honda City S MT PETROL MANUAL,S MT PETROL MANUAL,2009,Petrol,67524,MANUAL,2,Pune,217299
590,Maruti,Maruti Swift VDI MANUAL,VDI MANUAL,2018,Diesel,29446,MANUAL,1,Pune,625799

In [305]:
cars24_4['Source']='Cars24'
cars24_4.to_csv('cars24_4.csv')

In [306]:
driver.close()

NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=93.0.4577.82)

In [307]:
#city_5

In [308]:
driver=webdriver.Chrome("chromedriver.exe")
driver.get('https://www.cars24.com')

In [309]:
button_ele=driver.find_element_by_xpath('//div[@class="_1K8Qe"]//button')
button_ele.click()

In [310]:
city_ele=driver.find_elements_by_xpath('//ul[@class="_16Bvy"]//li')
for ele in city_ele:
    city.append(ele.text)
city_ele[5].click()
city[5]

'Bengaluru'

In [311]:
time.sleep(10)
viewallcars_ele=driver.find_element_by_xpath('//span[@class="jVs6G"]//a')
viewallcars_ele.click()

In [317]:
time.sleep(10)
for _ in range(2000):
    driver.execute_script('window.scrollBy(0,10)')

In [318]:
url_ele=driver.find_elements_by_xpath('//div[@class="col-4"]//a')
urls=[]
for info in url_ele:
    urls.append(info.get_attribute('href'))
len(urls)

859

In [320]:
brand=[]
model=[]
variant=[]
make_year=[]
fuel=[]
km=[]
transmission=[]
owner=[]
location=[]
price=[]

In [321]:
#city[5]
for url in urls:
    driver.get(url)
    model_ele=driver.find_element_by_xpath('//div[@class="_10kZS"]//h2')
    model.append(model_ele.text[5:])
    
    str=model_ele.text
    for i in range(len(str)):
        if str[i]==' ':
            x=i
            break

    for i in range(x+1,len(str)):
        if str[i]==' ':
            y=i
            break

    brand.append(str[x+1:y])
    
    var_ele=driver.find_element_by_xpath('//div[@class="_10kZS"]//h2//span')
    variant.append(var_ele.text)
    
    info_ele=driver.find_elements_by_xpath('//strong[@class="_1-PH2"]')
    if len(info_ele)==9:
        make_year.append(info_ele[8].text[-4:])
        fuel.append(info_ele[3].text)
        km.append(info_ele[2].text[:-3].replace(',',''))
        owner.append(info_ele[1].text[0])
        transmission.append(info_ele[5].text)   
        location.append(city[5])
        
    elif len(info_ele)==8:
        make_year.append(info_ele[7].text[-4:])
        fuel.append(info_ele[3].text)
        km.append(info_ele[2].text[:-3].replace(',',''))
        owner.append(info_ele[1].text[0])
        transmission.append(info_ele[4].text)   
        location.append(city[5])
   
    price_ele=driver.find_element_by_xpath('//strong[@class="_2yYvS"]')
    str=price_ele.text
    for i in range(1,len(str)):
        if str[i]=='₹':
            x=i

    price.append(str[x+1:].replace(',',''))
    print(len(urls),len(model),len(km),len(location),len(price))

859 1 1 1 1
859 2 2 2 2
859 3 3 3 3
859 4 4 4 4
859 5 5 5 5
859 6 6 6 6
859 7 7 7 7
859 8 8 8 8
859 9 9 9 9
859 10 10 10 10
859 11 11 11 11
859 12 12 12 12
859 13 13 13 13
859 14 14 14 14
859 15 15 15 15
859 16 16 16 16
859 17 17 17 17
859 18 18 18 18
859 19 19 19 19
859 20 20 20 20
859 21 21 21 21
859 22 22 22 22
859 23 23 23 23
859 24 24 24 24
859 25 25 25 25
859 26 26 26 26
859 27 27 27 27
859 28 28 28 28
859 29 29 29 29
859 30 30 30 30
859 31 31 31 31
859 32 32 32 32
859 33 33 33 33
859 34 34 34 34
859 35 35 35 35
859 36 36 36 36
859 37 37 37 37
859 38 38 38 38
859 39 39 39 39
859 40 40 40 40
859 41 41 41 41
859 42 42 42 42
859 43 43 43 43
859 44 44 44 44
859 45 45 45 45
859 46 46 46 46
859 47 47 47 47
859 48 48 48 48
859 49 49 49 49
859 50 50 50 50
859 51 51 51 51
859 52 52 52 52
859 53 53 53 53
859 54 54 54 54
859 55 55 55 55
859 56 56 56 56
859 57 57 57 57
859 58 58 58 58
859 59 59 59 59
859 60 60 60 60
859 61 61 61 61
859 62 62 62 62
859 63 63 63 63
859 64 64 64 64
859 65 65 65 65
859 66 66 66 66
859 67 67 67 67
859 68 68 68 68
859 69 69 69 69
859 70 70 70 70
859 71 71 71 71
859 72 72 72 72
859 73 73 73 73
859 74 74 74 74
859 75 75 75 75
859 76 76 76 76
859 77 77 77 77
859 78 78 78 78
859 79 79 79 79
859 80 80 80 80
859 81 81 81 81
859 82 82 82 82
859 83 83 83 83
859 84 84 84 84
859 85 85 85 85
859 86 86 86 86
859 87 87 87 87
859 88 88 88 88
859 89 89 89 89
859 90 90 90 90
859 91 91 91 91
859 92 92 92 92
859 93 93 93 93
859 94 94 94 94
859 95 95 95 95
859 96 96 96 96
859 97 97 97 97
859 98 98 98 98
859 99 99 99 99
859 100 100 100 100
859 101 101 101 101
859 102 102 102 102
859 103 103 103 103
859 104 104 104 104
859 105 105 105 105
859 106 106 106 106
859 107 107 107 107
859 108 108 108 108
859 109 109 109 109
859 110 110 110 110
859 111 111 111 111
859 112 112 112 112
859 113 113 113 113
859 114 114 114 114
859 115 115 115 115
859 116 116 116 116
859 117 117 117 117
859 118 118 118 118
859 119 119 119 119
859 120 120 120 120
859 121 121 121 121
859 122 122 122 122
859 123 123 123 123
859 124 124 124 124
859 125 125 125 125
859 126 126 126 126
859 127 127 127 127
859 128 128 128 128
859 129 129 129 129
859 130 130 130 130
859 131 131 131 131
859 132 132 132 132
859 133 133 133 133
859 134 134 134 134
859 135 135 135 135
859 136 136 136 136
859 137 137 137 137
859 138 138 138 138
859 139 139 139 139
859 140 140 140 140
859 141 141 141 141
859 142 142 142 142
859 143 143 143 143
859 144 144 144 144
859 145 145 145 145
859 146 146 146 146
859 147 147 147 147
859 148 148 148 148
859 149 149 149 149
859 150 150 150 150
859 151 151 151 151
859 152 152 152 152
859 153 153 153 153
859 154 154 154 154
859 155 155 155 155
859 156 156 156 156
859 157 157 157 157
859 158 158 158 158
859 159 159 159 159
859 160 160 160 160
859 161 161 161 161
859 162 162 162 162
859 163 163 163 163
859 164 164 164 164
859 165 165 165 165
859 166 166 166 166
859 167 167 167 167
859 168 168 168 168
859 169 169 169 169
859 170 170 170 170
859 171 171 171 171
859 172 172 172 172
859 173 173 173 173
859 174 174 174 174
859 175 175 175 175
859 176 176 176 176
859 177 177 177 177
859 178 178 178 178
859 179 179 179 179
859 180 180 180 180
859 181 181 181 181
859 182 182 182 182
859 183 183 183 183
859 184 184 184 184
859 185 185 185 185
859 186 186 186 186
859 187 187 187 187
859 188 188 188 188
859 189 189 189 189
859 190 190 190 190
859 191 191 191 191
859 192 192 192 192
859 193 193 193 193
859 194 194 194 194
859 195 195 195 195
859 196 196 196 196
859 197 197 197 197
859 198 198 198 198
859 199 199 199 199
859 200 200 200 200
859 201 201 201 201
859 202 202 202 202
859 203 203 203 203
859 204 204 204 204
859 205 205 205 205
859 206 206 206 206
859 207 207 207 207
859 208 208 208 208
859 209 209 209 209
859 210 210 210 210
859 211 211 211 211
859 212 212 212 212
859 213 213 213 213
859 214 214 214 214
859 215 215 215 215
859 216 216 216 216
859 217 217 217 217
859 218 218 218 218
859 219 219 219 219
859 220 220 220 220
859 221 221 221 221
859 222 222 222 222
859 223 223 223 223
859 224 224 224 224
859 225 225 225 225
859 226 226 226 226
859 227 227 227 227
859 228 228 228 228
859 229 229 229 229
859 230 230 230 230
859 231 231 231 231
859 232 232 232 232
859 233 233 233 233
859 234 234 234 234
859 235 235 235 235
859 236 236 236 236
859 237 237 237 237
859 238 238 238 238
859 239 239 239 239
859 240 240 240 240
859 241 241 241 241
859 242 242 242 242
859 243 243 243 243
859 244 244 244 244
859 245 245 245 245
859 246 246 246 246
859 247 247 247 247
859 248 248 248 248
859 249 249 249 249
859 250 250 250 250
859 251 251 251 251
859 252 252 252 252
859 253 253 253 253
859 254 254 254 254
859 255 255 255 255
859 256 256 256 256
859 257 257 257 257
859 258 258 258 258
859 259 259 259 259
859 260 260 260 260
859 261 261 261 261
859 262 262 262 262
859 263 263 263 263
859 264 264 264 264
859 265 265 265 265
859 266 266 266 266
859 267 267 267 267
859 268 268 268 268
859 269 269 269 269
859 270 270 270 270
859 271 271 271 271
859 272 272 272 272
859 273 273 273 273
859 274 274 274 274
859 275 275 275 275
859 276 276 276 276
859 277 277 277 277
859 278 278 278 278
859 279 279 279 279
859 280 280 280 280
859 281 281 281 281
859 282 282 282 282
859 283 283 283 283
859 284 284 284 284
859 285 285 285 285
859 286 286 286 286
859 287 287 287 287
859 288 288 288 288
859 289 289 289 289
859 290 290 290 290
859 291 291 291 291
859 292 292 292 292
859 293 293 293 293
859 294 294 294 294
859 295 295 295 295
859 296 296 296 296
859 297 297 297 297
859 298 298 298 298
859 299 299 299 299
859 300 300 300 300
859 301 301 301 301
859 302 302 302 302
859 303 303 303 303
859 304 304 304 304
859 305 305 305 305
859 306 306 306 306
859 307 307 307 307
859 308 308 308 308
859 309 309 309 309
859 310 310 310 310
859 311 311 311 311
859 312 312 312 312
859 313 313 313 313
859 314 314 314 314
859 315 315 315 315
859 316 316 316 316
859 317 317 317 317
859 318 318 318 318
859 319 319 319 319
859 320 320 320 320
859 321 321 321 321
859 322 322 322 322
859 323 323 323 323
859 324 324 324 324
859 325 325 325 325
859 326 326 326 326
859 327 327 327 327
859 328 328 328 328
859 329 329 329 329
859 330 330 330 330
859 331 331 331 331
859 332 332 332 332
859 333 333 333 333
859 334 334 334 334
859 335 335 335 335
859 336 336 336 336
859 337 337 337 337
859 338 338 338 338
859 339 339 339 339
859 340 340 340 340
859 341 341 341 341
859 342 342 342 342
859 343 343 343 343
859 344 344 344 344
859 345 345 345 345
859 346 346 346 346
859 347 347 347 347
859 348 348 348 348
859 349 349 349 349
859 350 350 350 350
859 351 351 351 351
859 352 352 352 352
859 353 353 353 353
859 354 354 354 354
859 355 355 355 355
859 356 356 356 356
859 357 357 357 357
859 358 358 358 358
859 359 359 359 359
859 360 360 360 360
859 361 361 361 361
859 362 362 362 362
859 363 363 363 363
859 364 364 364 364
859 365 365 365 365
859 366 366 366 366
859 367 367 367 367
859 368 368 368 368
859 369 369 369 369
859 370 370 370 370
859 371 371 371 371
859 372 372 372 372
859 373 373 373 373
859 374 374 374 374
859 375 375 375 375
859 376 376 376 376
859 377 377 377 377
859 378 378 378 378
859 379 379 379 379
859 380 380 380 380
859 381 381 381 381
859 382 382 382 382
859 383 383 383 383
859 384 384 384 384
859 385 385 385 385
859 386 386 386 386
859 387 387 387 387
859 388 388 388 388
859 389 389 389 389
859 390 390 390 390
859 391 391 391 391
859 392 392 392 392
859 393 393 393 393
859 394 394 394 394
859 395 395 395 395
859 396 396 396 396
859 397 397 397 397
859 398 398 398 398
859 399 399 399 399
859 400 400 400 400
859 401 401 401 401
859 402 402 402 402
859 403 403 403 403
859 404 404 404 404
859 405 405 405 405
859 406 406 406 406
859 407 407 407 407
859 408 408 408 408
859 409 409 409 409
859 410 410 410 410
859 411 411 411 411
859 412 412 412 412
859 413 413 413 413
859 414 414 414 414
859 415 415 415 415
859 416 416 416 416
859 417 417 417 417
859 418 418 418 418
859 419 419 419 419
859 420 420 420 420
859 421 421 421 421
859 422 422 422 422
859 423 423 423 423
859 424 424 424 424
859 425 425 425 425
859 426 426 426 426
859 427 427 427 427
859 428 428 428 428
859 429 429 429 429
859 430 430 430 430
859 431 431 431 431
859 432 432 432 432

859 433 433 433 433
859 434 434 434 434
859 435 435 435 435
859 436 436 436 436
859 437 437 437 437
859 438 438 438 438
859 439 439 439 439
859 440 440 440 440
859 441 441 441 441
859 442 442 442 442
859 443 443 443 443
859 444 444 444 444
859 445 445 445 445
859 446 446 446 446
859 447 447 447 447
859 448 448 448 448
859 449 449 449 449
859 450 450 450 450
859 451 451 451 451
859 452 452 452 452
859 453 453 453 453
859 454 454 454 454
859 455 455 455 455
859 456 456 456 456
859 457 457 457 457
859 458 458 458 458
859 459 459 459 459
859 460 460 460 460
859 461 461 461 461
859 462 462 462 462
859 463 463 463 463
859 464 464 464 464
859 465 465 465 465
859 466 466 466 466
859 467 467 467 467
859 468 468 468 468
859 469 469 469 469
859 470 470 470 470
859 471 471 471 471
859 472 472 472 472
859 473 473 473 473
859 474 474 474 474
859 475 475 475 475
859 476 476 476 476
859 477 477 477 477
859 478 478 478 478
859 479 479 479 479
859 480 480 480 480
859 481 481 481 481
859 482 482 482 482
859 483 483 483 483
859 484 484 484 484
859 485 485 485 485
859 486 486 486 486
859 487 487 487 487
859 488 488 488 488
859 489 489 489 489
859 490 490 490 490
859 491 491 491 491
859 492 492 492 492
859 493 493 493 493
859 494 494 494 494
859 495 495 495 495
859 496 496 496 496
859 497 497 497 497
859 498 498 498 498
859 499 499 499 499
859 500 500 500 500
859 501 501 501 501
859 502 502 502 502
859 503 503 503 503
859 504 504 504 504
859 505 505 505 505
859 506 506 506 506
859 507 507 507 507
859 508 508 508 508
859 509 509 509 509
859 510 510 510 510
859 511 511 511 511
859 512 512 512 512
859 513 513 513 513
859 514 514 514 514
859 515 515 515 515
859 516 516 516 516
859 517 517 517 517
859 518 518 518 518
859 519 519 519 519
859 520 520 520 520
859 521 521 521 521
859 522 522 522 522
859 523 523 523 523
859 524 524 524 524
859 525 525 525 525
859 526 526 526 526
859 527 527 527 527
859 528 528 528 528
859 529 529 529 529
859 530 530 530 530
859 531 531 531 531
859 532 532 532 532
859 533 533 533 533
859 534 534 534 534
859 535 535 535 535
859 536 536 536 536
859 537 537 537 537
859 538 538 538 538
859 539 539 539 539
859 540 540 540 540
859 541 541 541 541
859 542 542 542 542
859 543 543 543 543
859 544 544 544 544
859 545 545 545 545
859 546 546 546 546
859 547 547 547 547
859 548 548 548 548
859 549 549 549 549
859 550 550 550 550
859 551 551 551 551
859 552 552 552 552
859 553 553 553 553
859 554 554 554 554
859 555 555 555 555
859 556 556 556 556
859 557 557 557 557
859 558 558 558 558
859 559 559 559 559
859 560 560 560 560
859 561 561 561 561
859 562 562 562 562
859 563 563 563 563
859 564 564 564 564
859 565 565 565 565
859 566 566 566 566
859 567 567 567 567
859 568 568 568 568
859 569 569 569 569
859 570 570 570 570
859 571 571 571 571
859 572 572 572 572
859 573 573 573 573
859 574 574 574 574
859 575 575 575 575
859 576 576 576 576
859 577 577 577 577
859 578 578 578 578
859 579 579 579 579
859 580 580 580 580
859 581 581 581 581
859 582 582 582 582
859 583 583 583 583
859 584 584 584 584
859 585 585 585 585
859 586 586 586 586
859 587 587 587 587
859 588 588 588 588
859 589 589 589 589
859 590 590 590 590
859 591 591 591 591
859 592 592 592 592
859 593 593 593 593
859 594 594 594 594
859 595 595 595 595
859 596 596 596 596
859 597 597 597 597
859 598 598 598 598
859 599 599 599 599
859 600 600 600 600
859 601 601 601 601
859 602 602 602 602
859 603 603 603 603
859 604 604 604 604
859 605 605 605 605
859 606 606 606 606
859 607 607 607 607
859 608 608 608 608
859 609 609 609 609
859 610 610 610 610
859 611 611 611 611
859 612 612 612 612
859 613 613 613 613
859 614 614 614 614
859 615 615 615 615
859 616 616 616 616
859 617 617 617 617
859 618 618 618 618
859 619 619 619 619
859 620 620 620 620
859 621 621 621 621
859 622 622 622 622
859 623 623 623 623
859 624 624 624 624
859 625 625 625 625
859 626 626 626 626
859 627 627 627 627
859 628 628 628 628
859 629 629 629 629
859 630 630 630 630
859 631 631 631 631
859 632 632 632 632
859 633 633 633 633
859 634 634 634 634
859 635 635 635 635

WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT
  (Session info: chrome=93.0.4577.82)

In [322]:
cars24_5=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                       'Transmission':(transmission),
                  'Number_of_Owners':(owner),
                   'Location':(city[5]),
                  'Price':(price)})
cars24_5

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Transmission,Number_of_Owners,Location,Price
0,Maruti,Maruti Wagon R 1.0 VXI MANUAL,VXI MANUAL,2011,Petrol,32725,MANUAL,1,Bengaluru,339299
1,Maruti,Maruti Alto LXI MANUAL,LXI MANUAL,2009,Petrol,38264,MANUAL,1,Bengaluru,225899
2,Maruti,Maruti Alto LXI MANUAL,LXI MANUAL,2008,Petrol,45812,MANUAL,2,Bengaluru,194499
3,Maruti,Maruti S PRESSO VXI AGS AUTOMATIC,VXI AGS AUTOMATIC,2020,Petrol,5699,AUTOMATIC,1,Bengaluru,487199
4,Maruti,Maruti Ritz VXI BS IV MANUAL,VXI BS IV MANUAL,2010,Petrol,27602,MANUAL,1,Bengaluru,353499
...,...,...,...,...,...,...,...,...,...,...
630,Ford,Ford Ecosport 1.5 TITANIUM TI VCT MANUAL,1.5 TITANIUM TI VCT MANUAL,2014,Petrol,19207,MANUAL,3,Bengaluru,538499
631,Hyundai,Hyundai i20 SPORTZ 1.2 VTVT MANUAL,SPORTZ 1.2 VTVT MANUAL,2012,Petrol,45323,MANUAL,1,Bengaluru,462899
632,Maruti,Maruti Swift ZDI MANUAL,ZDI MANUAL,2014,Diesel,35205,MANUAL,1,Bengaluru,572799
633,Chevrolet,Chevrolet Beat LT DIESEL MANUAL,LT DIESEL MANUAL,2012,Diesel,32903,MANUAL,1,Bengaluru,259299
634,Maruti,Maruti Alto 800 VXI MANUAL,VXI MANUAL,2013,Petrol,18516,MANUAL,1,Bengaluru,275999

In [323]:
cars24_5['Source']='Cars24'
cars24_5.to_csv('cars24_5.csv')

In [334]:
driver.close()

In [325]:
#city_6

In [335]:
driver=webdriver.Chrome("chromedriver.exe")
driver.get('https://www.cars24.com')

In [336]:
button_ele=driver.find_element_by_xpath('//div[@class="_1K8Qe"]//button')
button_ele.click()

In [337]:
city_ele=driver.find_elements_by_xpath('//ul[@class="_16Bvy"]//li')
for ele in city_ele:
    city.append(ele.text)
city_ele[6].click()
city[6]

'Hyderabad'

In [338]:
time.sleep(10)
viewallcars_ele=driver.find_element_by_xpath('//span[@class="jVs6G"]//a')
viewallcars_ele.click()

In [339]:
time.sleep(10)
for _ in range(2000):
    driver.execute_script('window.scrollBy(0,10)')

In [340]:
url_ele=driver.find_elements_by_xpath('//div[@class="col-4"]//a')
urls=[]
for info in url_ele:
    urls.append(info.get_attribute('href'))
len(urls)

311

In [341]:
brand=[]
model=[]
variant=[]
make_year=[]
fuel=[]
km=[]
transmission=[]
owner=[]
location=[]
price=[]

In [342]:
#city[6]
for url in urls:
    driver.get(url)
    model_ele=driver.find_element_by_xpath('//div[@class="_10kZS"]//h2')
    model.append(model_ele.text[5:])
    
    str=model_ele.text
    for i in range(len(str)):
        if str[i]==' ':
            x=i
            break

    for i in range(x+1,len(str)):
        if str[i]==' ':
            y=i
            break

    brand.append(str[x+1:y])
    
    var_ele=driver.find_element_by_xpath('//div[@class="_10kZS"]//h2//span')
    variant.append(var_ele.text)
    
    info_ele=driver.find_elements_by_xpath('//strong[@class="_1-PH2"]')
    if len(info_ele)==9:
        make_year.append(info_ele[8].text[-4:])
        fuel.append(info_ele[3].text)
        km.append(info_ele[2].text[:-3].replace(',',''))
        owner.append(info_ele[1].text[0])
        transmission.append(info_ele[5].text)   
        location.append(city[6])
        
    elif len(info_ele)==8:
        make_year.append(info_ele[7].text[-4:])
        fuel.append(info_ele[3].text)
        km.append(info_ele[2].text[:-3].replace(',',''))
        owner.append(info_ele[1].text[0])
        transmission.append(info_ele[4].text)   
        location.append(city[6])
    
    price_ele=driver.find_element_by_xpath('//strong[@class="_2yYvS"]')
    str=price_ele.text
    for i in range(1,len(str)):
        if str[i]=='₹':
            x=i

    price.append(str[x+1:].replace(',',''))
    print(len(urls),len(model),len(km),len(location),len(price))

311 1 1 1 1
311 2 2 2 2
311 3 3 3 3
311 4 4 4 4
311 5 5 5 5
311 6 6 6 6
311 7 7 7 7
311 8 8 8 8
311 9 9 9 9
311 10 10 10 10
311 11 11 11 11
311 12 12 12 12
311 13 13 13 13
311 14 14 14 14
311 15 15 15 15
311 16 16 16 16
311 17 17 17 17
311 18 18 18 18
311 19 19 19 19
311 20 20 20 20
311 21 21 21 21
311 22 22 22 22
311 23 23 23 23
311 24 24 24 24
311 25 25 25 25
311 26 26 26 26
311 27 27 27 27
311 28 28 28 28
311 29 29 29 29
311 30 30 30 30
311 31 31 31 31
311 32 32 32 32
311 33 33 33 33
311 34 34 34 34
311 35 35 35 35
311 36 36 36 36
311 37 37 37 37
311 38 38 38 38
311 39 39 39 39
311 40 40 40 40
311 41 41 41 41
311 42 42 42 42
311 43 43 43 43
311 44 44 44 44
311 45 45 45 45
311 46 46 46 46
311 47 47 47 47
311 48 48 48 48
311 49 49 49 49
311 50 50 50 50
311 51 51 51 51
311 52 52 52 52
311 53 53 53 53
311 54 54 54 54
311 55 55 55 55
311 56 56 56 56
311 57 57 57 57
311 58 58 58 58
311 59 59 59 59
311 60 60 60 60
311 61 61 61 61
311 62 62 62 62
311 63 63 63 63
311 64 64 64 64
311 65 65 65 65
311 66 66 66 66
311 67 67 67 67
311 68 68 68 68
311 69 69 69 69
311 70 70 70 70
311 71 71 71 71
311 72 72 72 72
311 73 73 73 73
311 74 74 74 74
311 75 75 75 75
311 76 76 76 76
311 77 77 77 77
311 78 78 78 78
311 79 79 79 79
311 80 80 80 80
311 81 81 81 81
311 82 82 82 82
311 83 83 83 83
311 84 84 84 84
311 85 85 85 85
311 86 86 86 86
311 87 87 87 87
311 88 88 88 88
311 89 89 89 89
311 90 90 90 90
311 91 91 91 91
311 92 92 92 92
311 93 93 93 93
311 94 94 94 94
311 95 95 95 95
311 96 96 96 96
311 97 97 97 97
311 98 98 98 98
311 99 99 99 99
311 100 100 100 100
311 101 101 101 101
311 102 102 102 102
311 103 103 103 103
311 104 104 104 104
311 105 105 105 105
311 106 106 106 106
311 107 107 107 107
311 108 108 108 108
311 109 109 109 109
311 110 110 110 110
311 111 111 111 111
311 112 112 112 112
311 113 113 113 113
311 114 114 114 114
311 115 115 115 115
311 116 116 116 116
311 117 117 117 117
311 118 118 118 118
311 119 119 119 119
311 120 120 120 120
311 121 121 121 121
311 122 122 122 122
311 123 123 123 123
311 124 124 124 124
311 125 125 125 125
311 126 126 126 126
311 127 127 127 127
311 128 128 128 128
311 129 129 129 129
311 130 130 130 130
311 131 131 131 131
311 132 132 132 132
311 133 133 133 133
311 134 134 134 134
311 135 135 135 135
311 136 136 136 136
311 137 137 137 137
311 138 138 138 138
311 139 139 139 139
311 140 140 140 140
311 141 141 141 141
311 142 142 142 142
311 143 143 143 143
311 144 144 144 144
311 145 145 145 145
311 146 146 146 146
311 147 147 147 147
311 148 148 148 148
311 149 149 149 149
311 150 150 150 150
311 151 151 151 151
311 152 152 152 152
311 153 153 153 153
311 154 154 154 154
311 155 155 155 155
311 156 156 156 156
311 157 157 157 157
311 158 158 158 158
311 159 159 159 159
311 160 160 160 160
311 161 161 161 161
311 162 162 162 162
311 163 163 163 163
311 164 164 164 164
311 165 165 165 165
311 166 166 166 166
311 167 167 167 167
311 168 168 168 168
311 169 169 169 169
311 170 170 170 170
311 171 171 171 171
311 172 172 172 172
311 173 173 173 173
311 174 174 174 174
311 175 175 175 175
311 176 176 176 176
311 177 177 177 177
311 178 178 178 178
311 179 179 179 179
311 180 180 180 180
311 181 181 181 181
311 182 182 182 182
311 183 183 183 183
311 184 184 184 184
311 185 185 185 185
311 186 186 186 186
311 187 187 187 187
311 188 188 188 188
311 189 189 189 189
311 190 190 190 190
311 191 191 191 191
311 192 192 192 192
311 193 193 193 193
311 194 194 194 194
311 195 195 195 195
311 196 196 196 196
311 197 197 197 197
311 198 198 198 198
311 199 199 199 199
311 200 200 200 200
311 201 201 201 201
311 202 202 202 202
311 203 203 203 203
311 204 204 204 204
311 205 205 205 205
311 206 206 206 206
311 207 207 207 207
311 208 208 208 208

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="_10kZS"]//h2"}
  (Session info: chrome=93.0.4577.82)

In [343]:
cars24_6=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                       'Transmission':(transmission),
                  'Number_of_Owners':(owner),
                   'Location':(city[6]),
                  'Price':(price)})
cars24_6

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Transmission,Number_of_Owners,Location,Price
0,Maruti,Maruti Wagon R 1.0 LXI MANUAL,LXI MANUAL,2011,Petrol,20979,MANUAL,1,Hyderabad,328399
1,Maruti,Maruti Alto K10 LXI MANUAL,LXI MANUAL,2012,Petrol,36870,MANUAL,2,Hyderabad,219199
2,Maruti,Maruti Alto LXI MANUAL,LXI MANUAL,2011,Petrol,31119,MANUAL,1,Hyderabad,222499
3,Maruti,Maruti Alto LXI MANUAL,LXI MANUAL,2011,Petrol,23837,MANUAL,1,Hyderabad,224499
4,Maruti,Maruti Wagon R 1.0 LXI MANUAL,LXI MANUAL,2011,Petrol,63165,MANUAL,1,Hyderabad,295399
...,...,...,...,...,...,...,...,...,...,...
203,Maruti,Maruti Baleno ALPHA 1.2 K12 MANUAL,ALPHA 1.2 K12 MANUAL,2018,Petrol,16212,MANUAL,1,Hyderabad,703699
204,Maruti,Maruti Alto 800 LXI MANUAL,LXI MANUAL,2012,Petrol,44791,MANUAL,2,Hyderabad,256799
205,Hyundai,Hyundai Santro Xing GLS MANUAL,GLS MANUAL,2011,Petrol,70045,MANUAL,1,Hyderabad,231499
206,Maruti,Maruti Celerio ZXI OPT MANUAL,ZXI OPT MANUAL,2015,Petrol,43028,MANUAL,2,Hyderabad,376099
207,Hyundai,Hyundai Elite i20 ASTA 1.2 (O) MANUAL,ASTA 1.2 (O) MANUAL,2016,Petrol,38036,MANUAL,1,Hyderabad,655399

In [344]:
cars24_6['Source']='Cars24'
cars24_6.to_csv('cars24_6.csv')

In [345]:
driver.close()

In [346]:
#city_7

In [347]:
driver=webdriver.Chrome("chromedriver.exe")
driver.get('https://www.cars24.com')

In [348]:
button_ele=driver.find_element_by_xpath('//div[@class="_1K8Qe"]//button')
button_ele.click()

In [349]:
city_ele=driver.find_elements_by_xpath('//ul[@class="_16Bvy"]//li')
for ele in city_ele:
    city.append(ele.text)
city_ele[7].click()
city[7]

'Chennai'

In [350]:
time.sleep(10)
viewallcars_ele=driver.find_element_by_xpath('//span[@class="jVs6G"]//a')
viewallcars_ele.click()

In [352]:
time.sleep(10)
for _ in range(5000):
    driver.execute_script('window.scrollBy(0,10)')

In [354]:
url_ele=driver.find_elements_by_xpath('//div[@class="col-4"]//a')
urls=[]
for info in url_ele:
    urls.append(info.get_attribute('href'))
len(urls)

646

In [355]:
brand=[]
model=[]
variant=[]
make_year=[]
fuel=[]
km=[]
transmission=[]
owner=[]
location=[]
price=[]

In [356]:
#city[7]
for url in urls:
    driver.get(url)
    
    try:
        model_ele=driver.find_element_by_xpath('//div[@class="_10kZS"]//h2')
        model.append(model_ele.text[5:])
        str=model_ele.text
        for i in range(len(str)):
            if str[i]==' ':
                x=i
                break

        for i in range(x+1,len(str)):
            if str[i]==' ':
                y=i
                break

        brand.append(str[x+1:y])
    
    except NoSuchElementException:
            continue

    
    var_ele=driver.find_element_by_xpath('//div[@class="_10kZS"]//h2//span')
    variant.append(var_ele.text)
    
    info_ele=driver.find_elements_by_xpath('//strong[@class="_1-PH2"]')
    if len(info_ele)==9:
        make_year.append(info_ele[8].text[-4:])
        fuel.append(info_ele[3].text)
        km.append(info_ele[2].text[:-3].replace(',',''))
        owner.append(info_ele[1].text[0])
        transmission.append(info_ele[5].text)   
        location.append(city[7])
        
    elif len(info_ele)==8:
        make_year.append(info_ele[7].text[-4:])
        fuel.append(info_ele[3].text)
        km.append(info_ele[2].text[:-3].replace(',',''))
        owner.append(info_ele[1].text[0])
        transmission.append(info_ele[4].text)   
        location.append(city[7])
    
    price_ele=driver.find_element_by_xpath('//strong[@class="_2yYvS"]')
    str=price_ele.text
    for i in range(1,len(str)):
        if str[i]=='₹':
            x=i

    price.append(str[x+1:].replace(',',''))
    print(len(urls),len(model),len(km),len(location),len(price))

646 1 1 1 1
646 2 2 2 2
646 3 3 3 3
646 4 4 4 4
646 5 5 5 5
646 6 6 6 6
646 7 7 7 7
646 8 8 8 8
646 9 9 9 9
646 10 10 10 10
646 11 11 11 11
646 12 12 12 12
646 13 13 13 13
646 14 14 14 14
646 15 15 15 15
646 16 16 16 16
646 17 17 17 17
646 18 18 18 18
646 19 19 19 19
646 20 20 20 20
646 21 21 21 21
646 22 22 22 22
646 23 23 23 23
646 24 24 24 24
646 25 25 25 25
646 26 26 26 26
646 27 27 27 27
646 28 28 28 28
646 29 29 29 29
646 30 30 30 30
646 31 31 31 31
646 32 32 32 32
646 33 33 33 33
646 34 34 34 34
646 35 35 35 35
646 36 36 36 36
646 37 37 37 37
646 38 38 38 38
646 39 39 39 39
646 40 40 40 40
646 41 41 41 41
646 42 42 42 42
646 43 43 43 43
646 44 44 44 44
646 45 45 45 45
646 46 46 46 46
646 47 47 47 47
646 48 48 48 48
646 49 49 49 49
646 50 50 50 50
646 51 51 51 51
646 52 52 52 52
646 53 53 53 53
646 54 54 54 54
646 55 55 55 55
646 56 56 56 56
646 57 57 57 57
646 58 58 58 58
646 59 59 59 59
646 60 60 60 60
646 61 61 61 61
646 62 62 62 62
646 63 63 63 63
646 64 64 64 64
646 65 65 65 65
646 66 66 66 66
646 67 67 67 67
646 68 68 68 68
646 69 69 69 69
646 70 70 70 70
646 71 71 71 71
646 72 72 72 72
646 73 73 73 73
646 74 74 74 74
646 75 75 75 75
646 76 76 76 76
646 77 77 77 77
646 78 78 78 78
646 79 79 79 79
646 80 80 80 80
646 81 81 81 81
646 82 82 82 82
646 83 83 83 83
646 84 84 84 84
646 85 85 85 85
646 86 86 86 86
646 87 87 87 87
646 88 88 88 88
646 89 89 89 89
646 90 90 90 90
646 91 91 91 91
646 92 92 92 92
646 93 93 93 93
646 94 94 94 94
646 95 95 95 95
646 96 96 96 96
646 97 97 97 97
646 98 98 98 98
646 99 99 99 99
646 100 100 100 100
646 101 101 101 101
646 102 102 102 102
646 103 103 103 103
646 104 104 104 104
646 105 105 105 105
646 106 106 106 106
646 107 107 107 107
646 108 108 108 108
646 109 109 109 109
646 110 110 110 110
646 111 111 111 111
646 112 112 112 112
646 113 113 113 113
646 114 114 114 114
646 115 115 115 115
646 116 116 116 116
646 117 117 117 117
646 118 118 118 118
646 119 119 119 119
646 120 120 120 120
646 121 121 121 121
646 122 122 122 122
646 123 123 123 123
646 124 124 124 124
646 125 125 125 125
646 126 126 126 126
646 127 127 127 127
646 128 128 128 128
646 129 129 129 129
646 130 130 130 130
646 131 131 131 131
646 132 132 132 132
646 133 133 133 133
646 134 134 134 134
646 135 135 135 135
646 136 136 136 136
646 137 137 137 137
646 138 138 138 138
646 139 139 139 139
646 140 140 140 140
646 141 141 141 141
646 142 142 142 142
646 143 143 143 143
646 144 144 144 144
646 145 145 145 145
646 146 146 146 146
646 147 147 147 147
646 148 148 148 148
646 149 149 149 149
646 150 150 150 150
646 151 151 151 151
646 152 152 152 152
646 153 153 153 153
646 154 154 154 154
646 155 155 155 155
646 156 156 156 156
646 157 157 157 157
646 158 158 158 158
646 159 159 159 159
646 160 160 160 160
646 161 161 161 161
646 162 162 162 162
646 163 163 163 163
646 164 164 164 164
646 165 165 165 165
646 166 166 166 166
646 167 167 167 167
646 168 168 168 168
646 169 169 169 169
646 170 170 170 170
646 171 171 171 171
646 172 172 172 172
646 173 173 173 173
646 174 174 174 174
646 175 175 175 175
646 176 176 176 176
646 177 177 177 177
646 178 178 178 178
646 179 179 179 179
646 180 180 180 180
646 181 181 181 181
646 182 182 182 182
646 183 183 183 183
646 184 184 184 184
646 185 185 185 185
646 186 186 186 186
646 187 187 187 187
646 188 188 188 188
646 189 189 189 189
646 190 190 190 190
646 191 191 191 191
646 192 192 192 192
646 193 193 193 193
646 194 194 194 194
646 195 195 195 195
646 196 196 196 196
646 197 197 197 197
646 198 198 198 198
646 199 199 199 199
646 200 200 200 200
646 201 201 201 201
646 202 202 202 202
646 203 203 203 203
646 204 204 204 204
646 205 205 205 205
646 206 206 206 206
646 207 207 207 207
646 208 208 208 208
646 209 209 209 209
646 210 210 210 210
646 211 211 211 211
646 212 212 212 212
646 213 213 213 213
646 214 214 214 214
646 215 215 215 215
646 216 216 216 216
646 217 217 217 217
646 218 218 218 218
646 219 219 219 219
646 220 220 220 220
646 221 221 221 221
646 222 222 222 222
646 223 223 223 223
646 224 224 224 224
646 225 225 225 225
646 226 226 226 226
646 227 227 227 227
646 228 228 228 228
646 229 229 229 229
646 230 230 230 230
646 231 231 231 231
646 232 232 232 232
646 233 233 233 233
646 234 234 234 234
646 235 235 235 235
646 236 236 236 236
646 237 237 237 237
646 238 238 238 238
646 239 239 239 239
646 240 240 240 240
646 241 241 241 241
646 242 242 242 242
646 243 243 243 243
646 244 244 244 244
646 245 245 245 245
646 246 246 246 246
646 247 247 247 247
646 248 248 248 248
646 249 249 249 249
646 250 250 250 250
646 251 251 251 251
646 252 252 252 252
646 253 253 253 253
646 254 254 254 254
646 255 255 255 255
646 256 256 256 256
646 257 257 257 257
646 258 258 258 258
646 259 259 259 259
646 260 260 260 260
646 261 261 261 261
646 262 262 262 262
646 263 263 263 263
646 264 264 264 264
646 265 265 265 265
646 266 266 266 266
646 267 267 267 267
646 268 268 268 268
646 269 269 269 269
646 270 270 270 270
646 271 271 271 271
646 272 272 272 272
646 273 273 273 273
646 274 274 274 274
646 275 275 275 275
646 276 276 276 276
646 277 277 277 277
646 278 278 278 278
646 279 279 279 279
646 280 280 280 280
646 281 281 281 281
646 282 282 282 282
646 283 283 283 283
646 284 284 284 284
646 285 285 285 285
646 286 286 286 286
646 287 287 287 287
646 288 288 288 288
646 289 289 289 289
646 290 290 290 290
646 291 291 291 291
646 292 292 292 292
646 293 293 293 293
646 294 294 294 294
646 295 295 295 295
646 296 296 296 296
646 297 297 297 297
646 298 298 298 298
646 299 299 299 299
646 300 300 300 300
646 301 301 301 301
646 302 302 302 302
646 303 303 303 303
646 304 304 304 304
646 305 305 305 305
646 306 306 306 306
646 307 307 307 307
646 308 308 308 308
646 309 309 309 309
646 310 310 310 310
646 311 311 311 311
646 312 312 312 312
646 313 313 313 313
646 314 314 314 314
646 315 315 315 315
646 316 316 316 316
646 317 317 317 317
646 318 318 318 318
646 319 319 319 319
646 320 320 320 320
646 321 321 321 321
646 322 322 322 322
646 323 323 323 323
646 324 324 324 324
646 325 325 325 325
646 326 326 326 326
646 327 327 327 327
646 328 328 328 328
646 329 329 329 329
646 330 330 330 330
646 331 331 331 331
646 332 332 332 332
646 333 333 333 333
646 334 334 334 334
646 335 335 335 335
646 336 336 336 336
646 337 337 337 337
646 338 338 338 338
646 339 339 339 339
646 340 340 340 340
646 341 341 341 341
646 342 342 342 342
646 343 343 343 343
646 344 344 344 344
646 345 345 345 345

NoSuchWindowException: Message: no such window: window was already closed
  (Session info: chrome=93.0.4577.82)

In [357]:
cars24_7=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                       'Transmission':(transmission),
                  'Number_of_Owners':(owner),
                   'Location':(city[7]),
                  'Price':(price)})
cars24_7

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Transmission,Number_of_Owners,Location,Price
0,Maruti,Maruti Eeco 5 STR WITH AC PLUSHTR MANUAL,5 STR WITH AC PLUSHTR MANUAL,2017,Petrol,9328,MANUAL,1,Chennai,408999
1,Maruti,Maruti Alto LXI MANUAL,LXI MANUAL,2011,Petrol,23217,MANUAL,1,Chennai,248099
2,Maruti,Maruti Eeco 5 STR WITH AC PLUSHTR MANUAL,5 STR WITH AC PLUSHTR MANUAL,2014,Petrol,18371,MANUAL,1,Chennai,354499
3,Hyundai,Hyundai Grand i10 MAGNA 1.2 VTVT MANUAL,MAGNA 1.2 VTVT MANUAL,2015,Petrol,16026,MANUAL,1,Chennai,431099
4,Maruti,Maruti Alto K10 LXI MANUAL,LXI MANUAL,2010,Petrol,33888,MANUAL,1,Chennai,221799
...,...,...,...,...,...,...,...,...,...,...
340,Honda,Honda Amaze 1.2 V CVT I VTEC,1.2 V CVT I VTEC,2018,Petrol,29177,NA,1,Chennai,675899
341,Hyundai,Hyundai Eon ERA PLUS MANUAL,ERA PLUS MANUAL,2017,Petrol,50665,MANUAL,2,Chennai,352499
342,Ford,Ford Ecosport 1.5AMBIENTE TI VCT MANUAL,1.5AMBIENTE TI VCT MANUAL,2015,Petrol,85750,MANUAL,1,Chennai,534299
343,Hyundai,Hyundai Creta 1.6 SX CRDI,1.6 SX CRDI,2018,Diesel,47876,NA,1,Chennai,1112799
344,Tata,Tata Hexa Varicor 400 XT MANUAL,Varicor 400 XT MANUAL,2019,Diesel,34262,MANUAL,1,Chennai,1843499

In [358]:
cars24_7['Source']='Cars24'
cars24_7.to_csv('cars24_7.csv')

In [359]:
driver.close()

NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=93.0.4577.82)

In [360]:
#city_8

In [369]:
driver=webdriver.Chrome("chromedriver.exe")
driver.get('https://www.cars24.com')

In [370]:
button_ele=driver.find_element_by_xpath('//div[@class="_1K8Qe"]//button')
button_ele.click()

In [371]:
city_ele=driver.find_elements_by_xpath('//ul[@class="_16Bvy"]//li')
for ele in city_ele:
    city.append(ele.text)
city_ele[8].click()
city[8]

'Kolkata'

In [372]:
time.sleep(10)
viewallcars_ele=driver.find_element_by_xpath('//span[@class="jVs6G"]//a')
viewallcars_ele.click()

In [373]:
time.sleep(10)
for _ in range(10000):
    driver.execute_script('window.scrollBy(0,10)')

In [366]:
url_ele=driver.find_elements_by_xpath('//div[@class="col-4"]//a')
urls=[]
for info in url_ele:
    urls.append(info.get_attribute('href'))
len(urls)

279

In [375]:
brand=[]
model=[]
variant=[]
make_year=[]
fuel=[]
km=[]
transmission=[]
owner=[]
location=[]
price=[]

In [376]:
#city[8]
for url in urls:
    driver.get(url)
    try:
        model_ele=driver.find_element_by_xpath('//div[@class="_10kZS"]//h2')
        model.append(model_ele.text[5:])
        str=model_ele.text
        for i in range(len(str)):
            if str[i]==' ':
                x=i
                break

        for i in range(x+1,len(str)):
            if str[i]==' ':
                y=i
                break

        brand.append(str[x+1:y])
    
    except NoSuchElementException:
            continue
    
    var_ele=driver.find_element_by_xpath('//div[@class="_10kZS"]//h2//span')
    variant.append(var_ele.text)
    
    info_ele=driver.find_elements_by_xpath('//strong[@class="_1-PH2"]')
    if len(info_ele)==9:
        make_year.append(info_ele[8].text[-4:])
        fuel.append(info_ele[3].text)
        km.append(info_ele[2].text[:-3].replace(',',''))
        owner.append(info_ele[1].text[0])
        transmission.append(info_ele[5].text)   
        location.append(city[8])
        
    elif len(info_ele)==8:
        make_year.append(info_ele[7].text[-4:])
        fuel.append(info_ele[3].text)
        km.append(info_ele[2].text[:-3].replace(',',''))
        owner.append(info_ele[1].text[0])
        transmission.append(info_ele[4].text)   
        location.append(city[8])
    
    price_ele=driver.find_element_by_xpath('//strong[@class="_2yYvS"]')
    str=price_ele.text
    for i in range(1,len(str)):
        if str[i]=='₹':
            x=i

    price.append(str[x+1:].replace(',',''))
    print(len(urls),len(model),len(km),len(location),len(price))

279 1 1 1 1
279 2 2 2 2
279 3 3 3 3
279 4 4 4 4
279 5 5 5 5
279 6 6 6 6
279 7 7 7 7
279 8 8 8 8
279 9 9 9 9
279 10 10 10 10
279 11 11 11 11
279 12 12 12 12
279 13 13 13 13
279 14 14 14 14
279 15 15 15 15
279 16 16 16 16
279 17 17 17 17
279 18 18 18 18
279 19 19 19 19
279 20 20 20 20
279 21 21 21 21
279 22 22 22 22
279 23 23 23 23
279 24 24 24 24
279 25 25 25 25
279 26 26 26 26
279 27 27 27 27
279 28 28 28 28
279 29 29 29 29
279 30 30 30 30
279 31 31 31 31
279 32 32 32 32
279 33 33 33 33
279 34 34 34 34
279 35 35 35 35
279 36 36 36 36
279 37 37 37 37
279 38 38 38 38
279 39 39 39 39
279 40 40 40 40
279 41 41 41 41
279 42 42 42 42
279 43 43 43 43
279 44 44 44 44
279 45 45 45 45
279 46 46 46 46
279 47 47 47 47
279 48 48 48 48
279 49 49 49 49
279 50 50 50 50
279 51 51 51 51
279 52 52 52 52
279 53 53 53 53
279 54 54 54 54
279 55 55 55 55
279 56 56 56 56
279 57 57 57 57
279 58 58 58 58
279 59 59 59 59
279 60 60 60 60
279 61 61 61 61
279 62 62 62 62
279 63 63 63 63
279 64 64 64 64
279 65 65 65 65
279 66 66 66 66
279 67 67 67 67
279 68 68 68 68
279 69 69 69 69
279 70 70 70 70
279 71 71 71 71
279 72 72 72 72
279 73 73 73 73
279 74 74 74 74
279 75 75 75 75
279 76 76 76 76
279 77 77 77 77
279 78 78 78 78
279 79 79 79 79
279 80 80 80 80
279 81 81 81 81
279 82 82 82 82
279 83 83 83 83
279 84 84 84 84
279 85 85 85 85
279 86 86 86 86
279 87 87 87 87
279 88 88 88 88
279 89 89 89 89
279 90 90 90 90
279 91 91 91 91
279 92 92 92 92
279 93 93 93 93
279 94 94 94 94
279 95 95 95 95
279 96 96 96 96
279 97 97 97 97
279 98 98 98 98
279 99 99 99 99
279 100 100 100 100
279 101 101 101 101
279 102 102 102 102
279 103 103 103 103
279 104 104 104 104
279 105 105 105 105
279 106 106 106 106
279 107 107 107 107
279 108 108 108 108
279 109 109 109 109
279 110 110 110 110
279 111 111 111 111
279 112 112 112 112
279 113 113 113 113
279 114 114 114 114
279 115 115 115 115
279 116 116 116 116
279 117 117 117 117
279 118 118 118 118
279 119 119 119 119
279 120 120 120 120
279 121 121 121 121
279 122 122 122 122
279 123 123 123 123
279 124 124 124 124
279 125 125 125 125
279 126 126 126 126
279 127 127 127 127
279 128 128 128 128
279 129 129 129 129
279 130 130 130 130
279 131 131 131 131
279 132 132 132 132
279 133 133 133 133
279 134 134 134 134
279 135 135 135 135
279 136 136 136 136
279 137 137 137 137
279 138 138 138 138
279 139 139 139 139
279 140 140 140 140
279 141 141 141 141
279 142 142 142 142
279 143 143 143 143
279 144 144 144 144
279 145 145 145 145
279 146 146 146 146
279 147 147 147 147
279 148 148 148 148
279 149 149 149 149
279 150 150 150 150
279 151 151 151 151
279 152 152 152 152
279 153 153 153 153
279 154 154 154 154
279 155 155 155 155
279 156 156 156 156
279 157 157 157 157
279 158 158 158 158
279 159 159 159 159
279 160 160 160 160
279 161 161 161 161
279 162 162 162 162
279 163 163 163 163
279 164 164 164 164
279 165 165 165 165
279 166 166 166 166
279 167 167 167 167
279 168 168 168 168
279 169 169 169 169
279 170 170 170 170
279 171 171 171 171
279 172 172 172 172
279 173 173 173 173
279 174 174 174 174
279 175 175 175 175
279 176 176 176 176
279 177 177 177 177
279 178 178 178 178
279 179 179 179 179
279 180 180 180 180
279 181 181 181 181
279 182 182 182 182
279 183 183 183 183
279 184 184 184 184
279 185 185 185 185
279 186 186 186 186
279 187 187 187 187
279 188 188 188 188
279 189 189 189 189
279 190 190 190 190
279 191 191 191 191
279 192 192 192 192
279 193 193 193 193
279 194 194 194 194
279 195 195 195 195
279 196 196 196 196
279 197 197 197 197
279 198 198 198 198
279 199 199 199 199
279 200 200 200 200
279 201 201 201 201
279 202 202 202 202
279 203 203 203 203
279 204 204 204 204
279 205 205 205 205
279 206 206 206 206
279 207 207 207 207
279 208 208 208 208
279 209 209 209 209
279 210 210 210 210
279 211 211 211 211
279 212 212 212 212
279 213 213 213 213
279 214 214 214 214
279 215 215 215 215
279 216 216 216 216
279 217 217 217 217
279 218 218 218 218
279 219 219 219 219
279 220 220 220 220
279 221 221 221 221
279 222 222 222 222
279 223 223 223 223
279 224 224 224 224
279 225 225 225 225
279 226 226 226 226
279 227 227 227 227
279 228 228 228 228
279 229 229 229 229
279 230 230 230 230
279 231 231 231 231
279 232 232 232 232
279 233 233 233 233
279 234 234 234 234
279 235 235 235 235
279 236 236 236 236
279 237 237 237 237
279 238 238 238 238
279 239 239 239 239
279 240 240 240 240
279 241 241 241 241
279 242 242 242 242
279 243 243 243 243
279 244 244 244 244
279 245 245 245 245
279 246 246 246 246
279 247 247 247 247
279 248 248 248 248
279 249 249 249 249
279 250 250 250 250
279 251 251 251 251
279 252 252 252 252
279 253 253 253 253
279 254 254 254 254
279 255 255 255 255
279 256 256 256 256
279 257 257 257 257
279 258 258 258 258
279 259 259 259 259
279 260 260 260 260
279 261 261 261 261
279 262 262 262 262
279 263 263 263 263
279 264 264 264 264
279 265 265 265 265
279 266 266 266 266
279 267 267 267 267
279 268 268 268 268
279 269 269 269 269
279 270 270 270 270
279 271 271 271 271
279 272 272 272 272
279 273 273 273 273
279 274 274 274 274
279 275 275 275 275
279 276 276 276 276
279 277 277 277 277
279 278 278 278 278

In [377]:
cars24_8=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                       'Transmission':(transmission),
                  'Number_of_Owners':(owner),
                   'Location':(city[8]),
                  'Price':(price)})
cars24_8

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Transmission,Number_of_Owners,Location,Price
0,Hyundai,Hyundai Grand i10 SPORTZ 1.2 KAPPA VTVT MANUAL,SPORTZ 1.2 KAPPA VTVT MANUAL,2016,Petrol,12776,MANUAL,1,Kolkata,418599
1,Hyundai,Hyundai Elite i20 ASTA 1.2 MANUAL,ASTA 1.2 MANUAL,2015,Petrol,28228,MANUAL,2,Kolkata,465599
2,Maruti,Maruti Alto 800 LXI MANUAL,LXI MANUAL,2018,Petrol,727,MANUAL,1,Kolkata,336199
3,Honda,Honda Amaze 1.2 SMT I VTEC MANUAL,1.2 SMT I VTEC MANUAL,2013,Petrol,37382,MANUAL,1,Kolkata,312899
4,Hyundai,Hyundai Grand i10 MAGNA 1.2 VTVT MANUAL,MAGNA 1.2 VTVT MANUAL,2017,Petrol,20561,MANUAL,1,Kolkata,412899
...,...,...,...,...,...,...,...,...,...,...
273,Honda,Honda Amaze 1.5 SMT I DTEC MANUAL,1.5 SMT I DTEC MANUAL,2014,Diesel,101613,MANUAL,2,Kolkata,319699
274,Mahindra,Mahindra XUV500 W7 FWD MANUAL,W7 FWD MANUAL,2019,Diesel,10833,MANUAL,1,Kolkata,1085499
275,Honda,Honda Amaze 1.5 EXMT I DTEC MANUAL,1.5 EXMT I DTEC MANUAL,2013,Diesel,84592,MANUAL,1,Kolkata,261799
276,Toyota,Toyota Etios G MANUAL,G MANUAL,2014,Petrol,114767,MANUAL,1,Kolkata,294899
277,Fiat,Fiat Avvventura EMOTION MULTIJET 1.3 MANUAL,EMOTION MULTIJET 1.3 MANUAL,2014,Diesel,85145,MANUAL,1,Kolkata,500

In [378]:
cars24_8['Source']='Cars24'
cars24_8.to_csv('cars24_8.csv')

In [379]:
driver.close()

In [380]:
#city_9

In [428]:
driver=webdriver.Chrome("chromedriver.exe")
driver.get('https://www.cars24.com')

WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=93.0.4577.82)

In [382]:
button_ele=driver.find_element_by_xpath('//div[@class="_1K8Qe"]//button')
button_ele.click()

In [396]:
city_ele=driver.find_elements_by_xpath('//ul[@class="_16Bvy"]//li')
for ele in city_ele:
    city.append(ele.text)
city_ele[9].click()
city[9]

'Ahmedabad'

In [397]:
time.sleep(10)
viewallcars_ele=driver.find_element_by_xpath('//span[@class="jVs6G"]//a')
viewallcars_ele.click()

In [398]:
time.sleep(10)
for _ in range(10000):
    driver.execute_script('window.scrollBy(0,10)')

In [399]:
url_ele=driver.find_elements_by_xpath('//div[@class="col-4"]//a')
urls=[]
for info in url_ele:
    urls.append(info.get_attribute('href'))
len(urls)

497

In [387]:
brand=[]
model=[]
variant=[]
make_year=[]
fuel=[]
km=[]
transmission=[]
owner=[]
location=[]
price=[]

In [423]:
#city[9]
for url in urls:
    driver.get(url)
    try:
        model_ele=driver.find_element_by_xpath('//div[@class="_10kZS"]//h2')
        model.append(model_ele.text[5:])
        str=model_ele.text
        for i in range(len(str)):
            if str[i]==' ':
                x=i
                break

        for i in range(x+1,len(str)):
            if str[i]==' ':
                y=i
                break

        brand.append(str[x+1:y])
    
    except NoSuchElementException:
            continue
    var_ele=driver.find_element_by_xpath('//div[@class="_10kZS"]//h2//span')
    variant.append(var_ele.text)
    
    info_ele=driver.find_elements_by_xpath('//strong[@class="_1-PH2"]')
    if len(info_ele)==9:
        make_year.append(info_ele[8].text[-4:])
        fuel.append(info_ele[3].text)
        km.append(info_ele[2].text[:-3].replace(',',''))
        owner.append(info_ele[1].text[0])
        transmission.append(info_ele[5].text)   
        location.append(city[9])
        
    elif len(info_ele)==8:
        make_year.append(info_ele[7].text[-4:])
        fuel.append(info_ele[3].text)
        km.append(info_ele[2].text[:-3].replace(',',''))
        owner.append(info_ele[1].text[0])
        transmission.append(info_ele[4].text)   
        location.append(city[9])
    
    price_ele=driver.find_element_by_xpath('//strong[@class="_2yYvS"]')
    str=price_ele.text
    for i in range(1,len(str)):
        if str[i]=='₹':
            x=i

    price.append(str[x+1:].replace(',',''))
    print(len(urls),len(model),len(km),len(location),len(price))

497 329 329 329 329
497 330 330 330 330
497 331 331 331 331
497 332 332 332 332
497 333 333 333 333
497 334 334 334 334
497 335 335 335 335
497 336 336 336 336
497 337 337 337 337
497 338 338 338 338
497 339 339 339 339
497 340 340 340 340
497 341 341 341 341
497 342 342 342 342
497 343 343 343 343
497 344 344 344 344
497 345 345 345 345
497 346 346 346 346
497 347 347 347 347
497 348 348 348 348
497 349 349 349 349
497 350 350 350 350
497 351 351 351 351
497 352 352 352 352
497 353 353 353 353
497 354 354 354 354
497 355 355 355 355
497 356 356 356 356
497 357 357 357 357
497 358 358 358 358
497 359 359 359 359
497 360 360 360 360
497 361 361 361 361
497 362 362 362 362
497 363 363 363 363
497 364 364 364 364
497 365 365 365 365
497 366 366 366 366
497 367 367 367 367
497 368 368 368 368
497 369 369 369 369
497 370 370 370 370
497 371 371 371 371
497 372 372 372 372
497 373 373 373 373
497 374 374 374 374
497 375 375 375 375
497 376 376 376 376
497 377 377 377 377
497 378 378 378 378
497 379 379 379 379
497 380 380 380 380
497 381 381 381 381
497 382 382 382 382
497 383 383 383 383
497 384 384 384 384
497 385 385 385 385
497 386 386 386 386
497 387 387 387 387
497 388 388 388 388
497 389 389 389 389
497 390 390 390 390
497 391 391 391 391
497 392 392 392 392
497 393 393 393 393
497 394 394 394 394
497 395 395 395 395
497 396 396 396 396
497 397 397 397 397
497 398 398 398 398
497 399 399 399 399
497 400 400 400 400
497 401 401 401 401
497 402 402 402 402
497 403 403 403 403
497 404 404 404 404
497 405 405 405 405
497 406 406 406 406
497 407 407 407 407
497 408 408 408 408
497 409 409 409 409
497 410 410 410 410
497 411 411 411 411
497 412 412 412 412
497 413 413 413 413
497 414 414 414 414
497 415 415 415 415
497 416 416 416 416
497 417 417 417 417
497 418 418 418 418
497 419 419 419 419
497 420 420 420 420
497 421 421 421 421
497 422 422 422 422
497 423 423 423 423
497 424 424 424 424
497 425 425 425 425
497 426 426 426 426
497 427 427 427 427
497 428 428 428 428
497 429 429 429 429
497 430 430 430 430
497 431 431 431 431
497 432 432 432 432
497 433 433 433 433
497 434 434 434 434
497 435 435 435 435
497 436 436 436 436
497 437 437 437 437
497 438 438 438 438
497 439 439 439 439
497 440 440 440 440
497 441 441 441 441
497 442 442 442 442
497 443 443 443 443
497 444 444 444 444
497 445 445 445 445
497 446 446 446 446
497 447 447 447 447
497 448 448 448 448
497 449 449 449 449
497 450 450 450 450

NoSuchWindowException: Message: no such window: window was already closed
  (Session info: chrome=93.0.4577.82)

In [424]:
cars24_9=pd.DataFrame({'Brand':(brand),
                  'Model':(model),
                  'Variant':(variant),
                  'Make_Year':(make_year),
                  'Fuel':(fuel),
                  'Km_driven':(km),
                       'Transmission':(transmission),
                  'Number_of_Owners':(owner),
                   'Location':(city[9]),
                  'Price':(price)})
cars24_9

,Brand,Model,Variant,Make_Year,Fuel,Km_driven,Transmission,Number_of_Owners,Location,Price
0,Maruti,Maruti Baleno DELTA 1.2 K12 MANUAL,DELTA 1.2 K12 MANUAL,2020,Petrol,5672,MANUAL,1,Ahmedabad,648699
1,Maruti,Maruti Eeco 5 STR WITH AC PLUSHTR MANUAL,5 STR WITH AC PLUSHTR MANUAL,2019,Petrol,13464,MANUAL,1,Ahmedabad,491699
2,Maruti,Maruti Baleno DELTA 1.2 K12 MANUAL,DELTA 1.2 K12 MANUAL,2020,Petrol,4560,MANUAL,1,Ahmedabad,675699
3,Maruti,Maruti Alto K10 VXI MANUAL,VXI MANUAL,2016,Petrol,10179,MANUAL,1,Ahmedabad,331599
4,Maruti,Maruti Alto 800 LXI MANUAL,LXI MANUAL,2017,Petrol,16782,MANUAL,1,Ahmedabad,291399
...,...,...,...,...,...,...,...,...,...,...
445,Maruti,Maruti Swift VDI MANUAL,VDI MANUAL,2017,Diesel,40803,MANUAL,2,Ahmedabad,464199
446,Maruti,Maruti Baleno DELTA 1.2 K12 MANUAL,DELTA 1.2 K12 MANUAL,2019,Petrol,6444,MANUAL,1,Ahmedabad,607899
447,Maruti,Maruti Baleno DELTA 1.2 K12 MANUAL,DELTA 1.2 K12 MANUAL,2017,Petrol,42044,MANUAL,1,Ahmedabad,509199
448,Maruti,Maruti Baleno DELTA 1.2 K12 MANUAL,DELTA 1.2 K12 MANUAL,2017,Petrol,51919,MANUAL,1,Ahmedabad,526599
449,Maruti,Maruti Vitara Brezza ZDI PLUS DUAL TONE MANUAL,ZDI PLUS DUAL TONE MANUAL,2016,Diesel,25643,MANUAL,1,Ahmedabad,734999

In [429]:
cars24_9['Source']='Cars24'
cars24_9.to_csv('cars24_9.csv')

In [430]:
driver.close()